DBACreator: Capa.BLL.FacturaLN Class Reference
Capa.BLL.FacturaLN Class Reference
Public Member Functions
void Guardar (EncFactura factura)
Método que guarda el encabezado de la factura en la base de datos
int ObtenerNumeroDeFacturaActual ()
Obtiene el número siguiente de factura
void Guardar (EncFactura factura)
int ObtenerNumeroDeFacturaActual ()
Static Public Member Functions
static List< DetFactura > ObtenerDetallesPorCliente (int idCliente)
Obtiene las copras hechas por el cliente
static ClienteDetalle ObtenerDetallePorCodigo (int idCliente, string codigo)
Método usado para buscar una compra y empezar la realización de un examen
static void MarcarRealizado (string codigo)
Marca un examen como realizado
Detailed Description
Definition at line 11 of file FacturaLN.cs.
Member Function Documentation
Guardar()
void Capa.BLL.FacturaLN.Guardar (EncFactura factura)
Método que guarda el encabezado de la factura en la base de datos
Parameters
factura factura de la cuál extraerá los datos
Implements Capa.BLL.IFacturaLN.
Definition at line 17 of file FacturaLN.cs.
        {
            FacturaDB.Guardar(factura);
        }
References Capa.DAL.FacturaDB.Guardar().
MarcarRealizado()
static void Capa.BLL.FacturaLN.MarcarRealizado (string codigo) static
Marca un examen como realizado
Parameters
codigo busca por código
Definition at line 56 of file FacturaLN.cs.
        {
            FacturaDB.MarcarRealizado(codigo);
        }
References Capa.DAL.FacturaDB.MarcarRealizado().
Referenced by UI.RealizarExamen.comenzarExamen().
ObtenerDetallePorCodigo()
static ClienteDetalle Capa.BLL.FacturaLN.ObtenerDetallePorCodigo (int idCliente, string codigo) static
Método usado para buscar una compra y empezar la realización de un examen
Parameters
idCliente Cliente a buscar
codigo Codigo de la compra
Returns
retorna un dto para comenzar el examen
Definition at line 47 of file FacturaLN.cs.
        {
            return FacturaDB.ObtenerDetallePorCodigo(idCliente, codigo);
        }
References Capa.DAL.FacturaDB.ObtenerDetallePorCodigo().
Referenced by UI.RealizarExamen.btnRealizarExamen_Click().
ObtenerDetallesPorCliente()
static List< DetFactura > Capa.BLL.FacturaLN.ObtenerDetallesPorCliente (int idCliente) static
Obtiene las copras hechas por el cliente
Parameters
idCliente Cliente a consultar
Returns
Obtiene las copras hechas por el cliente
Definition at line 36 of file FacturaLN.cs.
        {
            return FacturaDB.ObtenerDetallesPorCliente(idCliente);
        }
References Capa.DAL.FacturaDB.ObtenerDetallesPorCliente().
ObtenerNumeroDeFacturaActual()
int Capa.BLL.FacturaLN.ObtenerNumeroDeFacturaActual ()
Obtiene el número siguiente de factura
Returns
retorna el número de factura siguiente
Implements Capa.BLL.IFacturaLN.
Definition at line 26 of file FacturaLN.cs.
        {
            return FacturaDB.ObtenerNumeroDeFacturaActual();
        }
References Capa.DAL.FacturaDB.ObtenerNumeroDeFacturaActual().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/FacturaLN.cs