DBACreator: Capa.BLL.PaisLN Class Reference
Capa.BLL.PaisLN Class Reference
Static Public Member Functions
static List< Pais > ObtenerTodos ()
Usado para ver todos los países
Detailed Description
Definition at line 11 of file PaisLN.cs.
Member Function Documentation
ObtenerTodos()
static List< Pais > Capa.BLL.PaisLN.ObtenerTodos () static
Usado para ver todos los países
Returns
retorna una lista con todos los países
Definition at line 17 of file PaisLN.cs.
        {
            return PaisDB.ObtenerTodos();
        }
References Capa.DAL.PaisDB.ObtenerTodos().
Referenced by UI.MantenimientoClientes.MantenimientoClientes_Load(), and UI.Registro.Registro_Load().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/PaisLN.cs