DBACreator: Capa.DAL.FacturaDB Class Reference
Capa.DAL.FacturaDB Class Reference
Static Public Member Functions
static void Guardar (EncFactura factura)
Método que guarda el encabezado de la factura en la base de datos
static void InsertarDetalleFactura (DetFactura detallefactura)
Metodo que inserta un detalle de factura en la base de datos
static int ObtenerNumeroDeFacturaActual ()
Obtiene el número siguiente de factura
static List< DetFactura > ObtenerDetallesPorCliente (int idCliente)
Obtiene las copras hechas por el cliente
static ClienteDetalle ObtenerDetallePorCodigo (int idCliente, string codigo)
Método usado para buscar una compra y empezar la realización de un examen
static void MarcarRealizado (string codigo)
Marca un examen como realizado
Detailed Description
Definition at line 12 of file FacturaDB.cs.
Member Function Documentation
Guardar()
static void Capa.DAL.FacturaDB.Guardar (EncFactura factura) static
Método que guarda el encabezado de la factura en la base de datos
Parameters
factura factura de la cuál extraerá los datos
Definition at line 18 of file FacturaDB.cs.
        {
            //EncFactura encFactura = factura;
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarEncFactura";
                comando.Parameters.AddWithValue("@idFactura", factura.IDFactura);
                comando.Parameters.AddWithValue("@idTarjeta", factura.IDTarjeta);
                comando.Parameters.AddWithValue("@idCliente", factura.IDCliente);
                comando.Parameters.AddWithValue("@numeroTarjeta", factura.NumeroTarjeta);
                comando.Parameters.AddWithValue("@total", factura.ObtenerTotal());
                db.ExecuteNonQuery(comando);
                foreach (DetFactura det in factura._ListaFacturaDetalle)
                {
                    InsertarDetalleFactura(det);
                }
            }
        }
References Capa.Entities.EncFactura._ListaFacturaDetalle, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Capa.Entities.EncFactura.IDCliente, Capa.Entities.EncFactura.IDFactura, Capa.Entities.EncFactura.IDTarjeta, Capa.DAL.FacturaDB.InsertarDetalleFactura(), Capa.Entities.EncFactura.NumeroTarjeta, and Capa.Entities.EncFactura.ObtenerTotal().
Referenced by Capa.BLL.FacturaLN.Guardar().
InsertarDetalleFactura()
static void Capa.DAL.FacturaDB.InsertarDetalleFactura (DetFactura detallefactura) static
Metodo que inserta un detalle de factura en la base de datos
Parameters
detallefactura objeto del que obtiene los datos
Definition at line 45 of file FacturaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarDetFactura";
                comando.Parameters.AddWithValue("@idFactura", detallefactura.IDFactura);
                comando.Parameters.AddWithValue("@secuencia", detallefactura.Secuencia);
                comando.Parameters.AddWithValue("@idExamen", detallefactura.IDExamen);
                comando.Parameters.AddWithValue("@monto", detallefactura.Monto);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Capa.Entities.DetFactura.IDExamen, Capa.Entities.DetFactura.IDFactura, Capa.Entities.DetFactura.Monto, and Capa.Entities.DetFactura.Secuencia.
Referenced by Capa.DAL.FacturaDB.Guardar().
MarcarRealizado()
static void Capa.DAL.FacturaDB.MarcarRealizado (string codigo) static
Marca un examen como realizado
Parameters
codigo busca por código
Definition at line 158 of file FacturaDB.cs.
        {
            //EncFactura encFactura = factura;
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_MarcarExamenRealizado";
                comando.Parameters.AddWithValue("@codigo", codigo);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.FacturaLN.MarcarRealizado().
ObtenerDetallePorCodigo()
static ClienteDetalle Capa.DAL.FacturaDB.ObtenerDetallePorCodigo (int idCliente, string codigo) static
Método usado para buscar una compra y empezar la realización de un examen
Parameters
idCliente Cliente a buscar
codigo Codigo de la compra
Returns
retorna un dto para comenzar el examen
Definition at line 125 of file FacturaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarDetallePorCodigo";
                comando.Parameters.AddWithValue("@idCliente", idCliente);
                comando.Parameters.AddWithValue("@codigo", codigo);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    ClienteDetalle c = new ClienteDetalle();
                    c.IdCliente = (int)dr["IDCliente"];
                    c.IDFactura = (int)dr["IDFactura"];
                    c.Secuencia = (int)dr["Secuencia"];
                    c.IDExamen = (int)dr["IDExamen"];
                    c.codigoUnico = dr["CodigoUnico"].ToString();
                    c.Monto = Convert.ToDouble(dr["Monto"]);
                    c.ExamenRealizado = Convert.ToBoolean(dr["ExamenRealizado"]);
                    return c;
                }
            }
            return null;
        }
References Capa.Entities.ClienteDetalle.codigoUnico, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.ClienteDetalle.ExamenRealizado, IDataBase.ExecuteDataSet(), Capa.Entities.ClienteDetalle.IdCliente, Capa.Entities.ClienteDetalle.IDExamen, Capa.Entities.ClienteDetalle.IDFactura, Capa.Entities.ClienteDetalle.Monto, and Capa.Entities.ClienteDetalle.Secuencia.
Referenced by Capa.BLL.FacturaLN.ObtenerDetallePorCodigo().
ObtenerDetallesPorCliente()
static List< DetFactura > Capa.DAL.FacturaDB.ObtenerDetallesPorCliente (int idCliente) static
Obtiene las copras hechas por el cliente
Parameters
idCliente Cliente a consultar
Returns
Obtiene las copras hechas por el cliente
Definition at line 90 of file FacturaDB.cs.
        {
            List<DetFactura> lista = new List<DetFactura>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarDetallesPorCliente";
                comando.Parameters.AddWithValue("@IdCliente", idCliente);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    DetFactura d = new DetFactura();
                    d.IDFactura = (int)dr["IDFactura"];
                    d.Secuencia = (int)dr["Secuencia"];
                    d.IDExamen = (int)dr["IDExamen"];
                    d.codigoUnico = dr["CodigoUnico"].ToString();
                    d.Monto = Convert.ToDouble(dr["Monto"]);
                    d.ExamenRealizado = Convert.ToBoolean(dr["ExamenRealizado"]);
                    lista.Add(d);
                }
            }
            return lista;
        }
References Capa.Entities.DetFactura.codigoUnico, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.DetFactura.ExamenRealizado, IDataBase.ExecuteDataSet(), Capa.Entities.DetFactura.IDExamen, Capa.Entities.DetFactura.IDFactura, Capa.Entities.DetFactura.Monto, and Capa.Entities.DetFactura.Secuencia.
Referenced by Capa.BLL.FacturaLN.ObtenerDetallesPorCliente().
ObtenerNumeroDeFacturaActual()
static int Capa.DAL.FacturaDB.ObtenerNumeroDeFacturaActual () static
Obtiene el número siguiente de factura
Returns
retorna el número de factura siguiente
Definition at line 65 of file FacturaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                int id;
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_UltimoIDFactura";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    id = (int)dr["IDFactura"];
                    return id + 1;
                }
            }
            return 1;
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteDataSet().
Referenced by Capa.BLL.FacturaLN.ObtenerNumeroDeFacturaActual().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/FacturaDB.cs