DBACreator: UI.MantenimientoCertificaciones Class Reference
UI.MantenimientoCertificaciones Class Reference
Public Member Functions
MantenimientoCertificaciones ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MantenimientoCertificaciones_Load (object sender, EventArgs e)
Carga los datos y captura excepciones
void CargarDatos ()
Llena el datagridview con las certificaciones en la base de datos
void habilitar ()
habilita botones y elementos gráficos
void deshabilitar ()
deshabilita y resetea o limpia botones y elementos gráficos
void toolStripBtnSalir_Click (object sender, EventArgs e)
cierra la ventana
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Se resetea la ventana para poder crear una nueva certificación
void toolStripBtnEditar_Click (object sender, EventArgs e)
Coloca los datos del objeto seleccionado para poder ser editados en el panel derecho
void btnCancelar_Click (object sender, EventArgs e)
Llama al método deshabilitar
void toolStripBtnBorrar_Click (object sender, EventArgs e)
Pregunta al usuario si está seguro de querer borrar y mediante la capa BLL borra dcho registro
void btnAceptar_Click (object sender, EventArgs e)
Valida los datos y los guarda/actualiza en la base de datos
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ICertificacionLN logica = new CertificacionLN()
int cont = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspPrincipal
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnEditar
System.Windows.Forms.ToolStripButton toolStripBtnBorrar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dataGridView1
System.Windows.Forms.TextBox txtPrecio
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox txtDescripcion
System.Windows.Forms.Label label3
System.Windows.Forms.Button btnAceptar
System.Windows.Forms.Button btnCancelar
System.Windows.Forms.Label label1
System.Windows.Forms.NumericUpDown numID
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 15 of file MantenimientoCertificaciones.cs.
Constructor & Destructor Documentation
MantenimientoCertificaciones()
UI.MantenimientoCertificaciones.MantenimientoCertificaciones ()
Definition at line 20 of file MantenimientoCertificaciones.cs.
        {
            InitializeComponent();
        }
References UI.MantenimientoCertificaciones.InitializeComponent().
Member Function Documentation
btnAceptar_Click()
void UI.MantenimientoCertificaciones.btnAceptar_Click (object sender, EventArgs e) private
Valida los datos y los guarda/actualiza en la base de datos
Parameters
sender
e
Definition at line 187 of file MantenimientoCertificaciones.cs.
        {
            try
            {
                Certificacion certificacion = new Certificacion();
                if (string.IsNullOrEmpty(txtDescripcion.Text))
                {
                    MessageBox.Show("Descripcion requerida");
                    txtDescripcion.Focus();
                    return;
                }
                if (string.IsNullOrEmpty(txtPrecio.Text))
                {
                    MessageBox.Show("Precio requerido");
                    txtPrecio.Focus();
                    return;
                }
                certificacion.Id = (int)numID.Value;
                certificacion.Descripcion = txtDescripcion.Text;
                certificacion.Precio = Convert.ToDouble(txtPrecio.Text);
                _MyLogControlEventos.Info("Se guardó la certificación " + certificacion.Id);
                logica.Guardar(certificacion);
                if (certificacion != null)
                    CargarDatos();
                deshabilitar();
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de certificaciones: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoCertificaciones._MyLogControlEventos, UI.MantenimientoCertificaciones.CargarDatos(), Capa.Entities.Certificacion.Descripcion, UI.MantenimientoCertificaciones.deshabilitar(), Capa.BLL.ICertificacionLN.Guardar(), Capa.Entities.Certificacion.Id, UI.MantenimientoCertificaciones.logica, UI.MantenimientoCertificaciones.numID, Capa.Entities.Certificacion.Precio, UI.MantenimientoCertificaciones.txtDescripcion, and UI.MantenimientoCertificaciones.txtPrecio.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
btnCancelar_Click()
void UI.MantenimientoCertificaciones.btnCancelar_Click (object sender, EventArgs e) private
Llama al método deshabilitar
Parameters
sender
e
Definition at line 145 of file MantenimientoCertificaciones.cs.
        {
            deshabilitar();
        }
References UI.MantenimientoCertificaciones.deshabilitar().
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
CargarDatos()
void UI.MantenimientoCertificaciones.CargarDatos () private
Llena el datagridview con las certificaciones en la base de datos
Definition at line 47 of file MantenimientoCertificaciones.cs.
        {
            dataGridView1.DataSource = logica.ObtenerTodos();
        }
References UI.MantenimientoCertificaciones.dataGridView1, UI.MantenimientoCertificaciones.logica, and Capa.BLL.ICertificacionLN.ObtenerTodos().
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.MantenimientoCertificaciones_Load(), and UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click().
deshabilitar()
void UI.MantenimientoCertificaciones.deshabilitar () private
deshabilita y resetea o limpia botones y elementos gráficos
Definition at line 67 of file MantenimientoCertificaciones.cs.
        {
            this.txtDescripcion.Enabled = false;
            this.txtPrecio.Enabled = false;
            btnAceptar.Enabled = false;
            btnCancelar.Enabled = false;
            numID.Enabled = false;
            numID.Value = 1;
            txtDescripcion.Text = "";
            txtPrecio.Text = "";
        }
References UI.MantenimientoCertificaciones.btnAceptar, UI.MantenimientoCertificaciones.btnCancelar, UI.MantenimientoCertificaciones.numID, UI.MantenimientoCertificaciones.txtDescripcion, and UI.MantenimientoCertificaciones.txtPrecio.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.btnCancelar_Click(), UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click(), and UI.MantenimientoCertificaciones.toolStripBtnNuevo_Click().
Dispose()
override void UI.MantenimientoCertificaciones.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file MantenimientoCertificaciones.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.MantenimientoCertificaciones.components.
habilitar()
void UI.MantenimientoCertificaciones.habilitar () private
habilita botones y elementos gráficos
Definition at line 55 of file MantenimientoCertificaciones.cs.
        {
            this.txtDescripcion.Enabled = true;
            this.txtPrecio.Enabled = true;
            btnAceptar.Enabled = true;
            btnCancelar.Enabled = true;
            numID.Enabled = true;
        }
References UI.MantenimientoCertificaciones.btnAceptar, UI.MantenimientoCertificaciones.btnCancelar, UI.MantenimientoCertificaciones.numID, UI.MantenimientoCertificaciones.txtDescripcion, and UI.MantenimientoCertificaciones.txtPrecio.
Referenced by UI.MantenimientoCertificaciones.toolStripBtnEditar_Click(), and UI.MantenimientoCertificaciones.toolStripBtnNuevo_Click().
InitializeComponent()
void UI.MantenimientoCertificaciones.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file MantenimientoCertificaciones.Designer.cs.
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MantenimientoCertificaciones));
            this.tspPrincipal = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEditar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnBorrar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.numID = new System.Windows.Forms.NumericUpDown();
            this.label1 = new System.Windows.Forms.Label();
            this.btnAceptar = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.txtPrecio = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.tspPrincipal.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numID)).BeginInit();
            this.SuspendLayout();
            //
            // tspPrincipal
            //
            this.tspPrincipal.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.tspPrincipal.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnEditar,
            this.toolStripBtnBorrar,
            this.toolStripBtnSalir});
            this.tspPrincipal.Location = new System.Drawing.Point(0, 0);
            this.tspPrincipal.Name = "tspPrincipal";
            this.tspPrincipal.Size = new System.Drawing.Size(932, 55);
            this.tspPrincipal.TabIndex = 3;
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnNuevo.Image")));
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(104, 52);
            this.toolStripBtnNuevo.Text = "&Nuevo";
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnEditar
            //
            this.toolStripBtnEditar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnEditar.Image")));
            this.toolStripBtnEditar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEditar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEditar.Name = "toolStripBtnEditar";
            this.toolStripBtnEditar.Size = new System.Drawing.Size(100, 52);
            this.toolStripBtnEditar.Text = "&Editar";
            this.toolStripBtnEditar.Click += new System.EventHandler(this.toolStripBtnEditar_Click);
            //
            // toolStripBtnBorrar
            //
            this.toolStripBtnBorrar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnBorrar.Image")));
            this.toolStripBtnBorrar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBorrar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBorrar.Name = "toolStripBtnBorrar";
            this.toolStripBtnBorrar.Size = new System.Drawing.Size(102, 52);
            this.toolStripBtnBorrar.Text = "&Borrar";
            this.toolStripBtnBorrar.Click += new System.EventHandler(this.toolStripBtnBorrar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "&Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // splitContainer1
            //
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 55);
            this.splitContainer1.Name = "splitContainer1";
            //
            // splitContainer1.Panel1
            //
            this.splitContainer1.Panel1.Controls.Add(this.dataGridView1);
            //
            // splitContainer1.Panel2
            //
            this.splitContainer1.Panel2.Controls.Add(this.numID);
            this.splitContainer1.Panel2.Controls.Add(this.label1);
            this.splitContainer1.Panel2.Controls.Add(this.btnAceptar);
            this.splitContainer1.Panel2.Controls.Add(this.btnCancelar);
            this.splitContainer1.Panel2.Controls.Add(this.txtPrecio);
            this.splitContainer1.Panel2.Controls.Add(this.label4);
            this.splitContainer1.Panel2.Controls.Add(this.txtDescripcion);
            this.splitContainer1.Panel2.Controls.Add(this.label3);
            this.splitContainer1.Size = new System.Drawing.Size(932, 385);
            this.splitContainer1.SplitterDistance = 562;
            this.splitContainer1.TabIndex = 4;
            //
            // dataGridView1
            //
            this.dataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridView1.Location = new System.Drawing.Point(0, 0);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersWidth = 51;
            this.dataGridView1.RowTemplate.Height = 24;
            this.dataGridView1.Size = new System.Drawing.Size(562, 385);
            this.dataGridView1.TabIndex = 0;
            //
            // numID
            //
            this.numID.Enabled = false;
            this.numID.Location = new System.Drawing.Point(117, 19);
            this.numID.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numID.Name = "numID";
            this.numID.Size = new System.Drawing.Size(237, 22);
            this.numID.TabIndex = 29;
            this.numID.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(16, 21);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(21, 17);
            this.label1.TabIndex = 27;
            this.label1.Text = "ID";
            //
            // btnAceptar
            //
            this.btnAceptar.Enabled = false;
            this.btnAceptar.Location = new System.Drawing.Point(185, 310);
            this.btnAceptar.Margin = new System.Windows.Forms.Padding(4);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(155, 53);
            this.btnAceptar.TabIndex = 25;
            this.btnAceptar.Text = "&Aceptar";
            this.btnAceptar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAceptar.UseVisualStyleBackColor = true;
            this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
            //
            // btnCancelar
            //
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancelar.Enabled = false;
            this.btnCancelar.Location = new System.Drawing.Point(15, 310);
            this.btnCancelar.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(152, 53);
            this.btnCancelar.TabIndex = 26;
            this.btnCancelar.Text = "&Cancelar";
            this.btnCancelar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnCancelar.UseVisualStyleBackColor = true;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            //
            // txtPrecio
            //
            this.txtPrecio.Enabled = false;
            this.txtPrecio.Location = new System.Drawing.Point(117, 100);
            this.txtPrecio.Name = "txtPrecio";
            this.txtPrecio.Size = new System.Drawing.Size(237, 22);
            this.txtPrecio.TabIndex = 24;
            //
            // label4
            //
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(16, 103);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(48, 17);
            this.label4.TabIndex = 23;
            this.label4.Text = "Precio";
            //
            // txtDescripcion
            //
            this.txtDescripcion.Enabled = false;
            this.txtDescripcion.Location = new System.Drawing.Point(117, 59);
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.Size = new System.Drawing.Size(237, 22);
            this.txtDescripcion.TabIndex = 22;
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(16, 59);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(82, 17);
            this.label3.TabIndex = 21;
            this.label3.Text = "Descripción";
            //
            // MantenimientoCertificaciones
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(932, 440);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.tspPrincipal);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "MantenimientoCertificaciones";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mantenimiento de Certificaciones";
            this.Load += new System.EventHandler(this.MantenimientoCertificaciones_Load);
            this.tspPrincipal.ResumeLayout(false);
            this.tspPrincipal.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numID)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.MantenimientoCertificaciones.btnAceptar, UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.btnCancelar, UI.MantenimientoCertificaciones.btnCancelar_Click(), UI.MantenimientoCertificaciones.dataGridView1, UI.MantenimientoCertificaciones.label1, UI.MantenimientoCertificaciones.label3, UI.MantenimientoCertificaciones.label4, UI.MantenimientoCertificaciones.MantenimientoCertificaciones_Load(), UI.MantenimientoCertificaciones.numID, UI.MantenimientoCertificaciones.splitContainer1, UI.MantenimientoCertificaciones.toolStripBtnBorrar, UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click(), UI.MantenimientoCertificaciones.toolStripBtnEditar, UI.MantenimientoCertificaciones.toolStripBtnEditar_Click(), UI.MantenimientoCertificaciones.toolStripBtnNuevo, UI.MantenimientoCertificaciones.toolStripBtnNuevo_Click(), UI.MantenimientoCertificaciones.toolStripBtnSalir, UI.MantenimientoCertificaciones.toolStripBtnSalir_Click(), UI.MantenimientoCertificaciones.tspPrincipal, UI.MantenimientoCertificaciones.txtDescripcion, and UI.MantenimientoCertificaciones.txtPrecio.
Referenced by UI.MantenimientoCertificaciones.MantenimientoCertificaciones().
MantenimientoCertificaciones_Load()
void UI.MantenimientoCertificaciones.MantenimientoCertificaciones_Load (object sender, EventArgs e) private
Carga los datos y captura excepciones
Parameters
sender
e
Definition at line 30 of file MantenimientoCertificaciones.cs.
        {
            try
            {
                CargarDatos();
                _MyLogControlEventos.Info("Certificaciones cargadas");
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Certificaciones: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoCertificaciones._MyLogControlEventos, and UI.MantenimientoCertificaciones.CargarDatos().
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnBorrar_Click()
void UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click (object sender, EventArgs e) private
Pregunta al usuario si está seguro de querer borrar y mediante la capa BLL borra dcho registro
Parameters
sender
e
Definition at line 155 of file MantenimientoCertificaciones.cs.
        {
            try
            {
                if (this.dataGridView1.SelectedRows.Count > 0)
                {
                    Certificacion certificacion = this.dataGridView1.SelectedRows[0].DataBoundItem as Certificacion;
                    if (MessageBox.Show($"¿Seguro que desea borrar el registro {certificacion.Id} {certificacion.Descripcion}? Los examenes de dicha certificación tambíen se borrarán", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        _MyLogControlEventos.Info("Se borró la certificación " + certificacion.Id);
                        logica.Borrar(certificacion.Id);
                        this.CargarDatos();
                    }
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                deshabilitar();
                CargarDatos();
            } catch(Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de certificaciones: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoCertificaciones._MyLogControlEventos, Capa.BLL.ICertificacionLN.Borrar(), UI.MantenimientoCertificaciones.CargarDatos(), UI.MantenimientoCertificaciones.dataGridView1, UI.MantenimientoCertificaciones.deshabilitar(), Capa.Entities.Certificacion.Id, and UI.MantenimientoCertificaciones.logica.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnEditar_Click()
void UI.MantenimientoCertificaciones.toolStripBtnEditar_Click (object sender, EventArgs e) private
Coloca los datos del objeto seleccionado para poder ser editados en el panel derecho
Parameters
sender
e
Definition at line 107 of file MantenimientoCertificaciones.cs.
        {
            cont++;
            if (cont == 1)
            {
                _MyLogControlEventos.Warn("si cambia el ID podría generar problemas");
                MessageBox.Show("Advertencia: si cambia el ID podría generar problemas, cambielo solo en caso de que sepa lo que está haciendo", "Advertencia", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            Certificacion certificacion = null;
            try
            {
                if (this.dataGridView1.SelectedRows.Count > 0)
                {
                    habilitar();
                    certificacion = this.dataGridView1.SelectedRows[0].DataBoundItem as Certificacion;
                    txtDescripcion.Text = certificacion.Descripcion;
                    txtPrecio.Text = certificacion.Precio.ToString();
                    numID.Value = certificacion.Id;
                    _MyLogControlEventos.Info("Edición de la certificación "+ certificacion.Id);
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de certificaciones: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoCertificaciones._MyLogControlEventos, UI.MantenimientoCertificaciones.cont, UI.MantenimientoCertificaciones.dataGridView1, Capa.Entities.Certificacion.Descripcion, UI.MantenimientoCertificaciones.habilitar(), Capa.Entities.Certificacion.Id, UI.MantenimientoCertificaciones.numID, Capa.Entities.Certificacion.Precio, UI.MantenimientoCertificaciones.txtDescripcion, and UI.MantenimientoCertificaciones.txtPrecio.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnNuevo_Click()
void UI.MantenimientoCertificaciones.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Se resetea la ventana para poder crear una nueva certificación
Parameters
sender
e
Definition at line 94 of file MantenimientoCertificaciones.cs.
        {
            deshabilitar();
            habilitar();
            _MyLogControlEventos.Info("Nueva certificación");
            //numID.Value = dataGridView1.RowCount + 1;
        }
References UI.MantenimientoCertificaciones._MyLogControlEventos, UI.MantenimientoCertificaciones.deshabilitar(), and UI.MantenimientoCertificaciones.habilitar().
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnSalir_Click()
void UI.MantenimientoCertificaciones.toolStripBtnSalir_Click (object sender, EventArgs e) private
cierra la ventana
Parameters
sender
e
Definition at line 84 of file MantenimientoCertificaciones.cs.
        {
            this.Close();
        }
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.MantenimientoCertificaciones._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 19 of file MantenimientoCertificaciones.cs.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.MantenimientoCertificaciones_Load(), UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click(), UI.MantenimientoCertificaciones.toolStripBtnEditar_Click(), and UI.MantenimientoCertificaciones.toolStripBtnNuevo_Click().
btnAceptar
System.Windows.Forms.Button UI.MantenimientoCertificaciones.btnAceptar private
Definition at line 272 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.deshabilitar(), UI.MantenimientoCertificaciones.habilitar(), and UI.MantenimientoCertificaciones.InitializeComponent().
btnCancelar
System.Windows.Forms.Button UI.MantenimientoCertificaciones.btnCancelar private
Definition at line 273 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.deshabilitar(), UI.MantenimientoCertificaciones.habilitar(), and UI.MantenimientoCertificaciones.InitializeComponent().
components
System.ComponentModel.IContainer UI.MantenimientoCertificaciones.components = null private
Required designer variable.
Definition at line 9 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.Dispose().
cont
int UI.MantenimientoCertificaciones.cont = 0 private
Definition at line 18 of file MantenimientoCertificaciones.cs.
Referenced by UI.MantenimientoCertificaciones.toolStripBtnEditar_Click().
dataGridView1
System.Windows.Forms.DataGridView UI.MantenimientoCertificaciones.dataGridView1 private
Definition at line 267 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.CargarDatos(), UI.MantenimientoCertificaciones.InitializeComponent(), UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click(), and UI.MantenimientoCertificaciones.toolStripBtnEditar_Click().
label1
System.Windows.Forms.Label UI.MantenimientoCertificaciones.label1 private
Definition at line 274 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
label3
System.Windows.Forms.Label UI.MantenimientoCertificaciones.label3 private
Definition at line 271 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
label4
System.Windows.Forms.Label UI.MantenimientoCertificaciones.label4 private
Definition at line 269 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
logica
ICertificacionLN UI.MantenimientoCertificaciones.logica = new CertificacionLN() private
Definition at line 17 of file MantenimientoCertificaciones.cs.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.CargarDatos(), and UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click().
numID
System.Windows.Forms.NumericUpDown UI.MantenimientoCertificaciones.numID private
Definition at line 275 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.deshabilitar(), UI.MantenimientoCertificaciones.habilitar(), UI.MantenimientoCertificaciones.InitializeComponent(), and UI.MantenimientoCertificaciones.toolStripBtnEditar_Click().
splitContainer1
System.Windows.Forms.SplitContainer UI.MantenimientoCertificaciones.splitContainer1 private
Definition at line 266 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnBorrar
System.Windows.Forms.ToolStripButton UI.MantenimientoCertificaciones.toolStripBtnBorrar private
Definition at line 264 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnEditar
System.Windows.Forms.ToolStripButton UI.MantenimientoCertificaciones.toolStripBtnEditar private
Definition at line 263 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton UI.MantenimientoCertificaciones.toolStripBtnNuevo private
Definition at line 262 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.MantenimientoCertificaciones.toolStripBtnSalir private
Definition at line 265 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
tspPrincipal
System.Windows.Forms.ToolStrip UI.MantenimientoCertificaciones.tspPrincipal private
Definition at line 261 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.InitializeComponent().
txtDescripcion
System.Windows.Forms.TextBox UI.MantenimientoCertificaciones.txtDescripcion private
Definition at line 270 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.deshabilitar(), UI.MantenimientoCertificaciones.habilitar(), UI.MantenimientoCertificaciones.InitializeComponent(), and UI.MantenimientoCertificaciones.toolStripBtnEditar_Click().
txtPrecio
System.Windows.Forms.TextBox UI.MantenimientoCertificaciones.txtPrecio private
Definition at line 268 of file MantenimientoCertificaciones.Designer.cs.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click(), UI.MantenimientoCertificaciones.deshabilitar(), UI.MantenimientoCertificaciones.habilitar(), UI.MantenimientoCertificaciones.InitializeComponent(), and UI.MantenimientoCertificaciones.toolStripBtnEditar_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Mantenimientos/MantenimientoCertificaciones.cs
118710756/DbaCreator/UI/Mantenimientos/MantenimientoCertificaciones.Designer.cs