DBACreator: UI.Reportes.FrmReporteClientes Class Reference
UI.Reportes.FrmReporteClientes Class Reference
Public Member Functions
FrmReporteClientes ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void FrmReporteClientes_Load (object sender, EventArgs e)
Carga todos los clientes
void toolStripBtnBuscar_Click (object sender, EventArgs e)
Usa un stored procedure para buscar según lo escrito en el textbox y carga el reporte
void toolStripBtnSalir_Click (object sender, EventArgs e)
cierra la ventana
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip toolStrip1
System.Windows.Forms.ToolStripTextBox toolStripTxtFiltro
System.Windows.Forms.ToolStripButton toolStripBtnBuscar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
System.Windows.Forms.BindingSource PA_ReporteClientesBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_ReporteClientesTableAdapter PA_ReporteClientesTableAdapter
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 13 of file FrmReporteClientes.cs.
Constructor & Destructor Documentation
FrmReporteClientes()
UI.Reportes.FrmReporteClientes.FrmReporteClientes ()
Definition at line 16 of file FrmReporteClientes.cs.
        {
            InitializeComponent();
        }
References UI.Reportes.FrmReporteClientes.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.FrmReporteClientes.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file FrmReporteClientes.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.FrmReporteClientes.components.
FrmReporteClientes_Load()
void UI.Reportes.FrmReporteClientes.FrmReporteClientes_Load (object sender, EventArgs e) private
Carga todos los clientes
Parameters
sender
e
Definition at line 26 of file FrmReporteClientes.cs.
        {
            toolStripBtnBuscar.PerformClick();
        }
References UI.Reportes.FrmReporteClientes.toolStripBtnBuscar.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
InitializeComponent()
void UI.Reportes.FrmReporteClientes.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file FrmReporteClientes.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmReporteClientes));
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.PA_ReporteClientesBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnBuscar = new System.Windows.Forms.ToolStripButton();
            this.toolStripTxtFiltro = new System.Windows.Forms.ToolStripTextBox();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_ReporteClientesTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_ReporteClientesTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteClientesBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            //
            // PA_ReporteClientesBindingSource
            //
            this.PA_ReporteClientesBindingSource.DataMember = "PA_ReporteClientes";
            this.PA_ReporteClientesBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // toolStrip1
            //
            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnBuscar,
            this.toolStripTxtFiltro,
            this.toolStripBtnSalir});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(994, 55);
            this.toolStrip1.TabIndex = 2;
            this.toolStrip1.Text = "toolStrip1";
            //
            // toolStripBtnBuscar
            //
            this.toolStripBtnBuscar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnBuscar.Image")));
            this.toolStripBtnBuscar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBuscar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBuscar.Name = "toolStripBtnBuscar";
            this.toolStripBtnBuscar.Size = new System.Drawing.Size(261, 52);
            this.toolStripBtnBuscar.Text = "Buscar por Nombre o Apellido";
            this.toolStripBtnBuscar.Click += new System.EventHandler(this.toolStripBtnBuscar_Click);
            //
            // toolStripTxtFiltro
            //
            this.toolStripTxtFiltro.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.toolStripTxtFiltro.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.toolStripTxtFiltro.Name = "toolStripTxtFiltro";
            this.toolStripTxtFiltro.Size = new System.Drawing.Size(133, 55);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.BackColor = System.Drawing.SystemColors.Control;
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // reportViewer1
            //
            this.reportViewer1.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetClientes";
            reportDataSource1.Value = this.PA_ReporteClientesBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteClientes.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 55);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(994, 512);
            this.reportViewer1.TabIndex = 3;
            //
            // PA_ReporteClientesTableAdapter
            //
            this.PA_ReporteClientesTableAdapter.ClearBeforeFill = true;
            //
            // FrmReporteClientes
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(994, 567);
            this.Controls.Add(this.reportViewer1);
            this.Controls.Add(this.toolStrip1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmReporteClientes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Reporte de Clientes";
            this.Load += new System.EventHandler(this.FrmReporteClientes_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteClientesBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Reportes.FrmReporteClientes.components, UI.Reportes.FrmReporteClientes.DataSetReportes, UI.Reportes.FrmReporteClientes.FrmReporteClientes_Load(), UI.Reportes.FrmReporteClientes.PA_ReporteClientesBindingSource, UI.Reportes.FrmReporteClientes.PA_ReporteClientesTableAdapter, UI.Reportes.FrmReporteClientes.reportViewer1, UI.Reportes.DataSetReportes.SchemaSerializationMode, UI.Reportes.FrmReporteClientes.toolStrip1, UI.Reportes.FrmReporteClientes.toolStripBtnBuscar, UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click(), UI.Reportes.FrmReporteClientes.toolStripBtnSalir, UI.Reportes.FrmReporteClientes.toolStripBtnSalir_Click(), and UI.Reportes.FrmReporteClientes.toolStripTxtFiltro.
Referenced by UI.Reportes.FrmReporteClientes.FrmReporteClientes().
toolStripBtnBuscar_Click()
void UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click (object sender, EventArgs e) private
Usa un stored procedure para buscar según lo escrito en el textbox y carga el reporte
Parameters
sender
e
Definition at line 36 of file FrmReporteClientes.cs.
        {
            string filtro = "";
            try
            {
                filtro = "%" + this.toolStripTxtFiltro.Text + "%";
                this.PA_ReporteClientesTableAdapter.Fill(this.DataSetReportes.PA_ReporteClientes, filtro);
                this.reportViewer1.RefreshReport();
                _MyLogControlEventos.Info("Datos encontrados");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de clientes: " + er.Message);
            }
        }
References UI.Reportes.FrmReporteClientes._MyLogControlEventos, UI.Reportes.DataSetReportes.PA_ReporteClientes, UI.Reportes.FrmReporteClientes.PA_ReporteClientesTableAdapter, UI.Reportes.FrmReporteClientes.reportViewer1, and UI.Reportes.FrmReporteClientes.toolStripTxtFiltro.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
toolStripBtnSalir_Click()
void UI.Reportes.FrmReporteClientes.toolStripBtnSalir_Click (object sender, EventArgs e) private
cierra la ventana
Parameters
sender
e
Definition at line 61 of file FrmReporteClientes.cs.
        {
            this.Close();
        }
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.FrmReporteClientes._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 15 of file FrmReporteClientes.cs.
Referenced by UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click().
components
System.ComponentModel.IContainer UI.Reportes.FrmReporteClientes.components = null private
Required designer variable.
Definition at line 9 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.Dispose(), and UI.Reportes.FrmReporteClientes.InitializeComponent().
DataSetReportes
DataSetReportes UI.Reportes.FrmReporteClientes.DataSetReportes private
Definition at line 145 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
PA_ReporteClientesBindingSource
System.Windows.Forms.BindingSource UI.Reportes.FrmReporteClientes.PA_ReporteClientesBindingSource private
Definition at line 144 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
PA_ReporteClientesTableAdapter
DataSetReportesTableAdapters.PA_ReporteClientesTableAdapter UI.Reportes.FrmReporteClientes.PA_ReporteClientesTableAdapter private
Definition at line 146 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent(), and UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.FrmReporteClientes.reportViewer1 private
Definition at line 143 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent(), and UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click().
toolStrip1
System.Windows.Forms.ToolStrip UI.Reportes.FrmReporteClientes.toolStrip1 private
Definition at line 139 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
toolStripBtnBuscar
System.Windows.Forms.ToolStripButton UI.Reportes.FrmReporteClientes.toolStripBtnBuscar private
Definition at line 141 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.FrmReporteClientes_Load(), and UI.Reportes.FrmReporteClientes.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.Reportes.FrmReporteClientes.toolStripBtnSalir private
Definition at line 142 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent().
toolStripTxtFiltro
System.Windows.Forms.ToolStripTextBox UI.Reportes.FrmReporteClientes.toolStripTxtFiltro private
Definition at line 140 of file FrmReporteClientes.Designer.cs.
Referenced by UI.Reportes.FrmReporteClientes.InitializeComponent(), and UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/FrmReporteClientes.cs
118710756/DbaCreator/UI/Reportes/FrmReporteClientes.Designer.cs