DBACreator: UI.Reportes.FrmClientesCertificados Class Reference
UI.Reportes.FrmClientesCertificados Class Reference
Public Member Functions
FrmClientesCertificados ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void FrmClientesCertificados_Load (object sender, EventArgs e)
Llena el combobox com las certificaciones existentes
void toolStripBtnBuscar_Click (object sender, EventArgs e)
Carga el reporte según la certificación seleccionada en el combobox
void toolStripBtnSalir_Click (object sender, EventArgs e)
Cierra la ventana
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip toolStrip1
System.Windows.Forms.ToolStripButton toolStripBtnBuscar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.ToolStripComboBox toolStripComboBoxCertis
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
System.Windows.Forms.BindingSource PA_ReporteClientesCertificadosBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_ReporteClientesCertificadosTableAdapter PA_ReporteClientesCertificadosTableAdapter
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 15 of file FrmClientesCertificados.cs.
Constructor & Destructor Documentation
FrmClientesCertificados()
UI.Reportes.FrmClientesCertificados.FrmClientesCertificados ()
Definition at line 18 of file FrmClientesCertificados.cs.
        {
            InitializeComponent();
        }
References UI.Reportes.FrmClientesCertificados.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.FrmClientesCertificados.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file FrmClientesCertificados.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.FrmClientesCertificados.components.
FrmClientesCertificados_Load()
void UI.Reportes.FrmClientesCertificados.FrmClientesCertificados_Load (object sender, EventArgs e) private
Llena el combobox com las certificaciones existentes
Parameters
sender
e
Definition at line 27 of file FrmClientesCertificados.cs.
        {
            try
            {
                var logica = new CertificacionLN();
                this.toolStripComboBoxCertis.ComboBox.DataSource = logica.ObtenerTodos();
                this.toolStripComboBoxCertis.ComboBox.DisplayMember = "Descripcion";
            } catch(Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de clientes certificados: " + er.Message);
            }
        }
References UI.Reportes.FrmClientesCertificados._MyLogControlEventos, and UI.Reportes.FrmClientesCertificados.toolStripComboBoxCertis.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
InitializeComponent()
void UI.Reportes.FrmClientesCertificados.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file FrmClientesCertificados.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmClientesCertificados));
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.PA_ReporteClientesCertificadosBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnBuscar = new System.Windows.Forms.ToolStripButton();
            this.toolStripComboBoxCertis = new System.Windows.Forms.ToolStripComboBox();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_ReporteClientesCertificadosTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_ReporteClientesCertificadosTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteClientesCertificadosBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            //
            // PA_ReporteClientesCertificadosBindingSource
            //
            this.PA_ReporteClientesCertificadosBindingSource.DataMember = "PA_ReporteClientesCertificados";
            this.PA_ReporteClientesCertificadosBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // toolStrip1
            //
            this.toolStrip1.BackColor = System.Drawing.SystemColors.Control;
            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnBuscar,
            this.toolStripComboBoxCertis,
            this.toolStripBtnSalir});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(963, 55);
            this.toolStrip1.Stretch = true;
            this.toolStrip1.TabIndex = 5;
            this.toolStrip1.Text = "toolStrip1";
            //
            // toolStripBtnBuscar
            //
            this.toolStripBtnBuscar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnBuscar.Image")));
            this.toolStripBtnBuscar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBuscar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBuscar.Name = "toolStripBtnBuscar";
            this.toolStripBtnBuscar.Size = new System.Drawing.Size(215, 52);
            this.toolStripBtnBuscar.Text = "Buscar por Certificación";
            this.toolStripBtnBuscar.Click += new System.EventHandler(this.toolStripBtnBuscar_Click);
            //
            // toolStripComboBoxCertis
            //
            this.toolStripComboBoxCertis.AutoSize = false;
            this.toolStripComboBoxCertis.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.toolStripComboBoxCertis.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripComboBoxCertis.Name = "toolStripComboBoxCertis";
            this.toolStripComboBoxCertis.Size = new System.Drawing.Size(400, 31);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // reportViewer1
            //
            this.reportViewer1.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetCxC";
            reportDataSource1.Value = this.PA_ReporteClientesCertificadosBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteClientesCertificados.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 55);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(963, 500);
            this.reportViewer1.TabIndex = 6;
            //
            // PA_ReporteClientesCertificadosTableAdapter
            //
            this.PA_ReporteClientesCertificadosTableAdapter.ClearBeforeFill = true;
            //
            // FrmClientesCertificados
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(963, 555);
            this.Controls.Add(this.reportViewer1);
            this.Controls.Add(this.toolStrip1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmClientesCertificados";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Clientes Certificados";
            this.Load += new System.EventHandler(this.FrmClientesCertificados_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteClientesCertificadosBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Reportes.FrmClientesCertificados.components, UI.Reportes.FrmClientesCertificados.DataSetReportes, UI.Reportes.FrmClientesCertificados.FrmClientesCertificados_Load(), UI.Reportes.FrmClientesCertificados.PA_ReporteClientesCertificadosBindingSource, UI.Reportes.FrmClientesCertificados.PA_ReporteClientesCertificadosTableAdapter, UI.Reportes.FrmClientesCertificados.reportViewer1, UI.Reportes.DataSetReportes.SchemaSerializationMode, UI.Reportes.FrmClientesCertificados.toolStrip1, UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar, UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click(), UI.Reportes.FrmClientesCertificados.toolStripBtnSalir, UI.Reportes.FrmClientesCertificados.toolStripBtnSalir_Click(), and UI.Reportes.FrmClientesCertificados.toolStripComboBoxCertis.
Referenced by UI.Reportes.FrmClientesCertificados.FrmClientesCertificados().
toolStripBtnBuscar_Click()
void UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click (object sender, EventArgs e) private
Carga el reporte según la certificación seleccionada en el combobox
Parameters
sender
e
Definition at line 48 of file FrmClientesCertificados.cs.
        {
            int id;
            try
            {
                id = (toolStripComboBoxCertis.ComboBox.SelectedItem as Certificacion).Id;
                this.PA_ReporteClientesCertificadosTableAdapter.Fill(this.DataSetReportes.PA_ReporteClientesCertificados, id);
                this.reportViewer1.RefreshReport();
                _MyLogControlEventos.Info("Datos encontrados");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de clientes certificados: " + er.Message);
            }
        }
References UI.Reportes.FrmClientesCertificados._MyLogControlEventos, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificados, UI.Reportes.FrmClientesCertificados.PA_ReporteClientesCertificadosTableAdapter, UI.Reportes.FrmClientesCertificados.reportViewer1, and UI.Reportes.FrmClientesCertificados.toolStripComboBoxCertis.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
toolStripBtnSalir_Click()
void UI.Reportes.FrmClientesCertificados.toolStripBtnSalir_Click (object sender, EventArgs e) private
Cierra la ventana
Parameters
sender
e
Definition at line 71 of file FrmClientesCertificados.cs.
        {
            this.Close();
        }
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.FrmClientesCertificados._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 17 of file FrmClientesCertificados.cs.
Referenced by UI.Reportes.FrmClientesCertificados.FrmClientesCertificados_Load(), and UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click().
components
System.ComponentModel.IContainer UI.Reportes.FrmClientesCertificados.components = null private
Required designer variable.
Definition at line 9 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.Dispose(), and UI.Reportes.FrmClientesCertificados.InitializeComponent().
DataSetReportes
DataSetReportes UI.Reportes.FrmClientesCertificados.DataSetReportes private
Definition at line 147 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
PA_ReporteClientesCertificadosBindingSource
System.Windows.Forms.BindingSource UI.Reportes.FrmClientesCertificados.PA_ReporteClientesCertificadosBindingSource private
Definition at line 146 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
PA_ReporteClientesCertificadosTableAdapter
DataSetReportesTableAdapters.PA_ReporteClientesCertificadosTableAdapter UI.Reportes.FrmClientesCertificados.PA_ReporteClientesCertificadosTableAdapter private
Definition at line 148 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent(), and UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.FrmClientesCertificados.reportViewer1 private
Definition at line 145 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent(), and UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click().
toolStrip1
System.Windows.Forms.ToolStrip UI.Reportes.FrmClientesCertificados.toolStrip1 private
Definition at line 141 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
toolStripBtnBuscar
System.Windows.Forms.ToolStripButton UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar private
Definition at line 142 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.Reportes.FrmClientesCertificados.toolStripBtnSalir private
Definition at line 143 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.InitializeComponent().
toolStripComboBoxCertis
System.Windows.Forms.ToolStripComboBox UI.Reportes.FrmClientesCertificados.toolStripComboBoxCertis private
Definition at line 144 of file FrmClientesCertificados.Designer.cs.
Referenced by UI.Reportes.FrmClientesCertificados.FrmClientesCertificados_Load(), UI.Reportes.FrmClientesCertificados.InitializeComponent(), and UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/FrmClientesCertificados.cs
118710756/DbaCreator/UI/Reportes/FrmClientesCertificados.Designer.cs