DBACreator: UI.MantenimientoExamenes Class Reference
UI.MantenimientoExamenes Class Reference
Public Member Functions
MantenimientoExamenes ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MantenimientoExamenes_Load (object sender, EventArgs e)
Llena los objetos gráficos y los ajusta para su debido uso
void toolStripBtnSalir_Click (object sender, EventArgs e)
cierra la ventana
void CargarDatos ()
llena el datagrid on los objetos de la bd
void toolStripBtnNuevo_Click (object sender, EventArgs e)
Reinicia la interfaz para crear un nuevo examen
void habilitar ()
Habilita objetos gráficos
void deshabilitar ()
deshabilita y limpia objetos gráficos
void toolStripBtnBorrar_Click (object sender, EventArgs e)
pide confirmación y borra el registro seleccionado de la bd
void toolStripBtnEditar_Click (object sender, EventArgs e)
Coloca los datos del objeto seleccionado en el panel derecho para su edición
void btnAceptar_Click (object sender, EventArgs e)
Guarda/actualiza los datos en la bd
void btnCancelar_Click (object sender, EventArgs e)
Llama a deshabilitar
void btnPreguntas_Click (object sender, EventArgs e)
Abre una ventana para editar las preguntas del examen seleccionado
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ICertificacionLN logicaCertificaciones = new CertificacionLN()
IExamenLN logicaExamenes = new ExamenLN()
int cont = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspPrincipal
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnEditar
System.Windows.Forms.ToolStripButton toolStripBtnBorrar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dgvDatos
System.Windows.Forms.NumericUpDown numID
System.Windows.Forms.Label label1
System.Windows.Forms.Label label4
System.Windows.Forms.Label label3
System.Windows.Forms.Button btnPreguntas
System.Windows.Forms.ComboBox cmbCerti
System.Windows.Forms.NumericUpDown numMInutos
System.Windows.Forms.NumericUpDown numPreguntas
System.Windows.Forms.Label label2
System.Windows.Forms.Button btnAceptar
System.Windows.Forms.Button btnCancelar
System.Windows.Forms.TextBox txtTitulo
System.Windows.Forms.Label label5
System.Windows.Forms.NumericUpDown numNota
System.Windows.Forms.Label label6
System.Windows.Forms.DataGridViewTextBoxColumn cID
System.Windows.Forms.DataGridViewTextBoxColumn cCertificacion
System.Windows.Forms.DataGridViewTextBoxColumn cTitulo
System.Windows.Forms.DataGridViewTextBoxColumn cMinutos
System.Windows.Forms.DataGridViewTextBoxColumn cCantp
System.Windows.Forms.DataGridViewTextBoxColumn cNota
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 15 of file MantenimientoExamenes.cs.
Constructor & Destructor Documentation
MantenimientoExamenes()
UI.MantenimientoExamenes.MantenimientoExamenes ()
Definition at line 21 of file MantenimientoExamenes.cs.
        {
            InitializeComponent();
        }
References UI.MantenimientoExamenes.InitializeComponent().
Member Function Documentation
btnAceptar_Click()
void UI.MantenimientoExamenes.btnAceptar_Click (object sender, EventArgs e) private
Guarda/actualiza los datos en la bd
Parameters
sender
e
Definition at line 191 of file MantenimientoExamenes.cs.
        {
            try
            {
                Examen examen = new Examen();
                if (string.IsNullOrEmpty(txtTitulo.Text))
                {
                    MessageBox.Show("Titulo requerido");
                    txtTitulo.Focus();
                    return;
                }
                examen.ID = (int)numID.Value;
                examen.CertificacionA = (Certificacion)cmbCerti.SelectedItem;
                examen.Titulo = txtTitulo.Text;
                examen.Minutos = (int)numMInutos.Value;
                examen.CantPreguntas = (int)numPreguntas.Value;
                examen.NotaMinima = (double)numNota.Value;
                logicaExamenes.Guardar(examen);
                _MyLogControlEventos.Info($"Se guardó el examen: {examen.ID}");
                if (examen != null)
                    CargarDatos();
                deshabilitar();
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, Capa.Entities.Examen.CantPreguntas, UI.MantenimientoExamenes.CargarDatos(), Capa.Entities.Examen.CertificacionA, UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.deshabilitar(), Capa.BLL.IExamenLN.Guardar(), Capa.Entities.Examen.ID, UI.MantenimientoExamenes.logicaExamenes, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, UI.MantenimientoExamenes.numID, UI.MantenimientoExamenes.numMInutos, UI.MantenimientoExamenes.numNota, UI.MantenimientoExamenes.numPreguntas, Capa.Entities.Examen.Titulo, and UI.MantenimientoExamenes.txtTitulo.
btnCancelar_Click()
void UI.MantenimientoExamenes.btnCancelar_Click (object sender, EventArgs e) private
Llama a deshabilitar
Parameters
sender
e
Definition at line 228 of file MantenimientoExamenes.cs.
        {
            try
            {
                deshabilitar();
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, and UI.MantenimientoExamenes.deshabilitar().
btnPreguntas_Click()
void UI.MantenimientoExamenes.btnPreguntas_Click (object sender, EventArgs e) private
Abre una ventana para editar las preguntas del examen seleccionado
Parameters
sender
e
Definition at line 247 of file MantenimientoExamenes.cs.
        {
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    var frm = new MantenimientoPreguntas();
                    Examen examen = this.dgvDatos.SelectedRows[0].DataBoundItem as Examen;
                    frm.AsignarExamen(examen);
                    frm.Show();
                    frm.Closed += (s, args) => this.CargarDatos();
                    _MyLogControlEventos.Info($"Se editan las preguntas del examen: {examen.ID}");
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, UI.MantenimientoExamenes.CargarDatos(), and UI.MantenimientoExamenes.dgvDatos.
CargarDatos()
void UI.MantenimientoExamenes.CargarDatos () private
llena el datagrid on los objetos de la bd
Definition at line 61 of file MantenimientoExamenes.cs.
        {
            this.dgvDatos.DataSource = logicaExamenes.ObtenerTodos();
        }
References UI.MantenimientoExamenes.dgvDatos, and Capa.BLL.IExamenLN.ObtenerTodos().
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.btnPreguntas_Click(), UI.MantenimientoExamenes.MantenimientoExamenes_Load(), and UI.MantenimientoExamenes.toolStripBtnBorrar_Click().
deshabilitar()
void UI.MantenimientoExamenes.deshabilitar () private
deshabilita y limpia objetos gráficos
Definition at line 96 of file MantenimientoExamenes.cs.
        {
            this.numID.Enabled = false;
            this.cmbCerti.Enabled = false;
            numMInutos.Enabled = false;
            numPreguntas.Enabled = false;
            btnAceptar.Enabled = false;
            btnCancelar.Enabled = false;
            btnPreguntas.Enabled = false;
            txtTitulo.Enabled = false;
            numNota.Enabled = false;
            numID.Value = 1;
            numMInutos.Value = 1;
            numPreguntas.Value = 0;
            cmbCerti.SelectedIndex = 0;
            txtTitulo.Text = "";
        }
References UI.MantenimientoExamenes.btnAceptar, UI.MantenimientoExamenes.btnCancelar, UI.MantenimientoExamenes.btnPreguntas, UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.numID, UI.MantenimientoExamenes.numMInutos, UI.MantenimientoExamenes.numNota, UI.MantenimientoExamenes.numPreguntas, and UI.MantenimientoExamenes.txtTitulo.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.btnCancelar_Click(), UI.MantenimientoExamenes.toolStripBtnBorrar_Click(), and UI.MantenimientoExamenes.toolStripBtnNuevo_Click().
Dispose()
override void UI.MantenimientoExamenes.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file MantenimientoExamenes.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.MantenimientoExamenes.components.
habilitar()
void UI.MantenimientoExamenes.habilitar () private
Habilita objetos gráficos
Definition at line 81 of file MantenimientoExamenes.cs.
        {
            this.numID.Enabled = true;
            this.cmbCerti.Enabled = true;
            numMInutos.Enabled = true;
            numNota.Enabled = true;
            btnAceptar.Enabled = true;
            btnCancelar.Enabled = true;
            //btnPreguntas.Enabled = true;
            txtTitulo.Enabled = true;
        }
References UI.MantenimientoExamenes.btnAceptar, UI.MantenimientoExamenes.btnCancelar, UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.numID, UI.MantenimientoExamenes.numMInutos, UI.MantenimientoExamenes.numNota, and UI.MantenimientoExamenes.txtTitulo.
Referenced by UI.MantenimientoExamenes.toolStripBtnEditar_Click(), and UI.MantenimientoExamenes.toolStripBtnNuevo_Click().
InitializeComponent()
void UI.MantenimientoExamenes.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file MantenimientoExamenes.Designer.cs.
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MantenimientoExamenes));
            this.tspPrincipal = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnEditar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnBorrar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.dgvDatos = new System.Windows.Forms.DataGridView();
            this.cID = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.cCertificacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.cTitulo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.cMinutos = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.cCantp = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.cNota = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.numNota = new System.Windows.Forms.NumericUpDown();
            this.label6 = new System.Windows.Forms.Label();
            this.txtTitulo = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.btnAceptar = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.btnPreguntas = new System.Windows.Forms.Button();
            this.cmbCerti = new System.Windows.Forms.ComboBox();
            this.numMInutos = new System.Windows.Forms.NumericUpDown();
            this.numPreguntas = new System.Windows.Forms.NumericUpDown();
            this.label2 = new System.Windows.Forms.Label();
            this.numID = new System.Windows.Forms.NumericUpDown();
            this.label1 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.tspPrincipal.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNota)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numMInutos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numPreguntas)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numID)).BeginInit();
            this.SuspendLayout();
            //
            // tspPrincipal
            //
            this.tspPrincipal.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.tspPrincipal.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnNuevo,
            this.toolStripBtnEditar,
            this.toolStripBtnBorrar,
            this.toolStripBtnSalir});
            this.tspPrincipal.Location = new System.Drawing.Point(0, 0);
            this.tspPrincipal.Name = "tspPrincipal";
            this.tspPrincipal.Size = new System.Drawing.Size(1304, 55);
            this.tspPrincipal.TabIndex = 4;
            //
            // toolStripBtnNuevo
            //
            this.toolStripBtnNuevo.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnNuevo.Image")));
            this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
            this.toolStripBtnNuevo.Size = new System.Drawing.Size(104, 52);
            this.toolStripBtnNuevo.Text = "&Nuevo";
            this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
            //
            // toolStripBtnEditar
            //
            this.toolStripBtnEditar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnEditar.Image")));
            this.toolStripBtnEditar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnEditar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnEditar.Name = "toolStripBtnEditar";
            this.toolStripBtnEditar.Size = new System.Drawing.Size(100, 52);
            this.toolStripBtnEditar.Text = "&Editar";
            this.toolStripBtnEditar.Click += new System.EventHandler(this.toolStripBtnEditar_Click);
            //
            // toolStripBtnBorrar
            //
            this.toolStripBtnBorrar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnBorrar.Image")));
            this.toolStripBtnBorrar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBorrar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBorrar.Name = "toolStripBtnBorrar";
            this.toolStripBtnBorrar.Size = new System.Drawing.Size(102, 52);
            this.toolStripBtnBorrar.Text = "&Borrar";
            this.toolStripBtnBorrar.Click += new System.EventHandler(this.toolStripBtnBorrar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "&Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // splitContainer1
            //
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 55);
            this.splitContainer1.Name = "splitContainer1";
            //
            // splitContainer1.Panel1
            //
            this.splitContainer1.Panel1.Controls.Add(this.dgvDatos);
            //
            // splitContainer1.Panel2
            //
            this.splitContainer1.Panel2.Controls.Add(this.numNota);
            this.splitContainer1.Panel2.Controls.Add(this.label6);
            this.splitContainer1.Panel2.Controls.Add(this.txtTitulo);
            this.splitContainer1.Panel2.Controls.Add(this.label5);
            this.splitContainer1.Panel2.Controls.Add(this.btnAceptar);
            this.splitContainer1.Panel2.Controls.Add(this.btnCancelar);
            this.splitContainer1.Panel2.Controls.Add(this.btnPreguntas);
            this.splitContainer1.Panel2.Controls.Add(this.cmbCerti);
            this.splitContainer1.Panel2.Controls.Add(this.numMInutos);
            this.splitContainer1.Panel2.Controls.Add(this.numPreguntas);
            this.splitContainer1.Panel2.Controls.Add(this.label2);
            this.splitContainer1.Panel2.Controls.Add(this.numID);
            this.splitContainer1.Panel2.Controls.Add(this.label1);
            this.splitContainer1.Panel2.Controls.Add(this.label4);
            this.splitContainer1.Panel2.Controls.Add(this.label3);
            this.splitContainer1.Size = new System.Drawing.Size(1304, 511);
            this.splitContainer1.SplitterDistance = 858;
            this.splitContainer1.TabIndex = 5;
            //
            // dgvDatos
            //
            this.dgvDatos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDatos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.cID,
            this.cCertificacion,
            this.cTitulo,
            this.cMinutos,
            this.cCantp,
            this.cNota});
            this.dgvDatos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDatos.Location = new System.Drawing.Point(0, 0);
            this.dgvDatos.Name = "dgvDatos";
            this.dgvDatos.RowHeadersWidth = 51;
            this.dgvDatos.RowTemplate.Height = 24;
            this.dgvDatos.Size = new System.Drawing.Size(858, 511);
            this.dgvDatos.TabIndex = 1;
            //
            // cID
            //
            this.cID.DataPropertyName = "ID";
            this.cID.HeaderText = "ID";
            this.cID.MinimumWidth = 6;
            this.cID.Name = "cID";
            this.cID.ReadOnly = true;
            this.cID.Width = 125;
            //
            // cCertificacion
            //
            this.cCertificacion.DataPropertyName = "NombreCertificacion";
            this.cCertificacion.HeaderText = "Certificación";
            this.cCertificacion.MinimumWidth = 6;
            this.cCertificacion.Name = "cCertificacion";
            this.cCertificacion.ReadOnly = true;
            this.cCertificacion.Width = 125;
            //
            // cTitulo
            //
            this.cTitulo.DataPropertyName = "Titulo";
            this.cTitulo.HeaderText = "Título";
            this.cTitulo.MinimumWidth = 6;
            this.cTitulo.Name = "cTitulo";
            this.cTitulo.ReadOnly = true;
            this.cTitulo.Width = 125;
            //
            // cMinutos
            //
            this.cMinutos.DataPropertyName = "Minutos";
            this.cMinutos.HeaderText = "Minutos";
            this.cMinutos.MinimumWidth = 6;
            this.cMinutos.Name = "cMinutos";
            this.cMinutos.ReadOnly = true;
            this.cMinutos.Width = 125;
            //
            // cCantp
            //
            this.cCantp.DataPropertyName = "CantPreguntas";
            this.cCantp.HeaderText = "Cantidad De Preguntas";
            this.cCantp.MinimumWidth = 6;
            this.cCantp.Name = "cCantp";
            this.cCantp.ReadOnly = true;
            this.cCantp.Width = 125;
            //
            // cNota
            //
            this.cNota.DataPropertyName = "NotaMinima";
            this.cNota.HeaderText = "Nota Mínima";
            this.cNota.MinimumWidth = 6;
            this.cNota.Name = "cNota";
            this.cNota.ReadOnly = true;
            this.cNota.Width = 125;
            //
            // numNota
            //
            this.numNota.Enabled = false;
            this.numNota.Location = new System.Drawing.Point(199, 322);
            this.numNota.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numNota.Name = "numNota";
            this.numNota.Size = new System.Drawing.Size(231, 22);
            this.numNota.TabIndex = 46;
            this.numNota.Value = new decimal(new int[] {
            80,
            0,
            0,
            0});
            //
            // label6
            //
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(13, 324);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(161, 17);
            this.label6.TabIndex = 45;
            this.label6.Text = "Nota Mínima Para Pasar";
            //
            // txtTitulo
            //
            this.txtTitulo.Enabled = false;
            this.txtTitulo.Location = new System.Drawing.Point(112, 139);
            this.txtTitulo.Name = "txtTitulo";
            this.txtTitulo.Size = new System.Drawing.Size(318, 22);
            this.txtTitulo.TabIndex = 44;
            //
            // label5
            //
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(11, 139);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(43, 17);
            this.label5.TabIndex = 43;
            this.label5.Text = "Título";
            //
            // btnAceptar
            //
            this.btnAceptar.Enabled = false;
            this.btnAceptar.Location = new System.Drawing.Point(233, 444);
            this.btnAceptar.Margin = new System.Windows.Forms.Padding(4);
            this.btnAceptar.Name = "btnAceptar";
            this.btnAceptar.Size = new System.Drawing.Size(197, 53);
            this.btnAceptar.TabIndex = 41;
            this.btnAceptar.Text = "&Aceptar";
            this.btnAceptar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnAceptar.UseVisualStyleBackColor = true;
            this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
            //
            // btnCancelar
            //
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancelar.Enabled = false;
            this.btnCancelar.Location = new System.Drawing.Point(14, 444);
            this.btnCancelar.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.Size = new System.Drawing.Size(211, 53);
            this.btnCancelar.TabIndex = 42;
            this.btnCancelar.Text = "&Cancelar";
            this.btnCancelar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageAboveText;
            this.btnCancelar.UseVisualStyleBackColor = true;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
            //
            // btnPreguntas
            //
            this.btnPreguntas.Enabled = false;
            this.btnPreguntas.Location = new System.Drawing.Point(14, 382);
            this.btnPreguntas.Name = "btnPreguntas";
            this.btnPreguntas.Size = new System.Drawing.Size(416, 55);
            this.btnPreguntas.TabIndex = 40;
            this.btnPreguntas.Text = "Editar preguntas";
            this.btnPreguntas.UseVisualStyleBackColor = true;
            this.btnPreguntas.Click += new System.EventHandler(this.btnPreguntas_Click);
            //
            // cmbCerti
            //
            this.cmbCerti.Enabled = false;
            this.cmbCerti.FormattingEnabled = true;
            this.cmbCerti.Location = new System.Drawing.Point(112, 72);
            this.cmbCerti.Name = "cmbCerti";
            this.cmbCerti.Size = new System.Drawing.Size(318, 24);
            this.cmbCerti.TabIndex = 39;
            //
            // numMInutos
            //
            this.numMInutos.Enabled = false;
            this.numMInutos.Location = new System.Drawing.Point(112, 202);
            this.numMInutos.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numMInutos.Name = "numMInutos";
            this.numMInutos.Size = new System.Drawing.Size(318, 22);
            this.numMInutos.TabIndex = 38;
            this.numMInutos.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            //
            // numPreguntas
            //
            this.numPreguntas.Enabled = false;
            this.numPreguntas.Location = new System.Drawing.Point(199, 259);
            this.numPreguntas.Name = "numPreguntas";
            this.numPreguntas.Size = new System.Drawing.Size(231, 22);
            this.numPreguntas.TabIndex = 37;
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(11, 259);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(153, 17);
            this.label2.TabIndex = 36;
            this.label2.Text = "Cantidad de Preguntas";
            //
            // numID
            //
            this.numID.Enabled = false;
            this.numID.Location = new System.Drawing.Point(112, 19);
            this.numID.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numID.Name = "numID";
            this.numID.Size = new System.Drawing.Size(318, 22);
            this.numID.TabIndex = 35;
            this.numID.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(11, 21);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(21, 17);
            this.label1.TabIndex = 34;
            this.label1.Text = "ID";
            //
            // label4
            //
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(11, 202);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(57, 17);
            this.label4.TabIndex = 32;
            this.label4.Text = "Minutos";
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(11, 72);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(85, 17);
            this.label3.TabIndex = 30;
            this.label3.Text = "Certificación";
            //
            // MantenimientoExamenes
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1304, 566);
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.tspPrincipal);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "MantenimientoExamenes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mantenimiento de Examenes";
            this.Load += new System.EventHandler(this.MantenimientoExamenes_Load);
            this.tspPrincipal.ResumeLayout(false);
            this.tspPrincipal.PerformLayout();
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            this.splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDatos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNota)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numMInutos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numPreguntas)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numID)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.MantenimientoExamenes.btnAceptar, UI.MantenimientoExamenes.btnCancelar, UI.MantenimientoExamenes.btnPreguntas, UI.MantenimientoExamenes.cCantp, UI.MantenimientoExamenes.cCertificacion, UI.MantenimientoExamenes.cID, UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.cMinutos, UI.MantenimientoExamenes.cNota, UI.MantenimientoExamenes.cTitulo, UI.MantenimientoExamenes.dgvDatos, UI.MantenimientoExamenes.label1, UI.MantenimientoExamenes.label2, UI.MantenimientoExamenes.label3, UI.MantenimientoExamenes.label4, UI.MantenimientoExamenes.label5, UI.MantenimientoExamenes.label6, UI.MantenimientoExamenes.numID, UI.MantenimientoExamenes.numMInutos, UI.MantenimientoExamenes.numNota, UI.MantenimientoExamenes.numPreguntas, UI.MantenimientoExamenes.splitContainer1, UI.MantenimientoExamenes.toolStripBtnBorrar, UI.MantenimientoExamenes.toolStripBtnBorrar_Click(), UI.MantenimientoExamenes.toolStripBtnEditar, UI.MantenimientoExamenes.toolStripBtnEditar_Click(), UI.MantenimientoExamenes.toolStripBtnNuevo, UI.MantenimientoExamenes.toolStripBtnNuevo_Click(), UI.MantenimientoExamenes.toolStripBtnSalir, UI.MantenimientoExamenes.toolStripBtnSalir_Click(), UI.MantenimientoExamenes.tspPrincipal, and UI.MantenimientoExamenes.txtTitulo.
Referenced by UI.MantenimientoExamenes.MantenimientoExamenes().
MantenimientoExamenes_Load()
void UI.MantenimientoExamenes.MantenimientoExamenes_Load (object sender, EventArgs e) private
Llena los objetos gráficos y los ajusta para su debido uso
Parameters
sender
e
Definition at line 31 of file MantenimientoExamenes.cs.
        {
            try
            {
                this.dgvDatos.AutoGenerateColumns = false;
                cmbCerti.DataSource = logicaCertificaciones.ObtenerTodos();
                cmbCerti.DisplayMember = "Descripcion";
                CargarDatos();
                _MyLogControlEventos.Info("Datos cargados");
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, UI.MantenimientoExamenes.CargarDatos(), UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.dgvDatos, and Capa.BLL.ICertificacionLN.ObtenerTodos().
toolStripBtnBorrar_Click()
void UI.MantenimientoExamenes.toolStripBtnBorrar_Click (object sender, EventArgs e) private
pide confirmación y borra el registro seleccionado de la bd
Parameters
sender
e
Definition at line 120 of file MantenimientoExamenes.cs.
        {
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    Examen examen = this.dgvDatos.SelectedRows[0].DataBoundItem as Examen;
                    if (MessageBox.Show($"¿Seguro que desea borrar el registro {examen.ID} {examen.Titulo}? Las preguntas asociadas se borrarán", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                    {
                        _MyLogControlEventos.Info($"Se borrró el examen: {examen.ID}");
                        logicaExamenes.Borrar(examen.ID);
                        this.CargarDatos();
                    }
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                deshabilitar();
                CargarDatos();
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, Capa.BLL.IExamenLN.Borrar(), UI.MantenimientoExamenes.CargarDatos(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.dgvDatos, Capa.Entities.Examen.ID, and UI.MantenimientoExamenes.logicaExamenes.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnEditar_Click()
void UI.MantenimientoExamenes.toolStripBtnEditar_Click (object sender, EventArgs e) private
Coloca los datos del objeto seleccionado en el panel derecho para su edición
Parameters
sender
e
Definition at line 154 of file MantenimientoExamenes.cs.
        {
            cont++;
            if(cont == 1)
                MessageBox.Show("Advertencia: si cambia el ID podría generar problemas, cambielo solo en caso de que sepa lo que está haciendo", "Advertencia", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            try
            {
                if (this.dgvDatos.SelectedRows.Count > 0)
                {
                    this.btnPreguntas.Enabled = true;
                    habilitar();
                    Examen examen = this.dgvDatos.SelectedRows[0].DataBoundItem as Examen;
                    numID.Value = examen.ID;
                    cmbCerti.SelectedIndex = examen.CertificacionA.Id - 1;
                    txtTitulo.Text = examen.Titulo;
                    numMInutos.Value = examen.Minutos;
                    numPreguntas.Value = examen.CantPreguntas;
                    _MyLogControlEventos.Info($"Edición del examen: {examen.ID}");
                }
                else
                {
                    MessageBox.Show("Seleccione el registro !", "Atención", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el mantenimiento de Examenes: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.MantenimientoExamenes._MyLogControlEventos, UI.MantenimientoExamenes.btnPreguntas, Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, UI.MantenimientoExamenes.cmbCerti, UI.MantenimientoExamenes.cont, UI.MantenimientoExamenes.dgvDatos, UI.MantenimientoExamenes.habilitar(), Capa.Entities.Certificacion.Id, Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, UI.MantenimientoExamenes.numID, UI.MantenimientoExamenes.numMInutos, UI.MantenimientoExamenes.numPreguntas, Capa.Entities.Examen.Titulo, and UI.MantenimientoExamenes.txtTitulo.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnNuevo_Click()
void UI.MantenimientoExamenes.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Reinicia la interfaz para crear un nuevo examen
Parameters
sender
e
Definition at line 71 of file MantenimientoExamenes.cs.
        {
            deshabilitar();
            habilitar();
            //numID.Value = dgvDatos.RowCount+1;
        }
References UI.MantenimientoExamenes.deshabilitar(), and UI.MantenimientoExamenes.habilitar().
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnSalir_Click()
void UI.MantenimientoExamenes.toolStripBtnSalir_Click (object sender, EventArgs e) private
cierra la ventana
Parameters
sender
e
Definition at line 53 of file MantenimientoExamenes.cs.
        {
            this.Close();
        }
Referenced by UI.MantenimientoExamenes.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.MantenimientoExamenes._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file MantenimientoExamenes.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.btnCancelar_Click(), UI.MantenimientoExamenes.btnPreguntas_Click(), UI.MantenimientoExamenes.MantenimientoExamenes_Load(), UI.MantenimientoExamenes.toolStripBtnBorrar_Click(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
btnAceptar
System.Windows.Forms.Button UI.MantenimientoExamenes.btnAceptar private
Definition at line 447 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), and UI.MantenimientoExamenes.InitializeComponent().
btnCancelar
System.Windows.Forms.Button UI.MantenimientoExamenes.btnCancelar private
Definition at line 448 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), and UI.MantenimientoExamenes.InitializeComponent().
btnPreguntas
System.Windows.Forms.Button UI.MantenimientoExamenes.btnPreguntas private
Definition at line 442 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.InitializeComponent(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
cCantp
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cCantp private
Definition at line 457 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
cCertificacion
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cCertificacion private
Definition at line 454 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
cID
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cID private
Definition at line 453 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
cmbCerti
System.Windows.Forms.ComboBox UI.MantenimientoExamenes.cmbCerti private
Definition at line 443 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), UI.MantenimientoExamenes.InitializeComponent(), UI.MantenimientoExamenes.MantenimientoExamenes_Load(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
cMinutos
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cMinutos private
Definition at line 456 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
cNota
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cNota private
Definition at line 458 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
components
System.ComponentModel.IContainer UI.MantenimientoExamenes.components = null private
Required designer variable.
Definition at line 9 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.Dispose().
cont
int UI.MantenimientoExamenes.cont = 0 private
Definition at line 19 of file MantenimientoExamenes.cs.
Referenced by UI.MantenimientoExamenes.toolStripBtnEditar_Click().
cTitulo
System.Windows.Forms.DataGridViewTextBoxColumn UI.MantenimientoExamenes.cTitulo private
Definition at line 455 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
dgvDatos
System.Windows.Forms.DataGridView UI.MantenimientoExamenes.dgvDatos private
Definition at line 437 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnPreguntas_Click(), UI.MantenimientoExamenes.CargarDatos(), UI.MantenimientoExamenes.InitializeComponent(), UI.MantenimientoExamenes.MantenimientoExamenes_Load(), UI.MantenimientoExamenes.toolStripBtnBorrar_Click(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
label1
System.Windows.Forms.Label UI.MantenimientoExamenes.label1 private
Definition at line 439 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
label2
System.Windows.Forms.Label UI.MantenimientoExamenes.label2 private
Definition at line 446 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
label3
System.Windows.Forms.Label UI.MantenimientoExamenes.label3 private
Definition at line 441 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
label4
System.Windows.Forms.Label UI.MantenimientoExamenes.label4 private
Definition at line 440 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
label5
System.Windows.Forms.Label UI.MantenimientoExamenes.label5 private
Definition at line 450 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
label6
System.Windows.Forms.Label UI.MantenimientoExamenes.label6 private
Definition at line 452 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
logicaCertificaciones
ICertificacionLN UI.MantenimientoExamenes.logicaCertificaciones = new CertificacionLN() private
Definition at line 17 of file MantenimientoExamenes.cs.
logicaExamenes
IExamenLN UI.MantenimientoExamenes.logicaExamenes = new ExamenLN() private
Definition at line 18 of file MantenimientoExamenes.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), and UI.MantenimientoExamenes.toolStripBtnBorrar_Click().
numID
System.Windows.Forms.NumericUpDown UI.MantenimientoExamenes.numID private
Definition at line 438 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), UI.MantenimientoExamenes.InitializeComponent(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
numMInutos
System.Windows.Forms.NumericUpDown UI.MantenimientoExamenes.numMInutos private
Definition at line 444 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), UI.MantenimientoExamenes.InitializeComponent(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
numNota
System.Windows.Forms.NumericUpDown UI.MantenimientoExamenes.numNota private
Definition at line 451 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), and UI.MantenimientoExamenes.InitializeComponent().
numPreguntas
System.Windows.Forms.NumericUpDown UI.MantenimientoExamenes.numPreguntas private
Definition at line 445 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.InitializeComponent(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
splitContainer1
System.Windows.Forms.SplitContainer UI.MantenimientoExamenes.splitContainer1 private
Definition at line 436 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnBorrar
System.Windows.Forms.ToolStripButton UI.MantenimientoExamenes.toolStripBtnBorrar private
Definition at line 434 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnEditar
System.Windows.Forms.ToolStripButton UI.MantenimientoExamenes.toolStripBtnEditar private
Definition at line 433 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton UI.MantenimientoExamenes.toolStripBtnNuevo private
Definition at line 432 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.MantenimientoExamenes.toolStripBtnSalir private
Definition at line 435 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
tspPrincipal
System.Windows.Forms.ToolStrip UI.MantenimientoExamenes.tspPrincipal private
Definition at line 431 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.InitializeComponent().
txtTitulo
System.Windows.Forms.TextBox UI.MantenimientoExamenes.txtTitulo private
Definition at line 449 of file MantenimientoExamenes.Designer.cs.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click(), UI.MantenimientoExamenes.deshabilitar(), UI.MantenimientoExamenes.habilitar(), UI.MantenimientoExamenes.InitializeComponent(), and UI.MantenimientoExamenes.toolStripBtnEditar_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Mantenimientos/MantenimientoExamenes.cs
118710756/DbaCreator/UI/Mantenimientos/MantenimientoExamenes.Designer.cs