DBACreator: Capa.DAL.ExamenDB Class Reference
Capa.DAL.ExamenDB Class Reference
Static Public Member Functions
static void Agregar (Examen e)
Método que guarda el examen en la base de datos
static List< Examen > ObtenerTodos ()
Método para obtener todos los datos de la tabla Examen
static List< Examen > SeleccionarPorCertificacion (int idCertificacion)
Método que busca los examenes por certificación
static Examen SeleccionarPorId (int id)
Retorna de la tabla Examen el dato con el ID buscado
static void Borrar (int id)
Borra el dato de la tabla con el ID enviado
static void Actualizar (Examen e)
Actuliza el examen que tenga el ID buscado
Detailed Description
Definition at line 12 of file ExamenDB.cs.
Member Function Documentation
Actualizar()
static void Capa.DAL.ExamenDB.Actualizar (Examen e) static
Actuliza el examen que tenga el ID buscado
Parameters
e ID Buscado
Definition at line 153 of file ExamenDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_ActualizarExamen";
                comando.Parameters.AddWithValue("@id", e.ID);
                comando.Parameters.AddWithValue("@idCertificacion", e.CertificacionA.Id);
                comando.Parameters.AddWithValue("@titulo", e.Titulo);
                comando.Parameters.AddWithValue("@minutos", e.Minutos);
                comando.Parameters.AddWithValue("@cantPreguntas", e.CantPreguntas);
                comando.Parameters.AddWithValue("@notaMinima", e.NotaMinima);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Capa.Entities.Certificacion.Id, Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, and Capa.Entities.Examen.Titulo.
Referenced by Capa.BLL.ExamenLN.Guardar().
Agregar()
static void Capa.DAL.ExamenDB.Agregar (Examen e) static
Método que guarda el examen en la base de datos
Parameters
c Examen del cuál extraerá los datos
Definition at line 18 of file ExamenDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarExamen";
                comando.Parameters.AddWithValue("@id", e.ID);
                comando.Parameters.AddWithValue("@idCertificacion", e.CertificacionA.Id);
                comando.Parameters.AddWithValue("@titulo", e.Titulo);
                comando.Parameters.AddWithValue("@minutos", e.Minutos);
                comando.Parameters.AddWithValue("@cantPreguntas", e.CantPreguntas);
                comando.Parameters.AddWithValue("@notaMinima", e.NotaMinima);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Capa.Entities.Certificacion.Id, Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, and Capa.Entities.Examen.Titulo.
Referenced by Capa.BLL.ExamenLN.Guardar().
Borrar()
static void Capa.DAL.ExamenDB.Borrar (int id) static
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Definition at line 137 of file ExamenDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_BorrarExamen";
                comando.Parameters.AddWithValue("@id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.ExamenLN.Borrar().
ObtenerTodos()
static List< Examen > Capa.DAL.ExamenDB.ObtenerTodos () static
Método para obtener todos los datos de la tabla Examen
Returns
Retorna una lista con todos los datos de la tabla Examen
Definition at line 39 of file ExamenDB.cs.
        {
            List<Examen> lista = new List<Examen>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarExamenes";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Examen e = new Examen();
                    e.ID = (int)dr["IDExamen"];
                    e.CertificacionA = CertificacionDB.SeleccionarPorId((int)dr["IDCertificacion"]);
                    e.Titulo = dr["Titulo"].ToString();
                    e.Minutos = (int)dr["Minutos"];
                    //e.CantPreguntas = (int)dr["CantPreguntas"];
                    e.CantPreguntas = PreguntaDB.SeleccionarPorExamen(e.ID).Count;
                    e.NotaMinima = Convert.ToDouble(dr["NotaMinima"]);
                    lista.Add(e);
                }
            }
            return lista;
        }
References Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, Capa.DAL.PreguntaDB.SeleccionarPorExamen(), Capa.DAL.CertificacionDB.SeleccionarPorId(), and Capa.Entities.Examen.Titulo.
Referenced by Capa.BLL.ExamenLN.ObtenerTodos().
SeleccionarPorCertificacion()
static List< Examen > Capa.DAL.ExamenDB.SeleccionarPorCertificacion (int idCertificacion) static
Método que busca los examenes por certificación
Parameters
idCertificacion ID de certificación a buscar
Returns
retorna una lista de examenes que pertenecen a una certificación
Definition at line 72 of file ExamenDB.cs.
        {
            List<Examen> lista = new List<Examen>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarExamenesPorCertificacion";
                comando.Parameters.AddWithValue("@IdCertificacion", idCertificacion);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Examen e = new Examen();
                    e.ID = (int)dr["IDExamen"];
                    e.CertificacionA = CertificacionDB.SeleccionarPorId((int)dr["IDCertificacion"]);
                    e.Titulo = dr["Titulo"].ToString();
                    e.Minutos = (int)dr["Minutos"];
                    e.CantPreguntas = PreguntaDB.SeleccionarPorExamen(e.ID).Count;
                    e.NotaMinima = Convert.ToDouble(dr["NotaMinima"]);
                    lista.Add(e);
                }
            }
            return lista;
        }
References Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, Capa.DAL.PreguntaDB.SeleccionarPorExamen(), Capa.DAL.CertificacionDB.SeleccionarPorId(), and Capa.Entities.Examen.Titulo.
Referenced by Capa.BLL.ExamenLN.ObtenerPorCertificacion().
SeleccionarPorId()
static Examen Capa.DAL.ExamenDB.SeleccionarPorId (int id) static
Retorna de la tabla Examen el dato con el ID buscado
Parameters
id ID a buscar
Returns
Retorna de la tabla Examen el dato con el ID buscado
Definition at line 106 of file ExamenDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarExamenPorID";
                comando.Parameters.AddWithValue("@Id", id);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Examen e = new Examen();
                    e.ID = (int)dr["IDExamen"];
                    e.CertificacionA = CertificacionDB.SeleccionarPorId((int)dr["IDCertificacion"]);
                    e.Titulo = dr["Titulo"].ToString();
                    e.Minutos = (int)dr["Minutos"];
                    //e.CantPreguntas = (int)dr["CantPreguntas"];
                    e.CantPreguntas = PreguntaDB.SeleccionarPorExamen(e.ID).Count;
                    e.NotaMinima = Convert.ToDouble(dr["NotaMinima"]);
                    return e;
                }
            }
            return null;
        }
References Capa.Entities.Examen.CantPreguntas, Capa.Entities.Examen.CertificacionA, FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Capa.Entities.Examen.ID, Capa.Entities.Examen.Minutos, Capa.Entities.Examen.NotaMinima, Capa.DAL.PreguntaDB.SeleccionarPorExamen(), Capa.DAL.CertificacionDB.SeleccionarPorId(), and Capa.Entities.Examen.Titulo.
Referenced by Capa.BLL.ExamenLN.ObtenerPorID().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/ExamenDB.cs