DBACreator: Capa.DAL.PreguntaDB Class Reference
Capa.DAL.PreguntaDB Class Reference
Static Public Member Functions
static void Agregar (Pregunta p)
Guarda una pregunta en su tabla de la base de datos
static void Actualizar (Pregunta p)
Actualiza una pregunta en su tabla de la base de datos
static Pregunta SeleccionarPorId (int id)
Sirve para buscar por ID una pregunta en específico
static void Borrar (int id)
Borra la pregunta cuyo id sea igual al parámetro
static List< Pregunta > SeleccionarPorExamen (int idExamen)
Método para ver las preguntas de un examen
Detailed Description
Definition at line 13 of file PreguntaDB.cs.
Member Function Documentation
Actualizar()
static void Capa.DAL.PreguntaDB.Actualizar (Pregunta p) static
Actualiza una pregunta en su tabla de la base de datos
Parameters
p Objeto del que extrae los datos
Definition at line 43 of file PreguntaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_ActualizarPregunta";
                comando.Parameters.AddWithValue("@idPregunta", p.ID);
                comando.Parameters.AddWithValue("@idExamen", p.IDExamen);
                comando.Parameters.AddWithValue("@idCertificacion", p.IDCertificacion);
                comando.Parameters.AddWithValue("@Enunciado", p.Enunciado);
                comando.Parameters.AddWithValue("@respuesta1", p.Respuesta1);
                comando.Parameters.AddWithValue("@respuesta2", p.Respuesta2);
                comando.Parameters.AddWithValue("@respuesta3", p.Respuesta3);
                comando.Parameters.AddWithValue("@correcta", p.Correcta);
                comando.Parameters.AddWithValue("@imagen", p.Imagen);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Pregunta.Correcta, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Pregunta.Enunciado, IDataBase.ExecuteNonQuery(), Capa.Entities.Pregunta.ID, Capa.Entities.Pregunta.IDCertificacion, Capa.Entities.Pregunta.IDExamen, Capa.Entities.Pregunta.Imagen, Capa.Entities.Pregunta.Respuesta1, Capa.Entities.Pregunta.Respuesta2, and Capa.Entities.Pregunta.Respuesta3.
Referenced by Capa.BLL.PreguntaLN.Guardar().
Agregar()
static void Capa.DAL.PreguntaDB.Agregar (Pregunta p) static
Guarda una pregunta en su tabla de la base de datos
Parameters
p Objeto del que extrae los datos
Definition at line 20 of file PreguntaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarPregunta";
                comando.Parameters.AddWithValue("@idExamen", p.IDExamen);
                comando.Parameters.AddWithValue("@idCertificacion", p.IDCertificacion);
                comando.Parameters.AddWithValue("@Enunciado", p.Enunciado);
                comando.Parameters.AddWithValue("@respuesta1", p.Respuesta1);
                comando.Parameters.AddWithValue("@respuesta2", p.Respuesta2);
                comando.Parameters.AddWithValue("@respuesta3", p.Respuesta3);
                comando.Parameters.AddWithValue("@correcta", p.Correcta);
                comando.Parameters.AddWithValue("@imagen", p.Imagen);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Pregunta.Correcta, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Pregunta.Enunciado, IDataBase.ExecuteNonQuery(), Capa.Entities.Pregunta.IDCertificacion, Capa.Entities.Pregunta.IDExamen, Capa.Entities.Pregunta.Imagen, Capa.Entities.Pregunta.Respuesta1, Capa.Entities.Pregunta.Respuesta2, and Capa.Entities.Pregunta.Respuesta3.
Referenced by Capa.BLL.PreguntaLN.Guardar().
Borrar()
static void Capa.DAL.PreguntaDB.Borrar (int id) static
Borra la pregunta cuyo id sea igual al parámetro
Parameters
id Id de pregunta a consultar
Definition at line 103 of file PreguntaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_BorrarPregunta";
                comando.Parameters.AddWithValue("@id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.PreguntaLN.Borrar().
SeleccionarPorExamen()
static List< Pregunta > Capa.DAL.PreguntaDB.SeleccionarPorExamen (int idExamen) static
Método para ver las preguntas de un examen
Parameters
idExamen Examen a consultar
Returns
Retorna una lista de preguntas asignada a un Id de Examen
Definition at line 121 of file PreguntaDB.cs.
        {
            List<Pregunta> lista = new List<Pregunta>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarPreguntasPorExamen";
                comando.Parameters.AddWithValue("@IdExamen", idExamen);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Pregunta p = new Pregunta();
                    p.ID = (int)dr["IDPregunta"];
                    p.IDCertificacion = (int)dr["IDCertificacion"];
                    p.IDExamen = (int)dr["IDExamen"];
                    p.Enunciado = dr["Enunciado"].ToString();
                    p.Correcta = dr["Correcta"].ToString();
                    p.Respuesta1 = dr["Respuesta1"].ToString();
                    p.Respuesta2 = dr["Respuesta2"].ToString();
                    p.Respuesta3 = dr["Respuesta3"].ToString();
                    p.Imagen = (Byte[])dr["Imagen"];
                    lista.Add(p);
                }
            }
            return lista;
        }
References Capa.Entities.Pregunta.Correcta, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Pregunta.Enunciado, IDataBase.ExecuteDataSet(), Capa.Entities.Pregunta.ID, Capa.Entities.Pregunta.IDCertificacion, Capa.Entities.Pregunta.IDExamen, Capa.Entities.Pregunta.Imagen, Capa.Entities.Pregunta.Respuesta1, Capa.Entities.Pregunta.Respuesta2, and Capa.Entities.Pregunta.Respuesta3.
Referenced by Capa.DAL.ExamenDB.ObtenerTodos(), Capa.DAL.ExamenDB.SeleccionarPorCertificacion(), Capa.BLL.PreguntaLN.SeleccionarPorExamen(), and Capa.DAL.ExamenDB.SeleccionarPorId().
SeleccionarPorId()
static Pregunta Capa.DAL.PreguntaDB.SeleccionarPorId (int id) static
Sirve para buscar por ID una pregunta en específico
Parameters
id Pregunta a consultar
Returns
Retorna la pregunta cuyo Id sea igual al parámetro
Definition at line 70 of file PreguntaDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarPreguntaPorID";
                comando.Parameters.AddWithValue("@Id", id);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Pregunta p = new Pregunta();
                    p.ID = (int)dr["IDPregunta"];
                    p.IDCertificacion = (int)dr["IDCertificacion"];
                    p.IDExamen = (int)dr["IDExamen"];
                    p.Enunciado = dr["Enunciado"].ToString();
                    p.Correcta = dr["Correcta"].ToString();
                    p.Respuesta1 = dr["Respuesta1"].ToString();
                    p.Respuesta2 = dr["Respuesta2"].ToString();
                    p.Respuesta3 = dr["Respuesta3"].ToString();
                    p.Imagen = (Byte[])dr["Imagen"];
                    return p;
                }
            }
            return null;
        }
References Capa.Entities.Pregunta.Correcta, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Pregunta.Enunciado, IDataBase.ExecuteDataSet(), Capa.Entities.Pregunta.ID, Capa.Entities.Pregunta.IDCertificacion, Capa.Entities.Pregunta.IDExamen, Capa.Entities.Pregunta.Imagen, Capa.Entities.Pregunta.Respuesta1, Capa.Entities.Pregunta.Respuesta2, and Capa.Entities.Pregunta.Respuesta3.
Referenced by Capa.BLL.PreguntaLN.ObtenerPorID().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/PreguntaDB.cs