DBACreator: Capa.Entities.EncFactura Class Reference
Capa.Entities.EncFactura Class Reference
Factura en general, contiene varios Detalles de factura
Public Member Functions
void AgregarDetalle (DetFactura pFacturaDetalle)
Inserta un item comprado en la factura
double ObtenerTotal ()
Obtiene el total que debe pagar el cliente por todos los item comprados
Properties
int IDFactura [get, set]
int IDTarjeta [get, set]
int IDCliente [get, set]
DateTime FechaFacturacion [get, set]
string NumeroTarjeta [get, set]
List< DetFactura > _ListaFacturaDetalle = new List<DetFactura>() [get]
Detailed Description
Factura en general, contiene varios Detalles de factura
Definition at line 12 of file EncFactura.cs.
Member Function Documentation
AgregarDetalle()
void Capa.Entities.EncFactura.AgregarDetalle (DetFactura pFacturaDetalle)
Inserta un item comprado en la factura
Parameters
pFacturaDetalle Objeto a insertar
Definition at line 26 of file EncFactura.cs.
        {
            _ListaFacturaDetalle.Add(pFacturaDetalle);
        }
References Capa.Entities.EncFactura._ListaFacturaDetalle.
Referenced by UI.FacturacionExamenes.btnAgregar_Click().
ObtenerTotal()
double Capa.Entities.EncFactura.ObtenerTotal ()
Obtiene el total que debe pagar el cliente por todos los item comprados
Returns
Retona un numero decimal en dólares
Definition at line 35 of file EncFactura.cs.
        {
            double total = 0;
            foreach(var item in _ListaFacturaDetalle)
            {
                total += item.Monto;
            }
            return total;
        }
References Capa.Entities.EncFactura._ListaFacturaDetalle.
Referenced by UI.FacturacionExamenes.btnAgregar_Click(), and Capa.DAL.FacturaDB.Guardar().
Property Documentation
_ListaFacturaDetalle
List<DetFactura> Capa.Entities.EncFactura._ListaFacturaDetalle = new List<DetFactura>() get
Definition at line 20 of file EncFactura.cs.
{ get; } = new List<DetFactura>();
Referenced by Capa.Entities.EncFactura.AgregarDetalle(), UI.FacturacionExamenes.btnAgregar_Click(), Capa.DAL.FacturaDB.Guardar(), Capa.Entities.EncFactura.ObtenerTotal(), and UI.FacturacionExamenes.toolStripBtnFacturar_Click().
FechaFacturacion
DateTime Capa.Entities.EncFactura.FechaFacturacion get set
Definition at line 17 of file EncFactura.cs.
{ get; set; }
Referenced by UI.FacturacionExamenes.toolStripBtnFacturar_Click().
IDCliente
int Capa.Entities.EncFactura.IDCliente get set
Definition at line 16 of file EncFactura.cs.
{ get; set; }
Referenced by Capa.DAL.FacturaDB.Guardar(), and UI.FacturacionExamenes.toolStripBtnNuevo_Click().
IDFactura
int Capa.Entities.EncFactura.IDFactura get set
Definition at line 14 of file EncFactura.cs.
{ get; set; }
Referenced by UI.FacturacionExamenes.btnAgregar_Click(), Capa.DAL.FacturaDB.Guardar(), UI.FacturacionExamenes.toolStripBtnFacturar_Click(), and UI.FacturacionExamenes.toolStripBtnNuevo_Click().
IDTarjeta
int Capa.Entities.EncFactura.IDTarjeta get set
Definition at line 15 of file EncFactura.cs.
{ get; set; }
Referenced by Capa.DAL.FacturaDB.Guardar(), and UI.FacturacionExamenes.toolStripBtnFacturar_Click().
NumeroTarjeta
string Capa.Entities.EncFactura.NumeroTarjeta get set
Definition at line 18 of file EncFactura.cs.
{ get; set; }
Referenced by Capa.DAL.FacturaDB.Guardar(), and UI.FacturacionExamenes.toolStripBtnFacturar_Click().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.Entities/EncFactura.cs