DBACreator: Capa.BLL.ClienteLN Class Reference
Capa.BLL.ClienteLN Class Reference
Public Member Functions
void Guardar (Cliente c)
Método que guarda el cliente en la base de datos, solo en caso de que no encuentre un dato con ese ID
Cliente ObtenerPorID (int id)
Retorna de la tabla Cliente el dato con el ID buscado
Cliente ObtenerPorTelefono (string telefono)
Retorna de la tabla Cliente el dato con el telefono buscado
Cliente ObtenerPorCorreo (string email)
Retorna de la tabla Cliente el dato con el email buscado
List< Cliente > ObtenerTodos ()
Método para obtener todos los datos de la tabla Cliente
void Borrar (string id)
Borra el dato de la tabla con el ID enviado
void Actualizar (Cliente c, int idViejo)
actualiza el dato de la tabla con el ID enviado
void Guardar (Cliente c)
Cliente ObtenerPorID (int id)
Cliente ObtenerPorTelefono (string telefono)
Cliente ObtenerPorCorreo (string email)
List< Cliente > ObtenerTodos ()
void Borrar (string id)
void Actualizar (Cliente c, int idViejo)
Detailed Description
Definition at line 11 of file ClienteLN.cs.
Member Function Documentation
Actualizar()
void Capa.BLL.ClienteLN.Actualizar (Cliente c, int idViejo)
actualiza el dato de la tabla con el ID enviado
Parameters
c Cliente del cual extrae los datos
idViejo ID a buscar
Implements Capa.BLL.IClienteLN.
Definition at line 80 of file ClienteLN.cs.
        {
            ClienteDB.Update(c, idViejo);
        }
References Capa.DAL.ClienteDB.Update().
Borrar()
void Capa.BLL.ClienteLN.Borrar (string id)
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Implements Capa.BLL.IClienteLN.
Definition at line 70 of file ClienteLN.cs.
        {
            ClienteDB.Delete(id);
        }
References Capa.DAL.ClienteDB.Delete().
Guardar()
void Capa.BLL.ClienteLN.Guardar (Cliente c)
Método que guarda el cliente en la base de datos, solo en caso de que no encuentre un dato con ese ID
Parameters
c Cliente del cuál extraerá los datos
Implements Capa.BLL.IClienteLN.
Definition at line 17 of file ClienteLN.cs.
        {
            ClienteDB db = new ClienteDB();
            if (ClienteDB.SeleccionarPorId(c.Id)==null)
            {
                ClienteDB.AgregarCliente(c);
            }
        }
References Capa.DAL.ClienteDB.AgregarCliente(), Capa.Entities.Cliente.Id, and Capa.DAL.ClienteDB.SeleccionarPorId().
ObtenerPorCorreo()
Cliente Capa.BLL.ClienteLN.ObtenerPorCorreo (string email)
Retorna de la tabla Cliente el dato con el email buscado
Parameters
email email a buscar
Returns
Implements Capa.BLL.IClienteLN.
Definition at line 52 of file ClienteLN.cs.
        {
            return ClienteDB.SeleccionarPorEmail(email);
        }
References Capa.DAL.ClienteDB.SeleccionarPorEmail().
ObtenerPorID()
Cliente Capa.BLL.ClienteLN.ObtenerPorID (int id)
Retorna de la tabla Cliente el dato con el ID buscado
Parameters
id ID a buscar
Returns
Implements Capa.BLL.IClienteLN.
Definition at line 32 of file ClienteLN.cs.
        {
            return ClienteDB.SeleccionarPorId(id);
        }
References Capa.DAL.ClienteDB.SeleccionarPorId().
ObtenerPorTelefono()
Cliente Capa.BLL.ClienteLN.ObtenerPorTelefono (string telefono)
Retorna de la tabla Cliente el dato con el telefono buscado
Parameters
telefono telefono a buscar
Returns
Implements Capa.BLL.IClienteLN.
Definition at line 42 of file ClienteLN.cs.
        {
            return ClienteDB.SeleccionarPorTelefono(telefono);
        }
References Capa.DAL.ClienteDB.SeleccionarPorTelefono().
ObtenerTodos()
List< Cliente > Capa.BLL.ClienteLN.ObtenerTodos ()
Método para obtener todos los datos de la tabla Cliente
Returns
Retorna una lista con todos los datos de la tabla Cliente
Implements Capa.BLL.IClienteLN.
Definition at line 61 of file ClienteLN.cs.
        {
            return ClienteDB.ObtenerClientes();
        }
References Capa.DAL.ClienteDB.ObtenerClientes().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/ClienteLN.cs