DBACreator: UI.RealizarExamen Class Reference
UI.RealizarExamen Class Reference
Public Member Functions
RealizarExamen (Cliente c)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void RealizarExamen_Load (object sender, EventArgs e)
Carga los datos del cliente
void comenzarExamen (ClienteDetalle cDetalle)
Metodo que da comienzo al examen
void EventoTiempo (object sender, System.Timers.ElapsedEventArgs e)
Metodo para que se vea el tiempo avanzar en horas, minutos y segundos
void habilitar ()
habilita elementos gráficos
void SiguientePregunta ()
Avanza a la siguiente pregunta del examen
void Calificar ()
Califica que la pregunta seleccionada sea la correcta
void RevisarExamen ()
Revisa el resultado final del examen, en caso de aprobado abre el reporte de certificado
void btnRealizarExamen_Click (object sender, EventArgs e)
Valida la compra y en caso de que todo sea correcto, pide confirmación y llama al método comenzarExamen
void btnSalir_Click (object sender, EventArgs e)
cierra la ventana
void btnSiguiente_Click (object sender, EventArgs e)
Botón para que el cliente pueda avanzar de pregunta
void RealizarExamen_FormClosed (object sender, FormClosedEventArgs e)
Si ya se inició el examen y el usuario cierra la ventana, arroja la revisión del examen
void tmr_Tick (object sender, EventArgs e)
Estos son los eventos que pasan cada que el reloj avanza
void RealizarExamen_FormClosing (object sender, FormClosingEventArgs e)
Antes de cerrar la aplicaión para los relojes para evitar posibles errores
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Cliente cliente
Examen examen
Intento intento
int cont = 0
int h
int m
int s
System.Timers.Timer t
List< Pregunta > ListaPreguntas
int NoPregunta = -1
int Total = 0
int LimiteTiempo
IExamenLN logicaExamenes = new ExamenLN()
IPreguntaLN logicaPreguntas = new PreguntaLN()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label label5
System.Windows.Forms.Label lbl1
System.Windows.Forms.Label lblNombre
System.Windows.Forms.Label lblID
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox txtCodigo
System.Windows.Forms.Button btnRealizarExamen
System.Windows.Forms.GroupBox gBValidacion
System.Windows.Forms.GroupBox gbExamen
System.Windows.Forms.Timer tmr
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.Button btnSalir
System.Windows.Forms.RichTextBox rtEnunciado
System.Windows.Forms.Label lblTiempo
System.Windows.Forms.Label label2
System.Windows.Forms.Button btnSiguiente
System.Windows.Forms.RadioButton radioR3
System.Windows.Forms.RadioButton radioR2
System.Windows.Forms.RadioButton radioR1
System.Windows.Forms.Label label6
System.Windows.Forms.Label lblTotalPreguntas
System.Windows.Forms.Label lblNo
System.Windows.Forms.Label label3
System.Windows.Forms.Label lblSlash
System.Windows.Forms.Label lbTotalTiempo
System.Windows.Forms.TextBox textBoxTiempo
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 16 of file RealizarExamen.cs.
Constructor & Destructor Documentation
RealizarExamen()
UI.RealizarExamen.RealizarExamen (Cliente c)
Definition at line 33 of file RealizarExamen.cs.
        {
            InitializeComponent();
            this.cliente = c;
        }
References UI.RealizarExamen.InitializeComponent().
Member Function Documentation
btnRealizarExamen_Click()
void UI.RealizarExamen.btnRealizarExamen_Click (object sender, EventArgs e) private
Valida la compra y en caso de que todo sea correcto, pide confirmación y llama al método comenzarExamen
Parameters
sender
e
Definition at line 213 of file RealizarExamen.cs.
        {
            try
            {
                ClienteDetalle cDetalle = FacturaLN.ObtenerDetallePorCodigo(cliente.Id, txtCodigo.Text);
                if (cDetalle == null)
                {
                    MessageBox.Show("No se ha encontrado su compra", "Código no encontrado", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }
                if (cDetalle.ExamenRealizado == true)
                {
                    MessageBox.Show("Usted ya realizó este examen, para volver a realizarlo debe pagarlo de nuevo", "Examen ya realizado", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }
                else
                {
                    if (MessageBox.Show("Su compra se ha encontrado ¿Desea comenzar el examen?", "Código encontrado", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.Yes)
                    {
                        comenzarExamen(cDetalle);
                        return;
                    }
                    else
                        return;
                }
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en la autenticación: " + er.Message);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.cliente, UI.RealizarExamen.comenzarExamen(), Capa.Entities.ClienteDetalle.ExamenRealizado, Capa.Entities.Cliente.Id, Capa.BLL.FacturaLN.ObtenerDetallePorCodigo(), and UI.RealizarExamen.txtCodigo.
Referenced by UI.RealizarExamen.InitializeComponent().
btnSalir_Click()
void UI.RealizarExamen.btnSalir_Click (object sender, EventArgs e) private
cierra la ventana
Parameters
sender
e
Definition at line 252 of file RealizarExamen.cs.
        {
            this.Close();
        }
Referenced by UI.RealizarExamen.InitializeComponent().
btnSiguiente_Click()
void UI.RealizarExamen.btnSiguiente_Click (object sender, EventArgs e) private
Botón para que el cliente pueda avanzar de pregunta
Parameters
sender
e
Definition at line 262 of file RealizarExamen.cs.
        {
            try
            {
                Calificar();
                if (NoPregunta == ListaPreguntas.Count - 1)
                {
                    tmr.Stop();
                    t.Stop();
                    RevisarExamen();
                    cont++;
                    btnSiguiente.Enabled = false;
                }
                else
                {
                    lblNo.Text = (NoPregunta + 2).ToString();
                    SiguientePregunta();
                }
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en realización: " + er.Message);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.btnSiguiente, UI.RealizarExamen.Calificar(), UI.RealizarExamen.cont, UI.RealizarExamen.lblNo, UI.RealizarExamen.ListaPreguntas, UI.RealizarExamen.NoPregunta, UI.RealizarExamen.RevisarExamen(), UI.RealizarExamen.SiguientePregunta(), UI.RealizarExamen.t, and UI.RealizarExamen.tmr.
Referenced by UI.RealizarExamen.InitializeComponent().
Calificar()
void UI.RealizarExamen.Calificar () private
Califica que la pregunta seleccionada sea la correcta
Definition at line 168 of file RealizarExamen.cs.
        {
            Pregunta pregunta = ListaPreguntas[NoPregunta];
            if (radioR1.Checked && radioR1.Text == pregunta.Correcta)
                Total++;
            if (radioR2.Checked && radioR2.Text == pregunta.Correcta)
                Total++;
            if (radioR3.Checked && radioR3.Text == pregunta.Correcta)
                Total++;
        }
References Capa.Entities.Pregunta.Correcta, UI.RealizarExamen.ListaPreguntas, UI.RealizarExamen.NoPregunta, UI.RealizarExamen.radioR1, UI.RealizarExamen.radioR2, UI.RealizarExamen.radioR3, and UI.RealizarExamen.Total.
Referenced by UI.RealizarExamen.btnSiguiente_Click().
comenzarExamen()
void UI.RealizarExamen.comenzarExamen (ClienteDetalle cDetalle) private
Metodo que da comienzo al examen
Parameters
cDetalle Parámetro del que extrae los datos para la realización
Definition at line 55 of file RealizarExamen.cs.
        {
            try
            {
                examen = logicaExamenes.ObtenerPorID(cDetalle.IDExamen);
                FacturaLN.MarcarRealizado(cDetalle.codigoUnico);
                intento = new Intento();
                intento.IDIntento = IntentoLN.ObtenerNumeroDeIntentoActual();
                intento.IDCliente = cliente.Id;
                intento.IDExamen = examen.ID;
                intento.Exitoso = false;
                ListaPreguntas = logicaPreguntas.SeleccionarPorExamen(examen.ID);
                lblTotalPreguntas.Text = ListaPreguntas.Count.ToString();
                IntentoLN.Insertar(intento);
                gbExamen.Text = examen.Titulo;
                gBValidacion.Visible = false;
                SiguientePregunta();
                habilitar();
                LimiteTiempo = examen.Minutos * 60;
                if (examen.Minutos == 1)
                    lbTotalTiempo.Text = examen.Minutos + " Minuto";
                else
                    lbTotalTiempo.Text = examen.Minutos + " Minutos";
                _MyLogControlEventos.Info($"El cliente {cliente.Nombre} {cliente.Apellido} realiza {examen.Titulo}");
                tmr.Start();
                t = new System.Timers.Timer();
                t.Interval = 1000;
                t.Elapsed += EventoTiempo;
                t.Start();
                cont++;
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en realización: " + er.Message);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.cliente, Capa.Entities.ClienteDetalle.codigoUnico, UI.RealizarExamen.cont, UI.RealizarExamen.EventoTiempo(), UI.RealizarExamen.examen, Capa.Entities.Intento.Exitoso, UI.RealizarExamen.gbExamen, UI.RealizarExamen.gBValidacion, UI.RealizarExamen.habilitar(), Capa.Entities.Cliente.Id, Capa.Entities.Examen.ID, Capa.Entities.Intento.IDCliente, Capa.Entities.ClienteDetalle.IDExamen, Capa.Entities.Intento.IDExamen, Capa.Entities.Intento.IDIntento, Capa.BLL.IntentoLN.Insertar(), UI.RealizarExamen.intento, UI.RealizarExamen.lblTotalPreguntas, UI.RealizarExamen.lbTotalTiempo, UI.RealizarExamen.LimiteTiempo, UI.RealizarExamen.ListaPreguntas, UI.RealizarExamen.logicaExamenes, UI.RealizarExamen.logicaPreguntas, Capa.BLL.FacturaLN.MarcarRealizado(), Capa.Entities.Examen.Minutos, Capa.BLL.IntentoLN.ObtenerNumeroDeIntentoActual(), Capa.BLL.IExamenLN.ObtenerPorID(), Capa.BLL.IPreguntaLN.SeleccionarPorExamen(), UI.RealizarExamen.SiguientePregunta(), UI.RealizarExamen.t, Capa.Entities.Examen.Titulo, and UI.RealizarExamen.tmr.
Referenced by UI.RealizarExamen.btnRealizarExamen_Click().
Dispose()
override void UI.RealizarExamen.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file RealizarExamen.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.RealizarExamen.components.
EventoTiempo()
void UI.RealizarExamen.EventoTiempo (object sender, System.Timers.ElapsedEventArgs e) private
Metodo para que se vea el tiempo avanzar en horas, minutos y segundos
Parameters
sender
e
Definition at line 108 of file RealizarExamen.cs.
        {
            Invoke(new Action(() =>
            {
                s += 1;
                if (s==60)
                {
                    s = 0;
                    m += 1;
                }
                if (m == 60)
                {
                    m = 0;
                    h += 1;
                }
                textBoxTiempo.Text = string.Format("{0}:{1}:{2}", h.ToString().PadLeft(2, '0'), m.ToString().PadLeft(2, '0'), s.ToString().PadLeft(2, '0'));
            }
            ));
        }
References UI.RealizarExamen.h, UI.RealizarExamen.m, UI.RealizarExamen.s, and UI.RealizarExamen.textBoxTiempo.
Referenced by UI.RealizarExamen.comenzarExamen().
habilitar()
void UI.RealizarExamen.habilitar () private
habilita elementos gráficos
Definition at line 132 of file RealizarExamen.cs.
        {
            lblSlash.Visible = true;
            lbTotalTiempo.Visible = true;
            label2.Visible = true;
            textBoxTiempo.Visible = true;
            rtEnunciado.Visible = true;
            radioR1.Visible = true;
            radioR2.Visible = true;
            radioR3.Visible = true;
            btnSiguiente.Visible = true;
            label3.Visible = true;
            lblNo.Visible = true;
            label6.Visible = true;
            lblTotalPreguntas.Visible = true;
        }
References UI.RealizarExamen.btnSiguiente, UI.RealizarExamen.label2, UI.RealizarExamen.label3, UI.RealizarExamen.label6, UI.RealizarExamen.lblNo, UI.RealizarExamen.lblSlash, UI.RealizarExamen.lblTotalPreguntas, UI.RealizarExamen.lbTotalTiempo, UI.RealizarExamen.radioR1, UI.RealizarExamen.radioR2, UI.RealizarExamen.radioR3, UI.RealizarExamen.rtEnunciado, and UI.RealizarExamen.textBoxTiempo.
Referenced by UI.RealizarExamen.comenzarExamen().
InitializeComponent()
void UI.RealizarExamen.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file RealizarExamen.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RealizarExamen));
            this.label5 = new System.Windows.Forms.Label();
            this.lbl1 = new System.Windows.Forms.Label();
            this.lblNombre = new System.Windows.Forms.Label();
            this.lblID = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.txtCodigo = new System.Windows.Forms.TextBox();
            this.btnRealizarExamen = new System.Windows.Forms.Button();
            this.gBValidacion = new System.Windows.Forms.GroupBox();
            this.btnSalir = new System.Windows.Forms.Button();
            this.gbExamen = new System.Windows.Forms.GroupBox();
            this.textBoxTiempo = new System.Windows.Forms.TextBox();
            this.lbTotalTiempo = new System.Windows.Forms.Label();
            this.lblSlash = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.lblTotalPreguntas = new System.Windows.Forms.Label();
            this.lblNo = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.lblTiempo = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.btnSiguiente = new System.Windows.Forms.Button();
            this.radioR3 = new System.Windows.Forms.RadioButton();
            this.radioR2 = new System.Windows.Forms.RadioButton();
            this.radioR1 = new System.Windows.Forms.RadioButton();
            this.rtEnunciado = new System.Windows.Forms.RichTextBox();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.tmr = new System.Windows.Forms.Timer(this.components);
            this.gBValidacion.SuspendLayout();
            this.gbExamen.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();
            //
            // label5
            //
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(6, 146);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(127, 20);
            this.label5.TabIndex = 18;
            this.label5.Text = "Identificación:";
            //
            // lbl1
            //
            this.lbl1.AutoSize = true;
            this.lbl1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl1.Location = new System.Drawing.Point(7, 60);
            this.lbl1.Name = "lbl1";
            this.lbl1.Size = new System.Drawing.Size(157, 18);
            this.lbl1.TabIndex = 16;
            this.lbl1.Text = "Nombre del Cliente:";
            //
            // lblNombre
            //
            this.lblNombre.AutoSize = true;
            this.lblNombre.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.Location = new System.Drawing.Point(803, 60);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(152, 20);
            this.lblNombre.TabIndex = 17;
            this.lblNombre.Text = "Nombre del Cliente";
            //
            // lblID
            //
            this.lblID.AutoSize = true;
            this.lblID.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblID.Location = new System.Drawing.Point(848, 146);
            this.lblID.Name = "lblID";
            this.lblID.Size = new System.Drawing.Size(107, 20);
            this.lblID.TabIndex = 19;
            this.lblID.Text = "ID del cliente";
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(7, 236);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(183, 18);
            this.label1.TabIndex = 20;
            this.label1.Text = "Código de Realización:";
            //
            // txtCodigo
            //
            this.txtCodigo.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCodigo.Location = new System.Drawing.Point(665, 236);
            this.txtCodigo.Name = "txtCodigo";
            this.txtCodigo.Size = new System.Drawing.Size(290, 27);
            this.txtCodigo.TabIndex = 21;
            //
            // btnRealizarExamen
            //
            this.btnRealizarExamen.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRealizarExamen.Location = new System.Drawing.Point(755, 310);
            this.btnRealizarExamen.Name = "btnRealizarExamen";
            this.btnRealizarExamen.Size = new System.Drawing.Size(200, 52);
            this.btnRealizarExamen.TabIndex = 22;
            this.btnRealizarExamen.Text = "Comenzar Examen";
            this.btnRealizarExamen.UseVisualStyleBackColor = true;
            this.btnRealizarExamen.Click += new System.EventHandler(this.btnRealizarExamen_Click);
            //
            // gBValidacion
            //
            this.gBValidacion.Controls.Add(this.btnSalir);
            this.gBValidacion.Controls.Add(this.lbl1);
            this.gBValidacion.Controls.Add(this.btnRealizarExamen);
            this.gBValidacion.Controls.Add(this.lblNombre);
            this.gBValidacion.Controls.Add(this.txtCodigo);
            this.gBValidacion.Controls.Add(this.label5);
            this.gBValidacion.Controls.Add(this.label1);
            this.gBValidacion.Controls.Add(this.lblID);
            this.gBValidacion.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gBValidacion.Location = new System.Drawing.Point(17, 278);
            this.gBValidacion.Name = "gBValidacion";
            this.gBValidacion.Size = new System.Drawing.Size(968, 368);
            this.gBValidacion.TabIndex = 23;
            this.gBValidacion.TabStop = false;
            this.gBValidacion.Text = "Ingrese su Código";
            //
            // btnSalir
            //
            this.btnSalir.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSalir.Location = new System.Drawing.Point(6, 310);
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.Size = new System.Drawing.Size(180, 52);
            this.btnSalir.TabIndex = 23;
            this.btnSalir.Text = "Salir";
            this.btnSalir.UseVisualStyleBackColor = true;
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            //
            // gbExamen
            //
            this.gbExamen.Controls.Add(this.textBoxTiempo);
            this.gbExamen.Controls.Add(this.lbTotalTiempo);
            this.gbExamen.Controls.Add(this.lblSlash);
            this.gbExamen.Controls.Add(this.label6);
            this.gbExamen.Controls.Add(this.lblTotalPreguntas);
            this.gbExamen.Controls.Add(this.lblNo);
            this.gbExamen.Controls.Add(this.label3);
            this.gbExamen.Controls.Add(this.lblTiempo);
            this.gbExamen.Controls.Add(this.gBValidacion);
            this.gbExamen.Controls.Add(this.label2);
            this.gbExamen.Controls.Add(this.btnSiguiente);
            this.gbExamen.Controls.Add(this.radioR3);
            this.gbExamen.Controls.Add(this.radioR2);
            this.gbExamen.Controls.Add(this.radioR1);
            this.gbExamen.Controls.Add(this.rtEnunciado);
            this.gbExamen.Controls.Add(this.pictureBox);
            this.gbExamen.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbExamen.Location = new System.Drawing.Point(12, 3);
            this.gbExamen.Name = "gbExamen";
            this.gbExamen.Size = new System.Drawing.Size(991, 657);
            this.gbExamen.TabIndex = 24;
            this.gbExamen.TabStop = false;
            //
            // textBoxTiempo
            //
            this.textBoxTiempo.Location = new System.Drawing.Point(117, 206);
            this.textBoxTiempo.Name = "textBoxTiempo";
            this.textBoxTiempo.ReadOnly = true;
            this.textBoxTiempo.Size = new System.Drawing.Size(100, 27);
            this.textBoxTiempo.TabIndex = 40;
            this.textBoxTiempo.Text = "00:00:00";
            this.textBoxTiempo.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.textBoxTiempo.Visible = false;
            //
            // lbTotalTiempo
            //
            this.lbTotalTiempo.AutoSize = true;
            this.lbTotalTiempo.Location = new System.Drawing.Point(243, 209);
            this.lbTotalTiempo.Name = "lbTotalTiempo";
            this.lbTotalTiempo.Size = new System.Drawing.Size(18, 20);
            this.lbTotalTiempo.TabIndex = 39;
            this.lbTotalTiempo.Text = "0";
            this.lbTotalTiempo.Visible = false;
            //
            // lblSlash
            //
            this.lblSlash.AutoSize = true;
            this.lblSlash.Location = new System.Drawing.Point(223, 208);
            this.lblSlash.Name = "lblSlash";
            this.lblSlash.Size = new System.Drawing.Size(14, 20);
            this.lblSlash.TabIndex = 38;
            this.lblSlash.Text = "/";
            this.lblSlash.Visible = false;
            //
            // label6
            //
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(908, 213);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(24, 18);
            this.label6.TabIndex = 35;
            this.label6.Text = "de";
            this.label6.Visible = false;
            //
            // lblTotalPreguntas
            //
            this.lblTotalPreguntas.AutoSize = true;
            this.lblTotalPreguntas.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalPreguntas.Location = new System.Drawing.Point(956, 213);
            this.lblTotalPreguntas.Name = "lblTotalPreguntas";
            this.lblTotalPreguntas.Size = new System.Drawing.Size(16, 18);
            this.lblTotalPreguntas.TabIndex = 34;
            this.lblTotalPreguntas.Text = "1";
            this.lblTotalPreguntas.Visible = false;
            //
            // lblNo
            //
            this.lblNo.AutoSize = true;
            this.lblNo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNo.Location = new System.Drawing.Point(870, 213);
            this.lblNo.Name = "lblNo";
            this.lblNo.Size = new System.Drawing.Size(16, 18);
            this.lblNo.TabIndex = 33;
            this.lblNo.Text = "1";
            this.lblNo.Visible = false;
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(769, 213);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(95, 18);
            this.label3.TabIndex = 32;
            this.label3.Text = "Pregunta No:";
            this.label3.Visible = false;
            //
            // lblTiempo
            //
            this.lblTiempo.AutoSize = true;
            this.lblTiempo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTiempo.Location = new System.Drawing.Point(114, 142);
            this.lblTiempo.Name = "lblTiempo";
            this.lblTiempo.Size = new System.Drawing.Size(16, 18);
            this.lblTiempo.TabIndex = 31;
            this.lblTiempo.Text = "0";
            this.lblTiempo.Visible = false;
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(20, 210);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(62, 18);
            this.label2.TabIndex = 30;
            this.label2.Text = "Tiempo:";
            this.label2.Visible = false;
            //
            // btnSiguiente
            //
            this.btnSiguiente.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSiguiente.Location = new System.Drawing.Point(803, 596);
            this.btnSiguiente.Name = "btnSiguiente";
            this.btnSiguiente.Size = new System.Drawing.Size(171, 50);
            this.btnSiguiente.TabIndex = 29;
            this.btnSiguiente.Text = "Siguiente";
            this.btnSiguiente.UseVisualStyleBackColor = true;
            this.btnSiguiente.Visible = false;
            this.btnSiguiente.Click += new System.EventHandler(this.btnSiguiente_Click);
            //
            // radioR3
            //
            this.radioR3.AutoSize = true;
            this.radioR3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.radioR3.Location = new System.Drawing.Point(28, 610);
            this.radioR3.Name = "radioR3";
            this.radioR3.Size = new System.Drawing.Size(81, 22);
            this.radioR3.TabIndex = 28;
            this.radioR3.TabStop = true;
            this.radioR3.Text = "radioR3";
            this.radioR3.UseVisualStyleBackColor = true;
            this.radioR3.Visible = false;
            //
            // radioR2
            //
            this.radioR2.AutoSize = true;
            this.radioR2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.radioR2.Location = new System.Drawing.Point(28, 504);
            this.radioR2.Name = "radioR2";
            this.radioR2.Size = new System.Drawing.Size(81, 22);
            this.radioR2.TabIndex = 27;
            this.radioR2.TabStop = true;
            this.radioR2.Text = "radioR2";
            this.radioR2.UseVisualStyleBackColor = true;
            this.radioR2.Visible = false;
            //
            // radioR1
            //
            this.radioR1.AutoSize = true;
            this.radioR1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.radioR1.Location = new System.Drawing.Point(28, 389);
            this.radioR1.Name = "radioR1";
            this.radioR1.Size = new System.Drawing.Size(81, 22);
            this.radioR1.TabIndex = 26;
            this.radioR1.TabStop = true;
            this.radioR1.Text = "radioR1";
            this.radioR1.UseVisualStyleBackColor = true;
            this.radioR1.Visible = false;
            //
            // rtEnunciado
            //
            this.rtEnunciado.Enabled = false;
            this.rtEnunciado.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtEnunciado.Location = new System.Drawing.Point(28, 254);
            this.rtEnunciado.Name = "rtEnunciado";
            this.rtEnunciado.ReadOnly = true;
            this.rtEnunciado.Size = new System.Drawing.Size(946, 113);
            this.rtEnunciado.TabIndex = 25;
            this.rtEnunciado.Text = "";
            this.rtEnunciado.Visible = false;
            //
            // pictureBox
            //
            this.pictureBox.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox.Image")));
            this.pictureBox.Location = new System.Drawing.Point(326, 37);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(331, 194);
            this.pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox.TabIndex = 24;
            this.pictureBox.TabStop = false;
            //
            // tmr
            //
            this.tmr.Interval = 1000;
            this.tmr.Tick += new System.EventHandler(this.tmr_Tick);
            //
            // RealizarExamen
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1020, 672);
            this.Controls.Add(this.gbExamen);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "RealizarExamen";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Realizar Examen";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.RealizarExamen_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.RealizarExamen_FormClosed);
            this.Load += new System.EventHandler(this.RealizarExamen_Load);
            this.gBValidacion.ResumeLayout(false);
            this.gBValidacion.PerformLayout();
            this.gbExamen.ResumeLayout(false);
            this.gbExamen.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
        }
References UI.RealizarExamen.btnRealizarExamen, UI.RealizarExamen.btnRealizarExamen_Click(), UI.RealizarExamen.btnSalir, UI.RealizarExamen.btnSalir_Click(), UI.RealizarExamen.btnSiguiente, UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.components, UI.RealizarExamen.gbExamen, UI.RealizarExamen.gBValidacion, UI.RealizarExamen.label1, UI.RealizarExamen.label2, UI.RealizarExamen.label3, UI.RealizarExamen.label5, UI.RealizarExamen.label6, UI.RealizarExamen.lbl1, UI.RealizarExamen.lblID, UI.RealizarExamen.lblNo, UI.RealizarExamen.lblNombre, UI.RealizarExamen.lblSlash, UI.RealizarExamen.lblTiempo, UI.RealizarExamen.lblTotalPreguntas, UI.RealizarExamen.lbTotalTiempo, UI.RealizarExamen.pictureBox, UI.RealizarExamen.radioR1, UI.RealizarExamen.radioR2, UI.RealizarExamen.radioR3, UI.RealizarExamen.RealizarExamen_FormClosed(), UI.RealizarExamen.RealizarExamen_FormClosing(), UI.RealizarExamen.RealizarExamen_Load(), UI.RealizarExamen.rtEnunciado, UI.RealizarExamen.textBoxTiempo, UI.RealizarExamen.tmr, UI.RealizarExamen.tmr_Tick(), and UI.RealizarExamen.txtCodigo.
Referenced by UI.RealizarExamen.RealizarExamen().
RealizarExamen_FormClosed()
void UI.RealizarExamen.RealizarExamen_FormClosed (object sender, FormClosedEventArgs e) private
Si ya se inició el examen y el usuario cierra la ventana, arroja la revisión del examen
Parameters
sender
e
Definition at line 296 of file RealizarExamen.cs.
        {
            if (cont==1)
            {
                RevisarExamen();
            }
        }
References UI.RealizarExamen.cont, and UI.RealizarExamen.RevisarExamen().
Referenced by UI.RealizarExamen.InitializeComponent().
RealizarExamen_FormClosing()
void UI.RealizarExamen.RealizarExamen_FormClosing (object sender, FormClosingEventArgs e) private
Antes de cerrar la aplicaión para los relojes para evitar posibles errores
Parameters
sender
e
Definition at line 344 of file RealizarExamen.cs.
        {
            try
            {
                if (cont == 1)
                {
                    tmr.Stop();
                    t.Stop();
                    Application.DoEvents();
                }
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en realización: " + er.Message);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.cont, UI.RealizarExamen.t, and UI.RealizarExamen.tmr.
Referenced by UI.RealizarExamen.InitializeComponent().
RealizarExamen_Load()
void UI.RealizarExamen.RealizarExamen_Load (object sender, EventArgs e) private
Carga los datos del cliente
Parameters
sender
e
Definition at line 45 of file RealizarExamen.cs.
        {
            lblNombre.Text = cliente.Nombre + " " + cliente.Apellido;
            lblID.Text = cliente.Id.ToString();
        }
References Capa.Entities.Cliente.Apellido, UI.RealizarExamen.cliente, Capa.Entities.Cliente.Id, UI.RealizarExamen.lblID, UI.RealizarExamen.lblNombre, and Capa.Entities.Cliente.Nombre.
Referenced by UI.RealizarExamen.InitializeComponent().
RevisarExamen()
void UI.RealizarExamen.RevisarExamen () private
Revisa el resultado final del examen, en caso de aprobado abre el reporte de certificado
Definition at line 182 of file RealizarExamen.cs.
        {
            _MyLogControlEventos.Info($"Prueba finalizada");
            MessageBox.Show($"La prueba a terminado, usted acertó {Total}/{ListaPreguntas.Count} preguntas!" +
                   $"\n Su calificación fue: " + (double)(((double)Total / (double)ListaPreguntas.Count)) * 100,
                   "Calificación",
                   MessageBoxButtons.OK, MessageBoxIcon.Information);
            if (Total >= ((ListaPreguntas.Count) * (examen.NotaMinima / 100)))
            {
                _MyLogControlEventos.Info($"Prueba aprobada");
                MessageBox.Show($"Usted aprobó el examen! Una vez de click en aceptar, espere a que se genere su certificado.", "Resultado", MessageBoxButtons.OK, MessageBoxIcon.Information);
                IntentoLN.MarcarIntentoExitoso(intento.IDIntento);
                var frm = new FrmCertificado(intento.IDIntento, cliente.Email);
                frm.ShowDialog();
                return;
            }
            else
            {
                _MyLogControlEventos.Info($"Prueba reprobada");
                MessageBox.Show($"Usted no aprobó el examen", "Resultado", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.cliente, Capa.Entities.Cliente.Email, UI.RealizarExamen.examen, Capa.Entities.Intento.IDIntento, UI.RealizarExamen.intento, UI.RealizarExamen.ListaPreguntas, Capa.BLL.IntentoLN.MarcarIntentoExitoso(), Capa.Entities.Examen.NotaMinima, and UI.RealizarExamen.Total.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.RealizarExamen_FormClosed(), and UI.RealizarExamen.tmr_Tick().
SiguientePregunta()
void UI.RealizarExamen.SiguientePregunta () private
Avanza a la siguiente pregunta del examen
Definition at line 152 of file RealizarExamen.cs.
        {
            NoPregunta++;
            Pregunta pregunta = ListaPreguntas[NoPregunta];
            this.rtEnunciado.Text = pregunta.Enunciado;
            this.radioR1.Text = pregunta.Respuesta1;
            this.radioR2.Text = pregunta.Respuesta2;
            this.radioR3.Text = pregunta.Respuesta3;
            this.pictureBox.Image = (Bitmap)((new ImageConverter()).ConvertFrom(pregunta.Imagen));
            this.radioR1.Checked = true;
        }
References Capa.Entities.Pregunta.Enunciado, Capa.Entities.Pregunta.Imagen, UI.RealizarExamen.ListaPreguntas, UI.RealizarExamen.NoPregunta, UI.RealizarExamen.pictureBox, UI.RealizarExamen.radioR1, UI.RealizarExamen.radioR2, UI.RealizarExamen.radioR3, Capa.Entities.Pregunta.Respuesta1, Capa.Entities.Pregunta.Respuesta2, Capa.Entities.Pregunta.Respuesta3, and UI.RealizarExamen.rtEnunciado.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), and UI.RealizarExamen.comenzarExamen().
tmr_Tick()
void UI.RealizarExamen.tmr_Tick (object sender, EventArgs e) private
Estos son los eventos que pasan cada que el reloj avanza
Parameters
sender
e
Definition at line 309 of file RealizarExamen.cs.
        {
            try
            {
                int value = int.Parse(this.lblTiempo.Text);
                if (value >= LimiteTiempo)
                {
                    t.Stop();
                    tmr.Stop();
                    btnSiguiente.Enabled = false;
                    MessageBox.Show($"Se acabó su tiempo", "Lo sentimos", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    _MyLogControlEventos.Info($"Tiempo de la prueba finalizado");
                    RevisarExamen();
                    cont++;
                    return;
                }
                value++;
                this.lblTiempo.Text = value.ToString();
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en realización: " + er.Message);
            }
        }
References UI.RealizarExamen._MyLogControlEventos, UI.RealizarExamen.btnSiguiente, UI.RealizarExamen.cont, UI.RealizarExamen.lblTiempo, UI.RealizarExamen.LimiteTiempo, UI.RealizarExamen.RevisarExamen(), UI.RealizarExamen.t, and UI.RealizarExamen.tmr.
Referenced by UI.RealizarExamen.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.RealizarExamen._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 18 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnRealizarExamen_Click(), UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.RealizarExamen_FormClosing(), UI.RealizarExamen.RevisarExamen(), and UI.RealizarExamen.tmr_Tick().
btnRealizarExamen
System.Windows.Forms.Button UI.RealizarExamen.btnRealizarExamen private
Definition at line 393 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent().
btnSalir
System.Windows.Forms.Button UI.RealizarExamen.btnSalir private
Definition at line 398 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent().
btnSiguiente
System.Windows.Forms.Button UI.RealizarExamen.btnSiguiente private
Definition at line 402 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.habilitar(), UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.tmr_Tick().
cliente
Cliente UI.RealizarExamen.cliente private
Definition at line 20 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnRealizarExamen_Click(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.RealizarExamen_Load(), and UI.RealizarExamen.RevisarExamen().
components
System.ComponentModel.IContainer UI.RealizarExamen.components = null private
Required designer variable.
Definition at line 9 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.Dispose(), and UI.RealizarExamen.InitializeComponent().
cont
int UI.RealizarExamen.cont = 0 private
Definition at line 23 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.RealizarExamen_FormClosed(), UI.RealizarExamen.RealizarExamen_FormClosing(), and UI.RealizarExamen.tmr_Tick().
examen
Examen UI.RealizarExamen.examen private
Definition at line 21 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), and UI.RealizarExamen.RevisarExamen().
gbExamen
System.Windows.Forms.GroupBox UI.RealizarExamen.gbExamen private
Definition at line 395 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), and UI.RealizarExamen.InitializeComponent().
gBValidacion
System.Windows.Forms.GroupBox UI.RealizarExamen.gBValidacion private
Definition at line 394 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), and UI.RealizarExamen.InitializeComponent().
h
int UI.RealizarExamen.h private
Definition at line 23 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.EventoTiempo().
intento
Intento UI.RealizarExamen.intento private
Definition at line 22 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), and UI.RealizarExamen.RevisarExamen().
label1
System.Windows.Forms.Label UI.RealizarExamen.label1 private
Definition at line 391 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent().
label2
System.Windows.Forms.Label UI.RealizarExamen.label2 private
Definition at line 401 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
label3
System.Windows.Forms.Label UI.RealizarExamen.label3 private
Definition at line 409 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
label5
System.Windows.Forms.Label UI.RealizarExamen.label5 private
Definition at line 387 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent().
label6
System.Windows.Forms.Label UI.RealizarExamen.label6 private
Definition at line 406 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
lbl1
System.Windows.Forms.Label UI.RealizarExamen.lbl1 private
Definition at line 388 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent().
lblID
System.Windows.Forms.Label UI.RealizarExamen.lblID private
Definition at line 390 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.RealizarExamen_Load().
lblNo
System.Windows.Forms.Label UI.RealizarExamen.lblNo private
Definition at line 408 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
lblNombre
System.Windows.Forms.Label UI.RealizarExamen.lblNombre private
Definition at line 389 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.RealizarExamen_Load().
lblSlash
System.Windows.Forms.Label UI.RealizarExamen.lblSlash private
Definition at line 410 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
lblTiempo
System.Windows.Forms.Label UI.RealizarExamen.lblTiempo private
Definition at line 400 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.tmr_Tick().
lblTotalPreguntas
System.Windows.Forms.Label UI.RealizarExamen.lblTotalPreguntas private
Definition at line 407 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
lbTotalTiempo
System.Windows.Forms.Label UI.RealizarExamen.lbTotalTiempo private
Definition at line 411 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
LimiteTiempo
int UI.RealizarExamen.LimiteTiempo private
Definition at line 29 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.comenzarExamen(), and UI.RealizarExamen.tmr_Tick().
ListaPreguntas
List<Pregunta> UI.RealizarExamen.ListaPreguntas private
Definition at line 26 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.Calificar(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.RevisarExamen(), and UI.RealizarExamen.SiguientePregunta().
logicaExamenes
IExamenLN UI.RealizarExamen.logicaExamenes = new ExamenLN() private
Definition at line 31 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.comenzarExamen().
logicaPreguntas
IPreguntaLN UI.RealizarExamen.logicaPreguntas = new PreguntaLN() private
Definition at line 32 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.comenzarExamen().
m
int UI.RealizarExamen.m private
Definition at line 23 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.EventoTiempo().
NoPregunta
int UI.RealizarExamen.NoPregunta = -1 private
Definition at line 27 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.Calificar(), and UI.RealizarExamen.SiguientePregunta().
pictureBox
System.Windows.Forms.PictureBox UI.RealizarExamen.pictureBox private
Definition at line 397 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.SiguientePregunta().
radioR1
System.Windows.Forms.RadioButton UI.RealizarExamen.radioR1 private
Definition at line 405 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.Calificar(), UI.RealizarExamen.habilitar(), UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.SiguientePregunta().
radioR2
System.Windows.Forms.RadioButton UI.RealizarExamen.radioR2 private
Definition at line 404 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.Calificar(), UI.RealizarExamen.habilitar(), UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.SiguientePregunta().
radioR3
System.Windows.Forms.RadioButton UI.RealizarExamen.radioR3 private
Definition at line 403 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.Calificar(), UI.RealizarExamen.habilitar(), UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.SiguientePregunta().
rtEnunciado
System.Windows.Forms.RichTextBox UI.RealizarExamen.rtEnunciado private
Definition at line 399 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.habilitar(), UI.RealizarExamen.InitializeComponent(), and UI.RealizarExamen.SiguientePregunta().
s
int UI.RealizarExamen.s private
Definition at line 23 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.EventoTiempo().
t
System.Timers.Timer UI.RealizarExamen.t private
Definition at line 24 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.RealizarExamen_FormClosing(), and UI.RealizarExamen.tmr_Tick().
textBoxTiempo
System.Windows.Forms.TextBox UI.RealizarExamen.textBoxTiempo private
Definition at line 412 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.EventoTiempo(), UI.RealizarExamen.habilitar(), and UI.RealizarExamen.InitializeComponent().
tmr
System.Windows.Forms.Timer UI.RealizarExamen.tmr private
Definition at line 396 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.btnSiguiente_Click(), UI.RealizarExamen.comenzarExamen(), UI.RealizarExamen.InitializeComponent(), UI.RealizarExamen.RealizarExamen_FormClosing(), and UI.RealizarExamen.tmr_Tick().
Total
int UI.RealizarExamen.Total = 0 private
Definition at line 28 of file RealizarExamen.cs.
Referenced by UI.RealizarExamen.Calificar(), and UI.RealizarExamen.RevisarExamen().
txtCodigo
System.Windows.Forms.TextBox UI.RealizarExamen.txtCodigo private
Definition at line 392 of file RealizarExamen.Designer.cs.
Referenced by UI.RealizarExamen.btnRealizarExamen_Click(), and UI.RealizarExamen.InitializeComponent().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Procesos/RealizarExamen.cs
118710756/DbaCreator/UI/Procesos/RealizarExamen.Designer.cs