DBACreator: Capa.BLL.IntentoLN Class Reference
Capa.BLL.IntentoLN Class Reference
Static Public Member Functions
static void Insertar (Intento i)
Inserta un intento en la base de datos
static int ObtenerNumeroDeIntentoActual ()
Usado para saber que numero de intento va y asignar un id
static void MarcarIntentoExitoso (int idIntento)
Si el cliente gana el examen se marca como exitoso
Detailed Description
Definition at line 11 of file IntentoLN.cs.
Member Function Documentation
Insertar()
static void Capa.BLL.IntentoLN.Insertar (Intento i) static
Inserta un intento en la base de datos
Parameters
i Intento del que extraerá los datos
Definition at line 17 of file IntentoLN.cs.
        {
            IntentoDB.Insertar(i);
        }
References Capa.DAL.IntentoDB.Insertar().
Referenced by UI.RealizarExamen.comenzarExamen().
MarcarIntentoExitoso()
static void Capa.BLL.IntentoLN.MarcarIntentoExitoso (int idIntento) static
Si el cliente gana el examen se marca como exitoso
Parameters
idIntento ID a buscar
Definition at line 35 of file IntentoLN.cs.
        {
            IntentoDB.MarcarIntentoExitoso(idIntento);
        }
References Capa.DAL.IntentoDB.MarcarIntentoExitoso().
Referenced by UI.RealizarExamen.RevisarExamen().
ObtenerNumeroDeIntentoActual()
static int Capa.BLL.IntentoLN.ObtenerNumeroDeIntentoActual () static
Usado para saber que numero de intento va y asignar un id
Returns
Retorna el id máximo en la tabla + 1
Definition at line 26 of file IntentoLN.cs.
        {
            return IntentoDB.ObtenerNumeroDeIntentoActual();
        }
References Capa.DAL.IntentoDB.ObtenerNumeroDeIntentoActual().
Referenced by UI.RealizarExamen.comenzarExamen().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/IntentoLN.cs