DBACreator: UI.Reportes.FrmReporteGrafico Class Reference
UI.Reportes.FrmReporteGrafico Class Reference
Public Member Functions
FrmReporteGrafico ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void FrmReporteGrafico_Load (object sender, EventArgs e)
Llena el gráfico con los datos
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
System.Windows.Forms.BindingSource PA_ReporteGraficoBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_ReporteGraficoTableAdapter PA_ReporteGraficoTableAdapter
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 13 of file FrmReporteGrafico.cs.
Constructor & Destructor Documentation
FrmReporteGrafico()
UI.Reportes.FrmReporteGrafico.FrmReporteGrafico ()
Definition at line 16 of file FrmReporteGrafico.cs.
        {
            InitializeComponent();
        }
References UI.Reportes.FrmReporteGrafico.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.FrmReporteGrafico.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file FrmReporteGrafico.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.FrmReporteGrafico.components.
FrmReporteGrafico_Load()
void UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load (object sender, EventArgs e) private
Llena el gráfico con los datos
Parameters
sender
e
Definition at line 26 of file FrmReporteGrafico.cs.
        {
            try
            {
                this.PA_ReporteGraficoTableAdapter.Fill(this.DataSetReportes.PA_ReporteGrafico);
                this.reportViewer1.RefreshReport();
                _MyLogControlEventos.Info("Datos encontrados");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte gráfico: " + er.Message);
            }
        }
References UI.Reportes.FrmReporteGrafico._MyLogControlEventos, UI.Reportes.DataSetReportes.PA_ReporteGrafico, UI.Reportes.FrmReporteGrafico.PA_ReporteGraficoTableAdapter, and UI.Reportes.FrmReporteGrafico.reportViewer1.
Referenced by UI.Reportes.FrmReporteGrafico.InitializeComponent().
InitializeComponent()
void UI.Reportes.FrmReporteGrafico.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file FrmReporteGrafico.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.PA_ReporteGraficoBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_ReporteGraficoTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_ReporteGraficoTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteGraficoBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.SuspendLayout();
            //
            // PA_ReporteGraficoBindingSource
            //
            this.PA_ReporteGraficoBindingSource.DataMember = "PA_ReporteGrafico";
            this.PA_ReporteGraficoBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // reportViewer1
            //
            this.reportViewer1.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetGrafico";
            reportDataSource1.Value = this.PA_ReporteGraficoBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteGrafico.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 0);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(1123, 614);
            this.reportViewer1.TabIndex = 0;
            //
            // PA_ReporteGraficoTableAdapter
            //
            this.PA_ReporteGraficoTableAdapter.ClearBeforeFill = true;
            //
            // FrmReporteGrafico
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1123, 614);
            this.Controls.Add(this.reportViewer1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmReporteGrafico";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Reporte Gráfico";
            this.Load += new System.EventHandler(this.FrmReporteGrafico_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteGraficoBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.ResumeLayout(false);
        }
References UI.Reportes.FrmReporteGrafico.components, UI.Reportes.FrmReporteGrafico.DataSetReportes, UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load(), UI.Reportes.FrmReporteGrafico.PA_ReporteGraficoBindingSource, UI.Reportes.FrmReporteGrafico.PA_ReporteGraficoTableAdapter, UI.Reportes.FrmReporteGrafico.reportViewer1, and UI.Reportes.DataSetReportes.SchemaSerializationMode.
Referenced by UI.Reportes.FrmReporteGrafico.FrmReporteGrafico().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.FrmReporteGrafico._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 15 of file FrmReporteGrafico.cs.
Referenced by UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load().
components
System.ComponentModel.IContainer UI.Reportes.FrmReporteGrafico.components = null private
Required designer variable.
Definition at line 9 of file FrmReporteGrafico.Designer.cs.
Referenced by UI.Reportes.FrmReporteGrafico.Dispose(), and UI.Reportes.FrmReporteGrafico.InitializeComponent().
DataSetReportes
DataSetReportes UI.Reportes.FrmReporteGrafico.DataSetReportes private
Definition at line 90 of file FrmReporteGrafico.Designer.cs.
Referenced by UI.Reportes.FrmReporteGrafico.InitializeComponent().
PA_ReporteGraficoBindingSource
System.Windows.Forms.BindingSource UI.Reportes.FrmReporteGrafico.PA_ReporteGraficoBindingSource private
Definition at line 89 of file FrmReporteGrafico.Designer.cs.
Referenced by UI.Reportes.FrmReporteGrafico.InitializeComponent().
PA_ReporteGraficoTableAdapter
DataSetReportesTableAdapters.PA_ReporteGraficoTableAdapter UI.Reportes.FrmReporteGrafico.PA_ReporteGraficoTableAdapter private
Definition at line 91 of file FrmReporteGrafico.Designer.cs.
Referenced by UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load(), and UI.Reportes.FrmReporteGrafico.InitializeComponent().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.FrmReporteGrafico.reportViewer1 private
Definition at line 88 of file FrmReporteGrafico.Designer.cs.
Referenced by UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load(), and UI.Reportes.FrmReporteGrafico.InitializeComponent().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/FrmReporteGrafico.cs
118710756/DbaCreator/UI/Reportes/FrmReporteGrafico.Designer.cs