DBACreator: UI.InicioSesion Class Reference
UI.InicioSesion Class Reference
Public Member Functions
InicioSesion ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void chkContrasenna_CheckedChanged (object sender, EventArgs e)
Sirve para ver la contraseña digitada
void btnRegistrarse_Click (object sender, EventArgs e)
Abre la ventana de registro
void btnLogIn_Click (object sender, EventArgs e)
Verifica los datos y si todo es correcto inicia la aplicación
void btnSalir_Click (object sender, EventArgs e)
Cierra la aplicación
void txtContrasenna_KeyDown (object sender, KeyEventArgs e)
Para hacer login con enter
void InicioSesion_Load (object sender, EventArgs e)
void txtID_KeyDown (object sender, KeyEventArgs e)
Para escribir la contraseña
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox Logo
System.Windows.Forms.Label label1
System.Windows.Forms.Button btnRegistrarse
System.Windows.Forms.Button btnLogIn
System.Windows.Forms.Button btnSalir
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox txtContrasenna
System.Windows.Forms.CheckBox chkContrasenna
System.Windows.Forms.TextBox txtID
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file InicioSesion.cs.
Constructor & Destructor Documentation
InicioSesion()
UI.InicioSesion.InicioSesion ()
Definition at line 20 of file InicioSesion.cs.
        {
            InitializeComponent();
        }
References UI.InicioSesion.InitializeComponent().
Member Function Documentation
btnLogIn_Click()
void UI.InicioSesion.btnLogIn_Click (object sender, EventArgs e) private
Verifica los datos y si todo es correcto inicia la aplicación
Parameters
sender
e
Definition at line 55 of file InicioSesion.cs.
        {
            IClienteLN ln = new ClienteLN();
            if (string.IsNullOrEmpty(txtID.Text))
            {
                MessageBox.Show("Debe ingresar su cédula", "Error", MessageBoxButtons.OK);
                return;
            }
            try
            {
                int id = Convert.ToInt32(txtID.Text);
                string contrasenna = txtContrasenna.Text;
                Cliente cLogin = ln.ObtenerPorID(id);
                if (cLogin == null)
                {
                    MessageBox.Show("Usuario no encontrado :(", "Error", MessageBoxButtons.OK);
                    return;
                }
                if (cLogin.Id==id)
                {
                    if (cLogin.Contrasenna==contrasenna)
                    {
                        _MyLogControlEventos.Info("Se inició sesión");
                        this.Hide();
                        var frm = new Menu();
                        frm.cliente = cLogin;
                        frm.Closed += (s, args) => this.Close();
                        frm.Show();
                    } else
                    {
                        MessageBox.Show("Contraseña Incorrecta", "Error", MessageBoxButtons.OK);
                        return;
                    }
                }
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error al tratar de iniciar sesión: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.InicioSesion._MyLogControlEventos, Capa.Entities.Cliente.Contrasenna, Capa.Entities.Cliente.Id, Capa.BLL.IClienteLN.ObtenerPorID(), UI.InicioSesion.txtContrasenna, and UI.InicioSesion.txtID.
Referenced by UI.InicioSesion.InitializeComponent().
btnRegistrarse_Click()
void UI.InicioSesion.btnRegistrarse_Click (object sender, EventArgs e) private
Abre la ventana de registro
Parameters
sender
e
Definition at line 43 of file InicioSesion.cs.
        {
            var frm = new Registro();
            frm.ShowDialog();
        }
Referenced by UI.InicioSesion.InitializeComponent().
btnSalir_Click()
void UI.InicioSesion.btnSalir_Click (object sender, EventArgs e) private
Cierra la aplicación
Parameters
sender
e
Definition at line 106 of file InicioSesion.cs.
        {
            Close();
        }
Referenced by UI.InicioSesion.InitializeComponent().
chkContrasenna_CheckedChanged()
void UI.InicioSesion.chkContrasenna_CheckedChanged (object sender, EventArgs e) private
Sirve para ver la contraseña digitada
Parameters
sender
e
Definition at line 30 of file InicioSesion.cs.
        {
            if (this.chkContrasenna.Checked)
                txtContrasenna.UseSystemPasswordChar = false;
            else
                txtContrasenna.UseSystemPasswordChar = true;
        }
References UI.InicioSesion.chkContrasenna, and UI.InicioSesion.txtContrasenna.
Referenced by UI.InicioSesion.InitializeComponent().
Dispose()
override void UI.InicioSesion.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file InicioSesion.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.InicioSesion.components.
InicioSesion_Load()
void UI.InicioSesion.InicioSesion_Load (object sender, EventArgs e) private
Definition at line 124 of file InicioSesion.cs.
        {
            _MyLogControlEventos.InfoFormat("Abierta la aplicación");
        }
References UI.InicioSesion._MyLogControlEventos.
Referenced by UI.InicioSesion.InitializeComponent().
InitializeComponent()
void UI.InicioSesion.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file InicioSesion.Designer.cs.
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(InicioSesion));
            this.Logo = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.btnRegistrarse = new System.Windows.Forms.Button();
            this.btnLogIn = new System.Windows.Forms.Button();
            this.btnSalir = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.txtContrasenna = new System.Windows.Forms.TextBox();
            this.chkContrasenna = new System.Windows.Forms.CheckBox();
            this.txtID = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).BeginInit();
            this.SuspendLayout();
            //
            // Logo
            //
            this.Logo.Image = ((System.Drawing.Image)(resources.GetObject("Logo.Image")));
            this.Logo.Location = new System.Drawing.Point(147, 12);
            this.Logo.Name = "Logo";
            this.Logo.Size = new System.Drawing.Size(239, 172);
            this.Logo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.Logo.TabIndex = 0;
            this.Logo.TabStop = false;
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Consolas", 16.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(185, 206);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(165, 33);
            this.label1.TabIndex = 1;
            this.label1.Text = "Bienvenido";
            //
            // btnRegistrarse
            //
            this.btnRegistrarse.Location = new System.Drawing.Point(13, 494);
            this.btnRegistrarse.Name = "btnRegistrarse";
            this.btnRegistrarse.Size = new System.Drawing.Size(149, 54);
            this.btnRegistrarse.TabIndex = 2;
            this.btnRegistrarse.Text = "Registrarse";
            this.btnRegistrarse.UseVisualStyleBackColor = true;
            this.btnRegistrarse.Click += new System.EventHandler(this.btnRegistrarse_Click);
            //
            // btnLogIn
            //
            this.btnLogIn.Location = new System.Drawing.Point(191, 494);
            this.btnLogIn.Name = "btnLogIn";
            this.btnLogIn.Size = new System.Drawing.Size(159, 54);
            this.btnLogIn.TabIndex = 3;
            this.btnLogIn.Text = "Iniciar Sesión";
            this.btnLogIn.UseVisualStyleBackColor = true;
            this.btnLogIn.Click += new System.EventHandler(this.btnLogIn_Click);
            //
            // btnSalir
            //
            this.btnSalir.Location = new System.Drawing.Point(380, 494);
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.Size = new System.Drawing.Size(149, 54);
            this.btnSalir.TabIndex = 4;
            this.btnSalir.Text = "Salir";
            this.btnSalir.UseVisualStyleBackColor = true;
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(12, 278);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(274, 23);
            this.label2.TabIndex = 5;
            this.label2.Text = "Identificación (Cédula):";
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(12, 358);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(131, 23);
            this.label3.TabIndex = 7;
            this.label3.Text = "Contraseña:";
            //
            // txtContrasenna
            //
            this.txtContrasenna.Location = new System.Drawing.Point(13, 393);
            this.txtContrasenna.Name = "txtContrasenna";
            this.txtContrasenna.Size = new System.Drawing.Size(516, 22);
            this.txtContrasenna.TabIndex = 8;
            this.txtContrasenna.UseSystemPasswordChar = true;
            this.txtContrasenna.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtContrasenna_KeyDown);
            //
            // chkContrasenna
            //
            this.chkContrasenna.AutoSize = true;
            this.chkContrasenna.Location = new System.Drawing.Point(13, 441);
            this.chkContrasenna.Name = "chkContrasenna";
            this.chkContrasenna.Size = new System.Drawing.Size(155, 21);
            this.chkContrasenna.TabIndex = 9;
            this.chkContrasenna.Text = "Mostrar Contraseña";
            this.chkContrasenna.UseVisualStyleBackColor = true;
            this.chkContrasenna.CheckedChanged += new System.EventHandler(this.chkContrasenna_CheckedChanged);
            //
            // txtID
            //
            this.txtID.Location = new System.Drawing.Point(16, 315);
            this.txtID.Name = "txtID";
            this.txtID.Size = new System.Drawing.Size(513, 22);
            this.txtID.TabIndex = 10;
            this.txtID.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtID_KeyDown);
            //
            // InicioSesion
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(541, 560);
            this.Controls.Add(this.txtID);
            this.Controls.Add(this.chkContrasenna);
            this.Controls.Add(this.txtContrasenna);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.btnSalir);
            this.Controls.Add(this.btnLogIn);
            this.Controls.Add(this.btnRegistrarse);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.Logo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "InicioSesion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Inicio de Sesión";
            this.Load += new System.EventHandler(this.InicioSesion_Load);
            ((System.ComponentModel.ISupportInitialize)(this.Logo)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.InicioSesion.btnLogIn, UI.InicioSesion.btnLogIn_Click(), UI.InicioSesion.btnRegistrarse, UI.InicioSesion.btnRegistrarse_Click(), UI.InicioSesion.btnSalir, UI.InicioSesion.btnSalir_Click(), UI.InicioSesion.chkContrasenna, UI.InicioSesion.chkContrasenna_CheckedChanged(), UI.InicioSesion.InicioSesion_Load(), UI.InicioSesion.label1, UI.InicioSesion.label2, UI.InicioSesion.label3, UI.InicioSesion.Logo, UI.InicioSesion.txtContrasenna, UI.InicioSesion.txtContrasenna_KeyDown(), UI.InicioSesion.txtID, and UI.InicioSesion.txtID_KeyDown().
Referenced by UI.InicioSesion.InicioSesion().
txtContrasenna_KeyDown()
void UI.InicioSesion.txtContrasenna_KeyDown (object sender, KeyEventArgs e) private
Para hacer login con enter
Parameters
sender
e
Definition at line 116 of file InicioSesion.cs.
        {
            if (e.KeyCode == Keys.Enter)
            {
                btnLogIn.PerformClick();
            }
        }
References UI.InicioSesion.btnLogIn.
Referenced by UI.InicioSesion.InitializeComponent().
txtID_KeyDown()
void UI.InicioSesion.txtID_KeyDown (object sender, KeyEventArgs e) private
Para escribir la contraseña
Parameters
sender
e
Definition at line 134 of file InicioSesion.cs.
        {
            if (e.KeyCode == Keys.Enter)
            {
                txtContrasenna.Focus();
            }
        }
References UI.InicioSesion.txtContrasenna.
Referenced by UI.InicioSesion.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.InicioSesion._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 19 of file InicioSesion.cs.
Referenced by UI.InicioSesion.btnLogIn_Click(), and UI.InicioSesion.InicioSesion_Load().
btnLogIn
System.Windows.Forms.Button UI.InicioSesion.btnLogIn private
Definition at line 177 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent(), and UI.InicioSesion.txtContrasenna_KeyDown().
btnRegistrarse
System.Windows.Forms.Button UI.InicioSesion.btnRegistrarse private
Definition at line 176 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
btnSalir
System.Windows.Forms.Button UI.InicioSesion.btnSalir private
Definition at line 178 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
chkContrasenna
System.Windows.Forms.CheckBox UI.InicioSesion.chkContrasenna private
Definition at line 182 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.chkContrasenna_CheckedChanged(), and UI.InicioSesion.InitializeComponent().
components
System.ComponentModel.IContainer UI.InicioSesion.components = null private
Required designer variable.
Definition at line 9 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.Dispose().
label1
System.Windows.Forms.Label UI.InicioSesion.label1 private
Definition at line 175 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
label2
System.Windows.Forms.Label UI.InicioSesion.label2 private
Definition at line 179 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
label3
System.Windows.Forms.Label UI.InicioSesion.label3 private
Definition at line 180 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
Logo
System.Windows.Forms.PictureBox UI.InicioSesion.Logo private
Definition at line 174 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.InitializeComponent().
txtContrasenna
System.Windows.Forms.TextBox UI.InicioSesion.txtContrasenna private
Definition at line 181 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.btnLogIn_Click(), UI.InicioSesion.chkContrasenna_CheckedChanged(), UI.InicioSesion.InitializeComponent(), and UI.InicioSesion.txtID_KeyDown().
txtID
System.Windows.Forms.TextBox UI.InicioSesion.txtID private
Definition at line 183 of file InicioSesion.Designer.cs.
Referenced by UI.InicioSesion.btnLogIn_Click(), and UI.InicioSesion.InitializeComponent().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Seguridad/InicioSesion.cs
118710756/DbaCreator/UI/Seguridad/InicioSesion.Designer.cs