DBACreator: UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable Class Reference
UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
PA_ReporteGraficoDataTable ()
void AddPA_ReporteGraficoRow (PA_ReporteGraficoRow row)
PA_ReporteGraficoRow AddPA_ReporteGraficoRow (string Descripcion, int Cantidad)
override global::System.Data.DataTable Clone ()
PA_ReporteGraficoRow NewPA_ReporteGraficoRow ()
void RemovePA_ReporteGraficoRow (PA_ReporteGraficoRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
PA_ReporteGraficoDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
PA_ReporteGraficoDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn DescripcionColumn [get]
global::System.Data.DataColumn CantidadColumn [get]
int Count [get]
PA_ReporteGraficoRow this[int index] [get]
Events
PA_ReporteGraficoRowChangeEventHandler PA_ReporteGraficoRowChanging
PA_ReporteGraficoRowChangeEventHandler PA_ReporteGraficoRowChanged
PA_ReporteGraficoRowChangeEventHandler PA_ReporteGraficoRowDeleting
PA_ReporteGraficoRowChangeEventHandler PA_ReporteGraficoRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnDescripcion
global::System.Data.DataColumn columnCantidad
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 3129 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
PA_ReporteGraficoDataTable() [1/3]
UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable ()
Definition at line 3137 of file DataSetReportes.Designer.cs.
{
                this.TableName = "PA_ReporteGrafico";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitClass().
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.Clone(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.CreateInstance().
PA_ReporteGraficoDataTable() [2/3]
UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable (global::System.Data.DataTable table) package
Definition at line 3146 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
PA_ReporteGraficoDataTable() [3/3]
UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 3163 of file DataSetReportes.Designer.cs.
                                                                                                                                                                         :
                    base(info, context) {
                this.InitVars();
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars().
Member Function Documentation
AddPA_ReporteGraficoRow() [1/2]
void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.AddPA_ReporteGraficoRow (PA_ReporteGraficoRow row)
Definition at line 3215 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
AddPA_ReporteGraficoRow() [2/2]
PA_ReporteGraficoRow UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.AddPA_ReporteGraficoRow (string Descripcion, int Cantidad)
Definition at line 3221 of file DataSetReportes.Designer.cs.
{
                PA_ReporteGraficoRow rowPA_ReporteGraficoRow = ((PA_ReporteGraficoRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Descripcion,
                        Cantidad};
                rowPA_ReporteGraficoRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPA_ReporteGraficoRow);
                return rowPA_ReporteGraficoRow;
            }
Clone()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.Clone ()
Definition at line 3233 of file DataSetReportes.Designer.cs.
{
                PA_ReporteGraficoDataTable cln = ((PA_ReporteGraficoDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable().
CreateInstance()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.CreateInstance () protected
Definition at line 3241 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteGraficoDataTable();
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable().
GetRowType()
override global.System.Type UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.GetRowType () protected
Definition at line 3278 of file DataSetReportes.Designer.cs.
{
                return typeof(PA_ReporteGraficoRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 3326 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PA_ReporteGraficoDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitClass () private
Definition at line 3254 of file DataSetReportes.Designer.cs.
{
                this.columnDescripcion = new global::System.Data.DataColumn("Descripcion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcion);
                this.columnCantidad = new global::System.Data.DataColumn("Cantidad", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCantidad);
                this.columnDescripcion.AllowDBNull = false;
                this.columnDescripcion.MaxLength = 50;
                this.columnCantidad.ReadOnly = true;
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnCantidad, and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnDescripcion.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable().
InitVars()
void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars () package
Definition at line 3247 of file DataSetReportes.Designer.cs.
{
                this.columnDescripcion = base.Columns["Descripcion"];
                this.columnCantidad = base.Columns["Cantidad"];
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnCantidad, and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnDescripcion.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.Clone(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoDataTable().
NewPA_ReporteGraficoRow()
PA_ReporteGraficoRow UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.NewPA_ReporteGraficoRow ()
Definition at line 3266 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteGraficoRow)(this.NewRow()));
            }
NewRowFromBuilder()
override global.System.Data.DataRow UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 3272 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteGraficoRow(builder);
            }
OnRowChanged()
override void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3284 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.PA_ReporteGraficoRowChanged != null)) {
                    this.PA_ReporteGraficoRowChanged(this, new PA_ReporteGraficoRowChangeEvent(((PA_ReporteGraficoRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowChanged.
OnRowChanging()
override void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3293 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.PA_ReporteGraficoRowChanging != null)) {
                    this.PA_ReporteGraficoRowChanging(this, new PA_ReporteGraficoRowChangeEvent(((PA_ReporteGraficoRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowChanging.
OnRowDeleted()
override void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3302 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.PA_ReporteGraficoRowDeleted != null)) {
                    this.PA_ReporteGraficoRowDeleted(this, new PA_ReporteGraficoRowChangeEvent(((PA_ReporteGraficoRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowDeleted.
OnRowDeleting()
override void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3311 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.PA_ReporteGraficoRowDeleting != null)) {
                    this.PA_ReporteGraficoRowDeleting(this, new PA_ReporteGraficoRowChangeEvent(((PA_ReporteGraficoRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowDeleting.
RemovePA_ReporteGraficoRow()
void UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.RemovePA_ReporteGraficoRow (PA_ReporteGraficoRow row)
Definition at line 3320 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnCantidad
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnCantidad private
Definition at line 3133 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars().
columnDescripcion
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.columnDescripcion private
Definition at line 3131 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars().
Property Documentation
CantidadColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.CantidadColumn get
Definition at line 3178 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnCantidad;
                }
            }
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoRow.IsCantidadNull(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoRow.SetCantidadNull().
Count
int UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.Count get
Definition at line 3187 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
DescripcionColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.DescripcionColumn get
Definition at line 3170 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnDescripcion;
                }
            }
this[int index]
PA_ReporteGraficoRow UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.this[int index] get
Definition at line 3195 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((PA_ReporteGraficoRow)(this.Rows[index]));
                }
            }
Event Documentation
PA_ReporteGraficoRowChanged
PA_ReporteGraficoRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowChanged
Definition at line 3205 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowChanged().
PA_ReporteGraficoRowChanging
PA_ReporteGraficoRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowChanging
Definition at line 3202 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowChanging().
PA_ReporteGraficoRowDeleted
PA_ReporteGraficoRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowDeleted
Definition at line 3211 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowDeleted().
PA_ReporteGraficoRowDeleting
PA_ReporteGraficoRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.PA_ReporteGraficoRowDeleting
Definition at line 3208 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs