DBACreator: Capa.DAL.ClienteDB Class Reference
Capa.DAL.ClienteDB Class Reference
Static Public Member Functions
static void AgregarCliente (Cliente c)
Método que guarda el cliente en la base de datos, solo en caso de que no encuentre un dato con ese ID
static Cliente SeleccionarPorId (int id)
Retorna de la tabla Cliente el dato con el ID buscado
static Cliente SeleccionarPorTelefono (string telefono)
Retorna de la tabla Cliente el dato con el telefono buscado
static Cliente SeleccionarPorEmail (string email)
Retorna de la tabla Cliente el dato con el email buscado
static List< Cliente > ObtenerClientes ()
Método para obtener todos los datos de la tabla Cliente
static void Delete (string id)
Borra el dato de la tabla con el ID enviado
static void Update (Cliente c, int idViejo)
actualiza el dato de la tabla con el ID enviado
Detailed Description
Definition at line 12 of file ClienteDB.cs.
Member Function Documentation
AgregarCliente()
static void Capa.DAL.ClienteDB.AgregarCliente (Cliente c) static
Método que guarda el cliente en la base de datos, solo en caso de que no encuentre un dato con ese ID
Parameters
c Cliente del cuál extraerá los datos
Definition at line 18 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarCliente";
                comando.Parameters.AddWithValue("@id", c.Id);
                comando.Parameters.AddWithValue("@idtipo", c.IdTipo);
                comando.Parameters.AddWithValue("@nombre", c.Nombre);
                comando.Parameters.AddWithValue("@apellido", c.Apellido);
                comando.Parameters.AddWithValue("@email", c.Email);
                comando.Parameters.AddWithValue("@foto", c.Imagen);
                comando.Parameters.AddWithValue("@fechaN", c.FechaNacimiento);
                comando.Parameters.AddWithValue("@telefono", c.Telefono);
                comando.Parameters.AddWithValue("@pais", c.Pais);
                comando.Parameters.AddWithValue("@contrasenna", c.Contrasenna);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteNonQuery(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.Guardar().
Delete()
static void Capa.DAL.ClienteDB.Delete (string id) static
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Definition at line 188 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_BorrarCliente";
                comando.Parameters.AddWithValue("@id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.ClienteLN.Borrar().
ObtenerClientes()
static List< Cliente > Capa.DAL.ClienteDB.ObtenerClientes () static
Método para obtener todos los datos de la tabla Cliente
Returns
Retorna una lista con todos los datos de la tabla Cliente
Definition at line 152 of file ClienteDB.cs.
        {
            List<Cliente> lista = new List<Cliente>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarClientes";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cliente c = new Cliente();
                    c.Id = (int)dr["IDCliente"];
                    c.IdTipo = (int)dr["IDTipo"];
                    c.Nombre = dr["Nombre"].ToString();
                    c.Apellido = dr["Apellido"].ToString();
                    c.Email = dr["Email"].ToString();
                    c.Imagen = (Byte[])dr["Fotografia"];
                    c.FechaNacimiento = Convert.ToDateTime(dr["FechaNacimiento"]);
                    c.Telefono = dr["Telefono"].ToString();
                    c.Pais = dr["PaisNacimiento"].ToString();
                    //c.Activo = Convert.ToBoolean(dr["Activo"]);
                    c.Contrasenna = dr["Contrasenna"].ToString();
                    lista.Add(c);
                }
            }
            return lista;
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteDataSet(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.ObtenerTodos().
SeleccionarPorEmail()
static Cliente Capa.DAL.ClienteDB.SeleccionarPorEmail (string email) static
Retorna de la tabla Cliente el dato con el email buscado
Parameters
email email a buscar
Returns
Definition at line 118 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarClientePorEmail";
                comando.Parameters.AddWithValue("@email", email);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cliente c = new Cliente();
                    c.Id = (int)dr["IDCliente"];
                    c.IdTipo = (int)dr["IDTipo"];
                    c.Nombre = dr["Nombre"].ToString();
                    c.Apellido = dr["Apellido"].ToString();
                    c.Email = dr["Email"].ToString();
                    c.Imagen = (Byte[])dr["Fotografia"];
                    c.FechaNacimiento = Convert.ToDateTime(dr["FechaNacimiento"]);
                    c.Telefono = dr["Telefono"].ToString();
                    c.Pais = dr["PaisNacimiento"].ToString();
                    c.Contrasenna = dr["Contrasenna"].ToString();
                    return c;
                }
            }
            return null;
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteDataSet(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.ObtenerPorCorreo().
SeleccionarPorId()
static Cliente Capa.DAL.ClienteDB.SeleccionarPorId (int id) static
Retorna de la tabla Cliente el dato con el ID buscado
Parameters
id ID a buscar
Returns
Definition at line 46 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarClientePorID";
                comando.Parameters.AddWithValue("@Id", id);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cliente c = new Cliente();
                    c.Id = (int)dr["IDCliente"];
                    c.IdTipo = (int)dr["IDTipo"];
                    c.Nombre = dr["Nombre"].ToString();
                    c.Apellido = dr["Apellido"].ToString();
                    c.Email = dr["Email"].ToString();
                    c.Imagen = (Byte[])dr["Fotografia"];
                    c.FechaNacimiento = Convert.ToDateTime(dr["FechaNacimiento"]);
                    c.Telefono = dr["Telefono"].ToString();
                    c.Pais = dr["PaisNacimiento"].ToString();
                    c.Contrasenna = dr["Contrasenna"].ToString();
                    return c;
                }
            }
            return null;
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteDataSet(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.Guardar(), and Capa.BLL.ClienteLN.ObtenerPorID().
SeleccionarPorTelefono()
static Cliente Capa.DAL.ClienteDB.SeleccionarPorTelefono (string telefono) static
Retorna de la tabla Cliente el dato con el telefono buscado
Parameters
telefono telefono a buscar
Returns
Definition at line 82 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarClientePorTelefono";
                comando.Parameters.AddWithValue("@telefono", telefono);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Cliente c = new Cliente();
                    c.Id = (int)dr["IDCliente"];
                    c.IdTipo = (int)dr["IDTipo"];
                    c.Nombre = dr["Nombre"].ToString();
                    c.Apellido = dr["Apellido"].ToString();
                    c.Email = dr["Email"].ToString();
                    c.Imagen = (Byte[])dr["Fotografia"];
                    c.FechaNacimiento = Convert.ToDateTime(dr["FechaNacimiento"]);
                    c.Telefono = dr["Telefono"].ToString();
                    c.Pais = dr["PaisNacimiento"].ToString();
                    //c.Activo = Convert.ToBoolean(dr["Activo"]);
                    c.Contrasenna = dr["Contrasenna"].ToString();
                    return c;
                }
            }
            return null;
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteDataSet(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.ObtenerPorTelefono().
Update()
static void Capa.DAL.ClienteDB.Update (Cliente c, int idViejo) static
actualiza el dato de la tabla con el ID enviado
Parameters
c Cliente del cual extrae los datos
idViejo ID a buscar
Definition at line 205 of file ClienteDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_ActualizarCliente";
                comando.Parameters.AddWithValue("@idViejo", idViejo);
                comando.Parameters.AddWithValue("@id", c.Id);
                comando.Parameters.AddWithValue("@idtipo", c.IdTipo);
                comando.Parameters.AddWithValue("@nombre", c.Nombre);
                comando.Parameters.AddWithValue("@apellido", c.Apellido);
                comando.Parameters.AddWithValue("@email", c.Email);
                comando.Parameters.AddWithValue("@foto", c.Imagen);
                comando.Parameters.AddWithValue("@fechaN", c.FechaNacimiento);
                comando.Parameters.AddWithValue("@telefono", c.Telefono);
                comando.Parameters.AddWithValue("@pais", c.Pais);
                comando.Parameters.AddWithValue("@contrasenna", c.Contrasenna);
                db.ExecuteNonQuery(comando);
            }
        }
References Capa.Entities.Cliente.Apellido, Capa.Entities.Cliente.Contrasenna, FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Cliente.Email, IDataBase.ExecuteNonQuery(), Capa.Entities.Cliente.FechaNacimiento, Capa.Entities.Cliente.Id, Capa.Entities.Cliente.IdTipo, Capa.Entities.Cliente.Imagen, Capa.Entities.Cliente.Nombre, Capa.Entities.Cliente.Pais, and Capa.Entities.Cliente.Telefono.
Referenced by Capa.BLL.ClienteLN.Actualizar().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/ClienteDB.cs