DBACreator: Capa.DAL.TarjetaDB Class Reference
Capa.DAL.TarjetaDB Class Reference
Static Public Member Functions
static List< Tarjeta > ObtenerTodos ()
Sirve para ver todas las tarjetas
Detailed Description
Definition at line 12 of file TarjetaDB.cs.
Member Function Documentation
ObtenerTodos()
static List< Tarjeta > Capa.DAL.TarjetaDB.ObtenerTodos () static
Sirve para ver todas las tarjetas
Returns
Retorna una lista con todas las tarjetas disponibles
Definition at line 18 of file TarjetaDB.cs.
        {
            List<Tarjeta> lista = new List<Tarjeta>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarTarjetas";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Tarjeta t = new Tarjeta();
                    t.ID = (int)dr["IDTarjeta"];
                    t.Nombre = dr["Nombre"].ToString();
                    lista.Add(t);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), Capa.Entities.Tarjeta.ID, and Capa.Entities.Tarjeta.Nombre.
Referenced by Capa.BLL.TarjetaLN.ObtenerTodos().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/TarjetaDB.cs