DBACreator: UI.Reportes.FrmReporteExamenes Class Reference
UI.Reportes.FrmReporteExamenes Class Reference
Public Member Functions
FrmReporteExamenes ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void FrmReporteExamenes_Load (object sender, EventArgs e)
void toolStripBtnBuscar_Click (object sender, EventArgs e)
Usa un stored procedure para buscar según lo escrito en el textbox y carga el reporte
void toolStripBtnSalir_Click (object sender, EventArgs e)
cierra la ventana
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
System.Windows.Forms.BindingSource PA_ReporteExamenesRealizadosBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_ReporteExamenesRealizadosTableAdapter PA_ReporteExamenesRealizadosTableAdapter
System.Windows.Forms.ToolStripButton toolStripBtnBuscar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.ToolStripTextBox toolStripTxtFiltro
System.Windows.Forms.ToolStrip toolStrip1
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 15 of file FrmReporteExamenes.cs.
Constructor & Destructor Documentation
FrmReporteExamenes()
UI.Reportes.FrmReporteExamenes.FrmReporteExamenes ()
Definition at line 18 of file FrmReporteExamenes.cs.
        {
            InitializeComponent();
        }
References UI.Reportes.FrmReporteExamenes.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.FrmReporteExamenes.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file FrmReporteExamenes.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.FrmReporteExamenes.components.
FrmReporteExamenes_Load()
void UI.Reportes.FrmReporteExamenes.FrmReporteExamenes_Load (object sender, EventArgs e) private
Definition at line 23 of file FrmReporteExamenes.cs.
        {
            toolStripBtnBuscar.PerformClick();
        }
References UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar.
InitializeComponent()
void UI.Reportes.FrmReporteExamenes.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file FrmReporteExamenes.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmReporteExamenes));
            this.PA_ReporteExamenesRealizadosBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_ReporteExamenesRealizadosTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_ReporteExamenesRealizadosTableAdapter();
            this.toolStripBtnBuscar = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.toolStripTxtFiltro = new System.Windows.Forms.ToolStripTextBox();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteExamenesRealizadosBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            //
            // PA_ReporteExamenesRealizadosBindingSource
            //
            this.PA_ReporteExamenesRealizadosBindingSource.DataMember = "PA_ReporteExamenesRealizados";
            this.PA_ReporteExamenesRealizadosBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // reportViewer1
            //
            this.reportViewer1.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetExamenesRealizados";
            reportDataSource1.Value = this.PA_ReporteExamenesRealizadosBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteExamenesRealizados.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 55);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(996, 510);
            this.reportViewer1.TabIndex = 5;
            //
            // PA_ReporteExamenesRealizadosTableAdapter
            //
            this.PA_ReporteExamenesRealizadosTableAdapter.ClearBeforeFill = true;
            //
            // toolStripBtnBuscar
            //
            this.toolStripBtnBuscar.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnBuscar.Image")));
            this.toolStripBtnBuscar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnBuscar.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnBuscar.Name = "toolStripBtnBuscar";
            this.toolStripBtnBuscar.Size = new System.Drawing.Size(282, 52);
            this.toolStripBtnBuscar.Text = "Buscar por Cliente (Identificación)";
            this.toolStripBtnBuscar.Click += new System.EventHandler(this.toolStripBtnBuscar_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // toolStripTxtFiltro
            //
            this.toolStripTxtFiltro.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.toolStripTxtFiltro.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.toolStripTxtFiltro.Name = "toolStripTxtFiltro";
            this.toolStripTxtFiltro.Size = new System.Drawing.Size(133, 55);
            //
            // toolStrip1
            //
            this.toolStrip1.BackColor = System.Drawing.SystemColors.Control;
            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnBuscar,
            this.toolStripTxtFiltro,
            this.toolStripBtnSalir});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.Size = new System.Drawing.Size(996, 55);
            this.toolStrip1.TabIndex = 4;
            this.toolStrip1.Text = "toolStrip1";
            //
            // FrmReporteExamenes
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(996, 565);
            this.Controls.Add(this.reportViewer1);
            this.Controls.Add(this.toolStrip1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmReporteExamenes";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Reporte de Examenes";
            this.Load += new System.EventHandler(this.FrmReporteExamenes_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_ReporteExamenesRealizadosBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Reportes.FrmReporteExamenes.components, UI.Reportes.FrmReporteExamenes.DataSetReportes, UI.Reportes.FrmReporteExamenes.PA_ReporteExamenesRealizadosBindingSource, UI.Reportes.FrmReporteExamenes.PA_ReporteExamenesRealizadosTableAdapter, UI.Reportes.FrmReporteExamenes.reportViewer1, UI.Reportes.DataSetReportes.SchemaSerializationMode, UI.Reportes.FrmReporteExamenes.toolStrip1, UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar, UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click(), UI.Reportes.FrmReporteExamenes.toolStripBtnSalir, UI.Reportes.FrmReporteExamenes.toolStripBtnSalir_Click(), and UI.Reportes.FrmReporteExamenes.toolStripTxtFiltro.
Referenced by UI.Reportes.FrmReporteExamenes.FrmReporteExamenes().
toolStripBtnBuscar_Click()
void UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click (object sender, EventArgs e) private
Usa un stored procedure para buscar según lo escrito en el textbox y carga el reporte
Parameters
sender
e
Definition at line 33 of file FrmReporteExamenes.cs.
        {
            string filtro = "";
            try
            {
                filtro = "%" + this.toolStripTxtFiltro.Text + "%";
                this.PA_ReporteExamenesRealizadosTableAdapter.Fill(this.DataSetReportes.PA_ReporteExamenesRealizados, filtro);
                this.reportViewer1.RefreshReport();
                _MyLogControlEventos.Info("Datos encontrados");
            }
            catch(Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de examenes realizados: " + er.Message);
            }
        }
References UI.Reportes.FrmReporteExamenes._MyLogControlEventos, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizados, UI.Reportes.FrmReporteExamenes.PA_ReporteExamenesRealizadosTableAdapter, UI.Reportes.FrmReporteExamenes.reportViewer1, and UI.Reportes.FrmReporteExamenes.toolStripTxtFiltro.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
toolStripBtnSalir_Click()
void UI.Reportes.FrmReporteExamenes.toolStripBtnSalir_Click (object sender, EventArgs e) private
cierra la ventana
Parameters
sender
e
Definition at line 56 of file FrmReporteExamenes.cs.
        {
            this.Close();
        }
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.FrmReporteExamenes._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 17 of file FrmReporteExamenes.cs.
Referenced by UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click().
components
System.ComponentModel.IContainer UI.Reportes.FrmReporteExamenes.components = null private
Required designer variable.
Definition at line 9 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.Dispose(), and UI.Reportes.FrmReporteExamenes.InitializeComponent().
DataSetReportes
DataSetReportes UI.Reportes.FrmReporteExamenes.DataSetReportes private
Definition at line 140 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
PA_ReporteExamenesRealizadosBindingSource
System.Windows.Forms.BindingSource UI.Reportes.FrmReporteExamenes.PA_ReporteExamenesRealizadosBindingSource private
Definition at line 139 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
PA_ReporteExamenesRealizadosTableAdapter
DataSetReportesTableAdapters.PA_ReporteExamenesRealizadosTableAdapter UI.Reportes.FrmReporteExamenes.PA_ReporteExamenesRealizadosTableAdapter private
Definition at line 141 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent(), and UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.FrmReporteExamenes.reportViewer1 private
Definition at line 138 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent(), and UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click().
toolStrip1
System.Windows.Forms.ToolStrip UI.Reportes.FrmReporteExamenes.toolStrip1 private
Definition at line 145 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
toolStripBtnBuscar
System.Windows.Forms.ToolStripButton UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar private
Definition at line 142 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.FrmReporteExamenes_Load(), and UI.Reportes.FrmReporteExamenes.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.Reportes.FrmReporteExamenes.toolStripBtnSalir private
Definition at line 143 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent().
toolStripTxtFiltro
System.Windows.Forms.ToolStripTextBox UI.Reportes.FrmReporteExamenes.toolStripTxtFiltro private
Definition at line 144 of file FrmReporteExamenes.Designer.cs.
Referenced by UI.Reportes.FrmReporteExamenes.InitializeComponent(), and UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/FrmReporteExamenes.cs
118710756/DbaCreator/UI/Reportes/FrmReporteExamenes.Designer.cs