DBACreator: Capa.BLL.PreguntaLN Class Reference
Capa.BLL.PreguntaLN Class Reference
Public Member Functions
List< Pregunta > SeleccionarPorExamen (int idExamen)
Método para ver las preguntas de un examen
void Guardar (Pregunta p)
Guarda una pregunta en su tabla de la base de datos
Pregunta ObtenerPorID (int id)
Sirve para buscar por ID una pregunta en específico
void Borrar (int id)
Borra la pregunta cuyo id sea igual al parámetro
List< Pregunta > SeleccionarPorExamen (int idExamen)
void Guardar (Pregunta p)
Pregunta ObtenerPorID (int id)
void Borrar (int id)
Detailed Description
Definition at line 11 of file PreguntaLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.PreguntaLN.Borrar (int id)
Borra la pregunta cuyo id sea igual al parámetro
Parameters
id Id de pregunta a consultar
Implements Capa.BLL.IPreguntaLN.
Definition at line 51 of file PreguntaLN.cs.
        {
            PreguntaDB.Borrar(id);
        }
References Capa.DAL.PreguntaDB.Borrar().
Guardar()
void Capa.BLL.PreguntaLN.Guardar (Pregunta p)
Guarda una pregunta en su tabla de la base de datos
Parameters
p Objeto del que extrae los datos
Implements Capa.BLL.IPreguntaLN.
Definition at line 27 of file PreguntaLN.cs.
        {
            if (ObtenerPorID(p.ID) == null)
            {
                PreguntaDB.Agregar(p);
            }
            else
            {
                PreguntaDB.Actualizar(p);
            }
        }
References Capa.DAL.PreguntaDB.Actualizar(), Capa.DAL.PreguntaDB.Agregar(), Capa.Entities.Pregunta.ID, and Capa.BLL.PreguntaLN.ObtenerPorID().
ObtenerPorID()
Pregunta Capa.BLL.PreguntaLN.ObtenerPorID (int id)
Sirve para buscar por ID una pregunta en específico
Parameters
id Pregunta a consultar
Returns
Retorna la pregunta cuyo Id sea igual al parámetro
Implements Capa.BLL.IPreguntaLN.
Definition at line 43 of file PreguntaLN.cs.
        {
            return PreguntaDB.SeleccionarPorId(id);
        }
References Capa.DAL.PreguntaDB.SeleccionarPorId().
Referenced by Capa.BLL.PreguntaLN.Guardar().
SeleccionarPorExamen()
List< Pregunta > Capa.BLL.PreguntaLN.SeleccionarPorExamen (int idExamen)
Método para ver las preguntas de un examen
Parameters
idExamen Examen a consultar
Returns
Retorna una lista de preguntas asignada a un Id de Examen
Implements Capa.BLL.IPreguntaLN.
Definition at line 18 of file PreguntaLN.cs.
        {
            return PreguntaDB.SeleccionarPorExamen(idExamen);
        }
References Capa.DAL.PreguntaDB.SeleccionarPorExamen().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/PreguntaLN.cs