DBACreator: UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable Class Reference
UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
PA_ReporteExamenesRealizadosDataTable ()
void AddPA_ReporteExamenesRealizadosRow (PA_ReporteExamenesRealizadosRow row)
PA_ReporteExamenesRealizadosRow AddPA_ReporteExamenesRealizadosRow (int IDIntento, int IDCliente, string Nombre, string Apellido, string Titulo, bool Exitoso)
override global::System.Data.DataTable Clone ()
PA_ReporteExamenesRealizadosRow NewPA_ReporteExamenesRealizadosRow ()
void RemovePA_ReporteExamenesRealizadosRow (PA_ReporteExamenesRealizadosRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
PA_ReporteExamenesRealizadosDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
PA_ReporteExamenesRealizadosDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn IDIntentoColumn [get]
global::System.Data.DataColumn IDClienteColumn [get]
global::System.Data.DataColumn NombreColumn [get]
global::System.Data.DataColumn ApellidoColumn [get]
global::System.Data.DataColumn TituloColumn [get]
global::System.Data.DataColumn ExitosoColumn [get]
int Count [get]
PA_ReporteExamenesRealizadosRow this[int index] [get]
Events
PA_ReporteExamenesRealizadosRowChangeEventHandler PA_ReporteExamenesRealizadosRowChanging
PA_ReporteExamenesRealizadosRowChangeEventHandler PA_ReporteExamenesRealizadosRowChanged
PA_ReporteExamenesRealizadosRowChangeEventHandler PA_ReporteExamenesRealizadosRowDeleting
PA_ReporteExamenesRealizadosRowChangeEventHandler PA_ReporteExamenesRealizadosRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnIDIntento
global::System.Data.DataColumn columnIDCliente
global::System.Data.DataColumn columnNombre
global::System.Data.DataColumn columnApellido
global::System.Data.DataColumn columnTitulo
global::System.Data.DataColumn columnExitoso
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2041 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
PA_ReporteExamenesRealizadosDataTable() [1/3]
UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable ()
Definition at line 2057 of file DataSetReportes.Designer.cs.
{
                this.TableName = "PA_ReporteExamenesRealizados";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass().
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.Clone(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.CreateInstance().
PA_ReporteExamenesRealizadosDataTable() [2/3]
UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable (global::System.Data.DataTable table) package
Definition at line 2066 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
PA_ReporteExamenesRealizadosDataTable() [3/3]
UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 2083 of file DataSetReportes.Designer.cs.
                                                                                                                                                                                    :
                    base(info, context) {
                this.InitVars();
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
Member Function Documentation
AddPA_ReporteExamenesRealizadosRow() [1/2]
PA_ReporteExamenesRealizadosRow UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.AddPA_ReporteExamenesRealizadosRow (int IDIntento, int IDCliente, string Nombre, string Apellido, string Titulo, bool Exitoso)
Definition at line 2173 of file DataSetReportes.Designer.cs.
{
                PA_ReporteExamenesRealizadosRow rowPA_ReporteExamenesRealizadosRow = ((PA_ReporteExamenesRealizadosRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IDIntento,
                        IDCliente,
                        Nombre,
                        Apellido,
                        Titulo,
                        Exitoso};
                rowPA_ReporteExamenesRealizadosRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPA_ReporteExamenesRealizadosRow);
                return rowPA_ReporteExamenesRealizadosRow;
            }
AddPA_ReporteExamenesRealizadosRow() [2/2]
void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.AddPA_ReporteExamenesRealizadosRow (PA_ReporteExamenesRealizadosRow row)
Definition at line 2167 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
Clone()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.Clone ()
Definition at line 2189 of file DataSetReportes.Designer.cs.
{
                PA_ReporteExamenesRealizadosDataTable cln = ((PA_ReporteExamenesRealizadosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable().
CreateInstance()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.CreateInstance () protected
Definition at line 2197 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteExamenesRealizadosDataTable();
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable().
GetRowType()
override global.System.Type UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.GetRowType () protected
Definition at line 2250 of file DataSetReportes.Designer.cs.
{
                return typeof(PA_ReporteExamenesRealizadosRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 2298 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PA_ReporteExamenesRealizadosDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass () private
Definition at line 2214 of file DataSetReportes.Designer.cs.
{
                this.columnIDIntento = new global::System.Data.DataColumn("IDIntento", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDIntento);
                this.columnIDCliente = new global::System.Data.DataColumn("IDCliente", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDCliente);
                this.columnNombre = new global::System.Data.DataColumn("Nombre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNombre);
                this.columnApellido = new global::System.Data.DataColumn("Apellido", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnApellido);
                this.columnTitulo = new global::System.Data.DataColumn("Titulo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTitulo);
                this.columnExitoso = new global::System.Data.DataColumn("Exitoso", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnExitoso);
                this.columnIDIntento.AllowDBNull = false;
                this.columnIDCliente.AllowDBNull = false;
                this.columnNombre.AllowDBNull = false;
                this.columnNombre.MaxLength = 50;
                this.columnApellido.AllowDBNull = false;
                this.columnApellido.MaxLength = 50;
                this.columnTitulo.MaxLength = 50;
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnExitoso, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDCliente, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDIntento, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnNombre, and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnTitulo.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable().
InitVars()
void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars () package
Definition at line 2203 of file DataSetReportes.Designer.cs.
{
                this.columnIDIntento = base.Columns["IDIntento"];
                this.columnIDCliente = base.Columns["IDCliente"];
                this.columnNombre = base.Columns["Nombre"];
                this.columnApellido = base.Columns["Apellido"];
                this.columnTitulo = base.Columns["Titulo"];
                this.columnExitoso = base.Columns["Exitoso"];
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnExitoso, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDCliente, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDIntento, UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnNombre, and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnTitulo.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.Clone(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosDataTable().
NewPA_ReporteExamenesRealizadosRow()
PA_ReporteExamenesRealizadosRow UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.NewPA_ReporteExamenesRealizadosRow ()
Definition at line 2238 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteExamenesRealizadosRow)(this.NewRow()));
            }
NewRowFromBuilder()
override global.System.Data.DataRow UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 2244 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteExamenesRealizadosRow(builder);
            }
OnRowChanged()
override void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 2256 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.PA_ReporteExamenesRealizadosRowChanged != null)) {
                    this.PA_ReporteExamenesRealizadosRowChanged(this, new PA_ReporteExamenesRealizadosRowChangeEvent(((PA_ReporteExamenesRealizadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowChanged.
OnRowChanging()
override void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 2265 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.PA_ReporteExamenesRealizadosRowChanging != null)) {
                    this.PA_ReporteExamenesRealizadosRowChanging(this, new PA_ReporteExamenesRealizadosRowChangeEvent(((PA_ReporteExamenesRealizadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowChanging.
OnRowDeleted()
override void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 2274 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.PA_ReporteExamenesRealizadosRowDeleted != null)) {
                    this.PA_ReporteExamenesRealizadosRowDeleted(this, new PA_ReporteExamenesRealizadosRowChangeEvent(((PA_ReporteExamenesRealizadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowDeleted.
OnRowDeleting()
override void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 2283 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.PA_ReporteExamenesRealizadosRowDeleting != null)) {
                    this.PA_ReporteExamenesRealizadosRowDeleting(this, new PA_ReporteExamenesRealizadosRowChangeEvent(((PA_ReporteExamenesRealizadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowDeleting.
RemovePA_ReporteExamenesRealizadosRow()
void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.RemovePA_ReporteExamenesRealizadosRow (PA_ReporteExamenesRealizadosRow row)
Definition at line 2292 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnApellido
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnApellido private
Definition at line 2049 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
columnExitoso
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnExitoso private
Definition at line 2053 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
columnIDCliente
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDCliente private
Definition at line 2045 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
columnIDIntento
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnIDIntento private
Definition at line 2043 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
columnNombre
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnNombre private
Definition at line 2047 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
columnTitulo
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.columnTitulo private
Definition at line 2051 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars().
Property Documentation
ApellidoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.ApellidoColumn get
Definition at line 2114 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnApellido;
                }
            }
Count
int UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.Count get
Definition at line 2139 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
ExitosoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.ExitosoColumn get
Definition at line 2130 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnExitoso;
                }
            }
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosRow.IsExitosoNull(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosRow.SetExitosoNull().
IDClienteColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.IDClienteColumn get
Definition at line 2098 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDCliente;
                }
            }
IDIntentoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.IDIntentoColumn get
Definition at line 2090 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDIntento;
                }
            }
NombreColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.NombreColumn get
Definition at line 2106 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnNombre;
                }
            }
this[int index]
PA_ReporteExamenesRealizadosRow UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.this[int index] get
Definition at line 2147 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((PA_ReporteExamenesRealizadosRow)(this.Rows[index]));
                }
            }
TituloColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.TituloColumn get
Definition at line 2122 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnTitulo;
                }
            }
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosRow.IsTituloNull(), and UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosRow.SetTituloNull().
Event Documentation
PA_ReporteExamenesRealizadosRowChanged
PA_ReporteExamenesRealizadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowChanged
Definition at line 2157 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowChanged().
PA_ReporteExamenesRealizadosRowChanging
PA_ReporteExamenesRealizadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowChanging
Definition at line 2154 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowChanging().
PA_ReporteExamenesRealizadosRowDeleted
PA_ReporteExamenesRealizadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowDeleted
Definition at line 2163 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowDeleted().
PA_ReporteExamenesRealizadosRowDeleting
PA_ReporteExamenesRealizadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.PA_ReporteExamenesRealizadosRowDeleting
Definition at line 2160 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs