DBACreator: UI.Registro Class Reference
UI.Registro Class Reference
Public Member Functions
Registro ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void chkContrasenna_CheckedChanged (object sender, EventArgs e)
Para ver contraseñas
void btnImagen_Click (object sender, EventArgs e)
Para seleccionar una imagen
void btnRegistrar_Click (object sender, EventArgs e)
Valida los datos y si todo es correcto guarda el nuevo cliente en la bd
byte[] imagenBytes ()
Convierte la imagen a bytes
void Limpiar ()
Limpia los objetos gráficos
void Registro_Load (object sender, EventArgs e)
Llena el combo países
void button1_Click (object sender, EventArgs e)
Cierra la ventana
void Registro_FormClosed (object sender, FormClosedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
string rutaImagen = ""
IClienteLN logica = new ClienteLN()
Cliente c
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.CheckBox chkContrasenna
System.Windows.Forms.TextBox txtContrasenna
System.Windows.Forms.Label label3
System.Windows.Forms.Label label2
System.Windows.Forms.Label label1
System.Windows.Forms.Label label4
System.Windows.Forms.MaskedTextBox mskTelefono
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox txtNombre
System.Windows.Forms.TextBox txtApellido
System.Windows.Forms.Label label6
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox txtmail
System.Windows.Forms.Label label8
System.Windows.Forms.DateTimePicker dateTimePicker
System.Windows.Forms.TextBox textValidarC
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.ComboBox cmbPais
System.Windows.Forms.Button button1
System.Windows.Forms.Button btnRegistrar
System.Windows.Forms.Button btnImagen
System.Windows.Forms.Label label11
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.TextBox txtID
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file Registro.cs.
Constructor & Destructor Documentation
Registro()
UI.Registro.Registro ()
Definition at line 25 of file Registro.cs.
        {
            InitializeComponent();
        }
References UI.Registro.InitializeComponent().
Member Function Documentation
btnImagen_Click()
void UI.Registro.btnImagen_Click (object sender, EventArgs e) private
Para seleccionar una imagen
Parameters
sender
e
Definition at line 54 of file Registro.cs.
        {
            OpenFileDialog selectImage = new OpenFileDialog();
            selectImage.Filter = " png files(*.png)|*.png|jpg files(*.jpg)|*.jpg|All files(*.*)|*.*";
            if (selectImage.ShowDialog() == DialogResult.OK)
            {
                rutaImagen = selectImage.FileName.ToString();
                pictureBox.ImageLocation = rutaImagen;
            }
        }
References UI.Registro.pictureBox, and UI.Registro.rutaImagen.
Referenced by UI.Registro.InitializeComponent().
btnRegistrar_Click()
void UI.Registro.btnRegistrar_Click (object sender, EventArgs e) private
Valida los datos y si todo es correcto guarda el nuevo cliente en la bd
Parameters
sender
e
Definition at line 71 of file Registro.cs.
        {
            try
            {
                Cliente clienteExistente = logica.ObtenerPorID(Convert.ToInt32(txtID.Text));
                if (clienteExistente != null)
                {
                    MessageBox.Show("Usuario ya registrado");
                    return;
                }
                clienteExistente = logica.ObtenerPorTelefono(mskTelefono.Text);
                if (clienteExistente != null)
                {
                    MessageBox.Show("Telefono ya registrado");
                    return;
                }
                clienteExistente = logica.ObtenerPorCorreo(txtmail.Text.ToLower());
                if (clienteExistente != null)
                {
                    MessageBox.Show("Correo ya registrado");
                    return;
                }
                if (Convert.ToInt32(txtID.Text) < 100000000)
                {
                    MessageBox.Show("Cédula no válida");
                    return;
                }
                if (!mskTelefono.MaskFull)
                {
                    MessageBox.Show("Debe digitar un telefono");
                    return;
                }
                if (txtNombre.Text == "")
                {
                    MessageBox.Show("Debe digitar un nombre");
                    return;
                }
                if (txtApellido.Text == "")
                {
                    MessageBox.Show("Debe digitar su apellido o apellidos");
                    return;
                }
                if (!Regex.IsMatch(txtmail.Text, "^[\\w-]+(\\.[\\w-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"))
                {
                    MessageBox.Show("Correo no válido");
                    return;
                }
                if (cmbPais.SelectedItem == null)
                {
                    MessageBox.Show("Seleccione un país");
                    return;
                }
                if (txtContrasenna.Text == "")
                {
                    MessageBox.Show("Inserte una contraseña");
                    return;
                }
                if (textValidarC.Text == "")
                {
                    MessageBox.Show("Valide su contraseña");
                    return;
                }
                if (txtContrasenna.Text != textValidarC.Text)
                {
                    MessageBox.Show("Sus contraseñas no coinciden");
                    return;
                }
                if (this.pictureBox.Image == null)
                {
                    MessageBox.Show("Debe insertar una imagen");
                    return;
                }
                c = new Cliente()
                {
                    Id = Convert.ToInt32(txtID.Text.Trim()),
                    IdTipo = 2,
                    Nombre = txtNombre.Text,
                    Apellido = txtApellido.Text,
                    Email = txtmail.Text.ToLower(),
                    Imagen = imagenBytes(),
                    FechaNacimiento = this.dateTimePicker.Value,
                    Telefono = mskTelefono.Text,
                    Pais = cmbPais.SelectedItem.ToString(),
                    Contrasenna = txtContrasenna.Text
                };
                logica.Guardar(c);
                _MyLogControlEventos.Info("Se creó un usuario nuevo satisfactoriamente");
                MessageBox.Show("Cliente satisfactoriamente registrado", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
                Limpiar();
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error al tratar de registrarse: " + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.Registro._MyLogControlEventos, UI.Registro.c, UI.Registro.cmbPais, UI.Registro.dateTimePicker, Capa.BLL.IClienteLN.Guardar(), UI.Registro.imagenBytes(), UI.Registro.Limpiar(), UI.Registro.logica, UI.Registro.mskTelefono, Capa.BLL.IClienteLN.ObtenerPorCorreo(), Capa.BLL.IClienteLN.ObtenerPorID(), Capa.BLL.IClienteLN.ObtenerPorTelefono(), UI.Registro.pictureBox, UI.Registro.textValidarC, UI.Registro.txtApellido, UI.Registro.txtContrasenna, UI.Registro.txtID, UI.Registro.txtmail, and UI.Registro.txtNombre.
Referenced by UI.Registro.InitializeComponent().
button1_Click()
void UI.Registro.button1_Click (object sender, EventArgs e) private
Cierra la ventana
Parameters
sender
e
Definition at line 228 of file Registro.cs.
        {
            this.Close();
        }
Referenced by UI.Registro.InitializeComponent().
chkContrasenna_CheckedChanged()
void UI.Registro.chkContrasenna_CheckedChanged (object sender, EventArgs e) private
Para ver contraseñas
Parameters
sender
e
Definition at line 35 of file Registro.cs.
        {
            if (this.chkContrasenna.Checked)
            {
                txtContrasenna.UseSystemPasswordChar = false;
                textValidarC.UseSystemPasswordChar = false;
            }
            else
            {
                txtContrasenna.UseSystemPasswordChar = true;
                textValidarC.UseSystemPasswordChar = true;
            }
        }
References UI.Registro.chkContrasenna, UI.Registro.textValidarC, and UI.Registro.txtContrasenna.
Referenced by UI.Registro.InitializeComponent().
Dispose()
override void UI.Registro.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file Registro.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Registro.components.
imagenBytes()
byte[] UI.Registro.imagenBytes () private
Convierte la imagen a bytes
Returns
Definition at line 175 of file Registro.cs.
        {
            byte[] imagen = null;
            FileStream stream = new FileStream(rutaImagen, FileMode.Open, FileAccess.Read);
            BinaryReader br = new BinaryReader(stream);
            imagen = br.ReadBytes((int)stream.Length);
            return imagen;
        }
References UI.Registro.rutaImagen.
Referenced by UI.Registro.btnRegistrar_Click().
InitializeComponent()
void UI.Registro.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file Registro.Designer.cs.
        {
            this.chkContrasenna = new System.Windows.Forms.CheckBox();
            this.txtContrasenna = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.mskTelefono = new System.Windows.Forms.MaskedTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtNombre = new System.Windows.Forms.TextBox();
            this.txtApellido = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.txtmail = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.dateTimePicker = new System.Windows.Forms.DateTimePicker();
            this.textValidarC = new System.Windows.Forms.TextBox();
            this.label9 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.cmbPais = new System.Windows.Forms.ComboBox();
            this.button1 = new System.Windows.Forms.Button();
            this.btnRegistrar = new System.Windows.Forms.Button();
            this.btnImagen = new System.Windows.Forms.Button();
            this.label11 = new System.Windows.Forms.Label();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.txtID = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();
            //
            // chkContrasenna
            //
            this.chkContrasenna.AutoSize = true;
            this.chkContrasenna.Location = new System.Drawing.Point(11, 498);
            this.chkContrasenna.Name = "chkContrasenna";
            this.chkContrasenna.Size = new System.Drawing.Size(162, 21);
            this.chkContrasenna.TabIndex = 14;
            this.chkContrasenna.Text = "Mostrar Contraseñas";
            this.chkContrasenna.UseVisualStyleBackColor = true;
            this.chkContrasenna.CheckedChanged += new System.EventHandler(this.chkContrasenna_CheckedChanged);
            //
            // txtContrasenna
            //
            this.txtContrasenna.Location = new System.Drawing.Point(11, 457);
            this.txtContrasenna.Name = "txtContrasenna";
            this.txtContrasenna.Size = new System.Drawing.Size(275, 22);
            this.txtContrasenna.TabIndex = 13;
            this.txtContrasenna.UseSystemPasswordChar = true;
            //
            // label3
            //
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(10, 422);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(131, 23);
            this.label3.TabIndex = 12;
            this.label3.Text = "Contraseña:";
            //
            // label2
            //
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(12, 86);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(274, 23);
            this.label2.TabIndex = 10;
            this.label2.Text = "Identificación (Cédula):";
            //
            // label1
            //
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Consolas", 16.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(336, 22);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(315, 33);
            this.label1.TabIndex = 15;
            this.label1.Text = "Registro de Usuarios";
            //
            // label4
            //
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(338, 86);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(109, 23);
            this.label4.TabIndex = 16;
            this.label4.Text = "Teléfono:";
            //
            // mskTelefono
            //
            this.mskTelefono.Location = new System.Drawing.Point(342, 121);
            this.mskTelefono.Mask = "(+000)0000-0000";
            this.mskTelefono.Name = "mskTelefono";
            this.mskTelefono.Size = new System.Drawing.Size(275, 22);
            this.mskTelefono.TabIndex = 17;
            //
            // label5
            //
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(12, 166);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(87, 23);
            this.label5.TabIndex = 18;
            this.label5.Text = "Nombre:";
            //
            // txtNombre
            //
            this.txtNombre.Location = new System.Drawing.Point(16, 201);
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.Size = new System.Drawing.Size(270, 22);
            this.txtNombre.TabIndex = 19;
            //
            // txtApellido
            //
            this.txtApellido.Location = new System.Drawing.Point(342, 201);
            this.txtApellido.Name = "txtApellido";
            this.txtApellido.Size = new System.Drawing.Size(275, 22);
            this.txtApellido.TabIndex = 21;
            //
            // label6
            //
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(338, 166);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(131, 23);
            this.label6.TabIndex = 20;
            this.label6.Text = "Apellido/s:";
            //
            // label7
            //
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(12, 248);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(219, 23);
            this.label7.TabIndex = 22;
            this.label7.Text = "Correo Electrónico:";
            //
            // txtmail
            //
            this.txtmail.Location = new System.Drawing.Point(16, 285);
            this.txtmail.Name = "txtmail";
            this.txtmail.Size = new System.Drawing.Size(270, 22);
            this.txtmail.TabIndex = 23;
            //
            // label8
            //
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(338, 248);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(230, 23);
            this.label8.TabIndex = 24;
            this.label8.Text = "Fecha de Nacimiento:";
            //
            // dateTimePicker
            //
            this.dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dateTimePicker.Location = new System.Drawing.Point(342, 283);
            this.dateTimePicker.Name = "dateTimePicker";
            this.dateTimePicker.Size = new System.Drawing.Size(275, 22);
            this.dateTimePicker.TabIndex = 25;
            this.dateTimePicker.Value = new System.DateTime(2000, 1, 1, 0, 0, 0, 0);
            //
            // textValidarC
            //
            this.textValidarC.Location = new System.Drawing.Point(339, 457);
            this.textValidarC.Name = "textValidarC";
            this.textValidarC.Size = new System.Drawing.Size(278, 22);
            this.textValidarC.TabIndex = 27;
            this.textValidarC.UseSystemPasswordChar = true;
            //
            // label9
            //
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.Location = new System.Drawing.Point(338, 422);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(241, 23);
            this.label9.TabIndex = 26;
            this.label9.Text = "Valide su contraseña:";
            //
            // label10
            //
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.Location = new System.Drawing.Point(12, 331);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(65, 23);
            this.label10.TabIndex = 28;
            this.label10.Text = "País:";
            //
            // cmbPais
            //
            this.cmbPais.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbPais.FormattingEnabled = true;
            this.cmbPais.Location = new System.Drawing.Point(16, 366);
            this.cmbPais.Name = "cmbPais";
            this.cmbPais.Size = new System.Drawing.Size(270, 24);
            this.cmbPais.Sorted = true;
            this.cmbPais.TabIndex = 29;
            //
            // button1
            //
            this.button1.Location = new System.Drawing.Point(11, 525);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(182, 54);
            this.button1.TabIndex = 30;
            this.button1.Text = "Salir";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            //
            // btnRegistrar
            //
            this.btnRegistrar.Location = new System.Drawing.Point(861, 525);
            this.btnRegistrar.Name = "btnRegistrar";
            this.btnRegistrar.Size = new System.Drawing.Size(182, 54);
            this.btnRegistrar.TabIndex = 31;
            this.btnRegistrar.Text = "Registrarse";
            this.btnRegistrar.UseVisualStyleBackColor = true;
            this.btnRegistrar.Click += new System.EventHandler(this.btnRegistrar_Click);
            //
            // btnImagen
            //
            this.btnImagen.Location = new System.Drawing.Point(769, 444);
            this.btnImagen.Name = "btnImagen";
            this.btnImagen.Size = new System.Drawing.Size(160, 35);
            this.btnImagen.TabIndex = 32;
            this.btnImagen.Text = "Seleccionar Imagen";
            this.btnImagen.UseVisualStyleBackColor = true;
            this.btnImagen.Click += new System.EventHandler(this.btnImagen_Click);
            //
            // label11
            //
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Consolas", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label11.Location = new System.Drawing.Point(800, 86);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(87, 23);
            this.label11.TabIndex = 33;
            this.label11.Text = "Imagen:";
            //
            // pictureBox
            //
            this.pictureBox.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.pictureBox.Location = new System.Drawing.Point(681, 121);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(332, 280);
            this.pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox.TabIndex = 34;
            this.pictureBox.TabStop = false;
            //
            // txtID
            //
            this.txtID.Location = new System.Drawing.Point(16, 121);
            this.txtID.Name = "txtID";
            this.txtID.Size = new System.Drawing.Size(270, 22);
            this.txtID.TabIndex = 35;
            //
            // Registro
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1055, 591);
            this.Controls.Add(this.txtID);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.label11);
            this.Controls.Add(this.btnImagen);
            this.Controls.Add(this.btnRegistrar);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.cmbPais);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.textValidarC);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.dateTimePicker);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.txtmail);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.txtApellido);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtNombre);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.mskTelefono);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.chkContrasenna);
            this.Controls.Add(this.txtContrasenna);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "Registro";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Registro";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Registro_FormClosed);
            this.Load += new System.EventHandler(this.Registro_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Registro.btnImagen, UI.Registro.btnImagen_Click(), UI.Registro.btnRegistrar, UI.Registro.btnRegistrar_Click(), UI.Registro.button1, UI.Registro.button1_Click(), UI.Registro.chkContrasenna, UI.Registro.chkContrasenna_CheckedChanged(), UI.Registro.cmbPais, UI.Registro.dateTimePicker, UI.Registro.label1, UI.Registro.label10, UI.Registro.label11, UI.Registro.label2, UI.Registro.label3, UI.Registro.label4, UI.Registro.label5, UI.Registro.label6, UI.Registro.label7, UI.Registro.label8, UI.Registro.label9, UI.Registro.mskTelefono, UI.Registro.pictureBox, UI.Registro.Registro_FormClosed(), UI.Registro.Registro_Load(), UI.Registro.textValidarC, UI.Registro.txtApellido, UI.Registro.txtContrasenna, UI.Registro.txtID, UI.Registro.txtmail, and UI.Registro.txtNombre.
Referenced by UI.Registro.Registro().
Limpiar()
void UI.Registro.Limpiar () private
Limpia los objetos gráficos
Definition at line 190 of file Registro.cs.
        {
            txtID.Text = "";
            txtNombre.Text = "";
            txtmail.Text = "";
            txtApellido.Text = "";
            txtContrasenna.Text = "";
            textValidarC.Text = "";
            mskTelefono.Clear();
            pictureBox.Image = null;
        }
References UI.Registro.mskTelefono, UI.Registro.pictureBox, UI.Registro.textValidarC, UI.Registro.txtApellido, UI.Registro.txtContrasenna, UI.Registro.txtID, UI.Registro.txtmail, and UI.Registro.txtNombre.
Referenced by UI.Registro.btnRegistrar_Click().
Registro_FormClosed()
void UI.Registro.Registro_FormClosed (object sender, FormClosedEventArgs e) private
Definition at line 233 of file Registro.cs.
        {
        }
Referenced by UI.Registro.InitializeComponent().
Registro_Load()
void UI.Registro.Registro_Load (object sender, EventArgs e) private
Llena el combo países
Parameters
sender
e
Definition at line 207 of file Registro.cs.
        {
            try
            {
                List<Pais> paises = PaisLN.ObtenerTodos();
                cmbPais.DisplayMember = "Nombre";
                cmbPais.DataSource = paises;
            }
            catch (Exception er)
            {
                _MyLogControlEventos.Error("Ocurrió el siguiente error:" + er.Message);
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References UI.Registro._MyLogControlEventos, UI.Registro.cmbPais, and Capa.BLL.PaisLN.ObtenerTodos().
Referenced by UI.Registro.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Registro._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file Registro.cs.
Referenced by UI.Registro.btnRegistrar_Click(), and UI.Registro.Registro_Load().
btnImagen
System.Windows.Forms.Button UI.Registro.btnImagen private
Definition at line 358 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
btnRegistrar
System.Windows.Forms.Button UI.Registro.btnRegistrar private
Definition at line 357 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
button1
System.Windows.Forms.Button UI.Registro.button1 private
Definition at line 356 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
c
Cliente UI.Registro.c private
Definition at line 23 of file Registro.cs.
Referenced by UI.Registro.btnRegistrar_Click().
chkContrasenna
System.Windows.Forms.CheckBox UI.Registro.chkContrasenna private
Definition at line 337 of file Registro.Designer.cs.
Referenced by UI.Registro.chkContrasenna_CheckedChanged(), and UI.Registro.InitializeComponent().
cmbPais
System.Windows.Forms.ComboBox UI.Registro.cmbPais private
Definition at line 355 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Registro_Load().
components
System.ComponentModel.IContainer UI.Registro.components = null private
Required designer variable.
Definition at line 9 of file Registro.Designer.cs.
Referenced by UI.Registro.Dispose().
dateTimePicker
System.Windows.Forms.DateTimePicker UI.Registro.dateTimePicker private
Definition at line 351 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), and UI.Registro.InitializeComponent().
label1
System.Windows.Forms.Label UI.Registro.label1 private
Definition at line 341 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label10
System.Windows.Forms.Label UI.Registro.label10 private
Definition at line 354 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label11
System.Windows.Forms.Label UI.Registro.label11 private
Definition at line 359 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label2
System.Windows.Forms.Label UI.Registro.label2 private
Definition at line 340 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label3
System.Windows.Forms.Label UI.Registro.label3 private
Definition at line 339 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label4
System.Windows.Forms.Label UI.Registro.label4 private
Definition at line 342 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label5
System.Windows.Forms.Label UI.Registro.label5 private
Definition at line 344 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label6
System.Windows.Forms.Label UI.Registro.label6 private
Definition at line 347 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label7
System.Windows.Forms.Label UI.Registro.label7 private
Definition at line 348 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label8
System.Windows.Forms.Label UI.Registro.label8 private
Definition at line 350 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
label9
System.Windows.Forms.Label UI.Registro.label9 private
Definition at line 353 of file Registro.Designer.cs.
Referenced by UI.Registro.InitializeComponent().
logica
IClienteLN UI.Registro.logica = new ClienteLN() private
Definition at line 22 of file Registro.cs.
Referenced by UI.Registro.btnRegistrar_Click().
mskTelefono
System.Windows.Forms.MaskedTextBox UI.Registro.mskTelefono private
Definition at line 343 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
pictureBox
System.Windows.Forms.PictureBox UI.Registro.pictureBox private
Definition at line 360 of file Registro.Designer.cs.
Referenced by UI.Registro.btnImagen_Click(), UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
rutaImagen
string UI.Registro.rutaImagen = "" private
Definition at line 19 of file Registro.cs.
Referenced by UI.Registro.btnImagen_Click(), and UI.Registro.imagenBytes().
textValidarC
System.Windows.Forms.TextBox UI.Registro.textValidarC private
Definition at line 352 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.chkContrasenna_CheckedChanged(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
txtApellido
System.Windows.Forms.TextBox UI.Registro.txtApellido private
Definition at line 346 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
txtContrasenna
System.Windows.Forms.TextBox UI.Registro.txtContrasenna private
Definition at line 338 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.chkContrasenna_CheckedChanged(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
txtID
System.Windows.Forms.TextBox UI.Registro.txtID private
Definition at line 361 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
txtmail
System.Windows.Forms.TextBox UI.Registro.txtmail private
Definition at line 349 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
txtNombre
System.Windows.Forms.TextBox UI.Registro.txtNombre private
Definition at line 345 of file Registro.Designer.cs.
Referenced by UI.Registro.btnRegistrar_Click(), UI.Registro.InitializeComponent(), and UI.Registro.Limpiar().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Seguridad/Registro.cs
118710756/DbaCreator/UI/Seguridad/Registro.Designer.cs