DBACreator: UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable Class Reference
UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
PA_ReporteVentasDataTable ()
void AddPA_ReporteVentasRow (PA_ReporteVentasRow row)
PA_ReporteVentasRow AddPA_ReporteVentasRow (int IDFactura, string Tarjeta, string Nombre, int IDCliente, System.DateTime FechaFacturacion, string TarjetaNumero, decimal Total)
PA_ReporteVentasRow FindByIDFactura (int IDFactura)
override global::System.Data.DataTable Clone ()
PA_ReporteVentasRow NewPA_ReporteVentasRow ()
void RemovePA_ReporteVentasRow (PA_ReporteVentasRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
PA_ReporteVentasDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
PA_ReporteVentasDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn IDFacturaColumn [get]
global::System.Data.DataColumn TarjetaColumn [get]
global::System.Data.DataColumn NombreColumn [get]
global::System.Data.DataColumn IDClienteColumn [get]
global::System.Data.DataColumn FechaFacturacionColumn [get]
global::System.Data.DataColumn TarjetaNumeroColumn [get]
global::System.Data.DataColumn TotalColumn [get]
int Count [get]
PA_ReporteVentasRow this[int index] [get]
Events
PA_ReporteVentasRowChangeEventHandler PA_ReporteVentasRowChanging
PA_ReporteVentasRowChangeEventHandler PA_ReporteVentasRowChanged
PA_ReporteVentasRowChangeEventHandler PA_ReporteVentasRowDeleting
PA_ReporteVentasRowChangeEventHandler PA_ReporteVentasRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnIDFactura
global::System.Data.DataColumn columnTarjeta
global::System.Data.DataColumn columnNombre
global::System.Data.DataColumn columnIDCliente
global::System.Data.DataColumn columnFechaFacturacion
global::System.Data.DataColumn columnTarjetaNumero
global::System.Data.DataColumn columnTotal
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1691 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
PA_ReporteVentasDataTable() [1/3]
UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable ()
Definition at line 1709 of file DataSetReportes.Designer.cs.
{
                this.TableName = "PA_ReporteVentas";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass().
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.Clone(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.CreateInstance().
PA_ReporteVentasDataTable() [2/3]
UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable (global::System.Data.DataTable table) package
Definition at line 1718 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
PA_ReporteVentasDataTable() [3/3]
UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 1735 of file DataSetReportes.Designer.cs.
                                                                                                                                                                        :
                    base(info, context) {
                this.InitVars();
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
Member Function Documentation
AddPA_ReporteVentasRow() [1/2]
PA_ReporteVentasRow UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.AddPA_ReporteVentasRow (int IDFactura, string Tarjeta, string Nombre, int IDCliente, System.DateTime FechaFacturacion, string TarjetaNumero, decimal Total)
Definition at line 1833 of file DataSetReportes.Designer.cs.
{
                PA_ReporteVentasRow rowPA_ReporteVentasRow = ((PA_ReporteVentasRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IDFactura,
                        Tarjeta,
                        Nombre,
                        IDCliente,
                        FechaFacturacion,
                        TarjetaNumero,
                        Total};
                rowPA_ReporteVentasRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPA_ReporteVentasRow);
                return rowPA_ReporteVentasRow;
            }
AddPA_ReporteVentasRow() [2/2]
void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.AddPA_ReporteVentasRow (PA_ReporteVentasRow row)
Definition at line 1827 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
Clone()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.Clone ()
Definition at line 1857 of file DataSetReportes.Designer.cs.
{
                PA_ReporteVentasDataTable cln = ((PA_ReporteVentasDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable().
CreateInstance()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.CreateInstance () protected
Definition at line 1865 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteVentasDataTable();
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable().
FindByIDFactura()
PA_ReporteVentasRow UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.FindByIDFactura (int IDFactura)
Definition at line 1850 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteVentasRow)(this.Rows.Find(new object[] {
                            IDFactura})));
            }
GetRowType()
override global.System.Type UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.GetRowType () protected
Definition at line 1926 of file DataSetReportes.Designer.cs.
{
                return typeof(PA_ReporteVentasRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 1974 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PA_ReporteVentasDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass () private
Definition at line 1883 of file DataSetReportes.Designer.cs.
{
                this.columnIDFactura = new global::System.Data.DataColumn("IDFactura", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDFactura);
                this.columnTarjeta = new global::System.Data.DataColumn("Tarjeta", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTarjeta);
                this.columnNombre = new global::System.Data.DataColumn("Nombre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNombre);
                this.columnIDCliente = new global::System.Data.DataColumn("IDCliente", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDCliente);
                this.columnFechaFacturacion = new global::System.Data.DataColumn("FechaFacturacion", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFechaFacturacion);
                this.columnTarjetaNumero = new global::System.Data.DataColumn("TarjetaNumero", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTarjetaNumero);
                this.columnTotal = new global::System.Data.DataColumn("Total", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTotal);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnIDFactura}, true));
                this.columnIDFactura.AllowDBNull = false;
                this.columnIDFactura.Unique = true;
                this.columnTarjeta.AllowDBNull = false;
                this.columnTarjeta.MaxLength = 50;
                this.columnNombre.AllowDBNull = false;
                this.columnNombre.MaxLength = 50;
                this.columnIDCliente.AllowDBNull = false;
                this.columnFechaFacturacion.AllowDBNull = false;
                this.columnTarjetaNumero.AllowDBNull = false;
                this.columnTarjetaNumero.MaxLength = 50;
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnFechaFacturacion, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDCliente, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDFactura, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnNombre, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjeta, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjetaNumero, and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTotal.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable().
InitVars()
void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars () package
Definition at line 1871 of file DataSetReportes.Designer.cs.
{
                this.columnIDFactura = base.Columns["IDFactura"];
                this.columnTarjeta = base.Columns["Tarjeta"];
                this.columnNombre = base.Columns["Nombre"];
                this.columnIDCliente = base.Columns["IDCliente"];
                this.columnFechaFacturacion = base.Columns["FechaFacturacion"];
                this.columnTarjetaNumero = base.Columns["TarjetaNumero"];
                this.columnTotal = base.Columns["Total"];
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnFechaFacturacion, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDCliente, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDFactura, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnNombre, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjeta, UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjetaNumero, and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTotal.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.Clone(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasDataTable().
NewPA_ReporteVentasRow()
PA_ReporteVentasRow UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.NewPA_ReporteVentasRow ()
Definition at line 1914 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteVentasRow)(this.NewRow()));
            }
NewRowFromBuilder()
override global.System.Data.DataRow UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 1920 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteVentasRow(builder);
            }
OnRowChanged()
override void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1932 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.PA_ReporteVentasRowChanged != null)) {
                    this.PA_ReporteVentasRowChanged(this, new PA_ReporteVentasRowChangeEvent(((PA_ReporteVentasRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowChanged.
OnRowChanging()
override void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1941 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.PA_ReporteVentasRowChanging != null)) {
                    this.PA_ReporteVentasRowChanging(this, new PA_ReporteVentasRowChangeEvent(((PA_ReporteVentasRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowChanging.
OnRowDeleted()
override void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1950 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.PA_ReporteVentasRowDeleted != null)) {
                    this.PA_ReporteVentasRowDeleted(this, new PA_ReporteVentasRowChangeEvent(((PA_ReporteVentasRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowDeleted.
OnRowDeleting()
override void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1959 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.PA_ReporteVentasRowDeleting != null)) {
                    this.PA_ReporteVentasRowDeleting(this, new PA_ReporteVentasRowChangeEvent(((PA_ReporteVentasRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowDeleting.
RemovePA_ReporteVentasRow()
void UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.RemovePA_ReporteVentasRow (PA_ReporteVentasRow row)
Definition at line 1968 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnFechaFacturacion
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnFechaFacturacion private
Definition at line 1701 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnIDCliente
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDCliente private
Definition at line 1699 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnIDFactura
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnIDFactura private
Definition at line 1693 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnNombre
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnNombre private
Definition at line 1697 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnTarjeta
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjeta private
Definition at line 1695 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnTarjetaNumero
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTarjetaNumero private
Definition at line 1703 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
columnTotal
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.columnTotal private
Definition at line 1705 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars().
Property Documentation
Count
int UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.Count get
Definition at line 1799 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
FechaFacturacionColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.FechaFacturacionColumn get
Definition at line 1774 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnFechaFacturacion;
                }
            }
IDClienteColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.IDClienteColumn get
Definition at line 1766 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDCliente;
                }
            }
IDFacturaColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.IDFacturaColumn get
Definition at line 1742 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDFactura;
                }
            }
NombreColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.NombreColumn get
Definition at line 1758 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnNombre;
                }
            }
TarjetaColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.TarjetaColumn get
Definition at line 1750 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnTarjeta;
                }
            }
TarjetaNumeroColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.TarjetaNumeroColumn get
Definition at line 1782 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnTarjetaNumero;
                }
            }
this[int index]
PA_ReporteVentasRow UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.this[int index] get
Definition at line 1807 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((PA_ReporteVentasRow)(this.Rows[index]));
                }
            }
TotalColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.TotalColumn get
Definition at line 1790 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnTotal;
                }
            }
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasRow.IsTotalNull(), and UI.Reportes.DataSetReportes.PA_ReporteVentasRow.SetTotalNull().
Event Documentation
PA_ReporteVentasRowChanged
PA_ReporteVentasRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowChanged
Definition at line 1817 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowChanged().
PA_ReporteVentasRowChanging
PA_ReporteVentasRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowChanging
Definition at line 1814 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowChanging().
PA_ReporteVentasRowDeleted
PA_ReporteVentasRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowDeleted
Definition at line 1823 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowDeleted().
PA_ReporteVentasRowDeleting
PA_ReporteVentasRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.PA_ReporteVentasRowDeleting
Definition at line 1820 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs