DBACreator: Capa.DAL.CertificacionDB Class Reference
Capa.DAL.CertificacionDB Class Reference
Static Public Member Functions
static void AgregarCertificacion (Certificacion c)
Método que guarda la certificacion en la base de datos
static List< Certificacion > ObtenerTodos ()
Método para obtener todos los datos de la tabla Certificación
static Certificacion SeleccionarPorId (int id)
Retorna de la tabla Certificación el dato con el ID buscado
static void Borrar (int id)
Borra el dato de la tabla con el ID enviado
static void Actualizar (Certificacion c)
Método que actualiza un dato en la tabla
Detailed Description
Definition at line 12 of file CertificacionDB.cs.
Member Function Documentation
Actualizar()
static void Capa.DAL.CertificacionDB.Actualizar (Certificacion c) static
Método que actualiza un dato en la tabla
Parameters
c Objeto del que extrae los datos
Definition at line 109 of file CertificacionDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_ActualizarCertificacion";
                comando.Parameters.AddWithValue("@descripcion", c.Descripcion);
                comando.Parameters.AddWithValue("@precio", c.Precio);
                comando.Parameters.AddWithValue("@id", c.Id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Certificacion.Descripcion, IDataBase.ExecuteNonQuery(), Capa.Entities.Certificacion.Id, and Capa.Entities.Certificacion.Precio.
Referenced by Capa.BLL.CertificacionLN.Guardar().
AgregarCertificacion()
static void Capa.DAL.CertificacionDB.AgregarCertificacion (Certificacion c) static
Método que guarda la certificacion en la base de datos
Parameters
c Certificación del cuál extraerá los datos
Definition at line 18 of file CertificacionDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarCertificacion";
                comando.Parameters.AddWithValue("@id", c.Id);
                comando.Parameters.AddWithValue("@descripcion", c.Descripcion);
                comando.Parameters.AddWithValue("@precio", c.Precio);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Certificacion.Descripcion, IDataBase.ExecuteNonQuery(), Capa.Entities.Certificacion.Id, and Capa.Entities.Certificacion.Precio.
Referenced by Capa.BLL.CertificacionLN.Guardar().
Borrar()
static void Capa.DAL.CertificacionDB.Borrar (int id) static
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Definition at line 93 of file CertificacionDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = CommandType.StoredProcedure;
                comando.CommandText = "PA_BorrarCertificacion";
                comando.Parameters.AddWithValue("@id", id);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.CertificacionLN.Borrar().
ObtenerTodos()
static List< Certificacion > Capa.DAL.CertificacionDB.ObtenerTodos () static
Método para obtener todos los datos de la tabla Certificación
Returns
Retorna una lista con todos los datos de la tabla Certificacion
Definition at line 36 of file CertificacionDB.cs.
        {
            List<Certificacion> lista = new List<Certificacion>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarCertificaciones";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Certificacion c = new Certificacion();
                    c.Id = (int)dr["IDCertificacion"];
                    c.Descripcion = dr["Descripcion"].ToString();
                    c.Precio = Convert.ToDouble(dr["Precio"]);
                    lista.Add(c);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Certificacion.Descripcion, IDataBase.ExecuteDataSet(), Capa.Entities.Certificacion.Id, and Capa.Entities.Certificacion.Precio.
Referenced by Capa.BLL.CertificacionLN.ObtenerTodos().
SeleccionarPorId()
static Certificacion Capa.DAL.CertificacionDB.SeleccionarPorId (int id) static
Retorna de la tabla Certificación el dato con el ID buscado
Parameters
id ID a buscar
Returns
Definition at line 66 of file CertificacionDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarCertificacionPorID";
                comando.Parameters.AddWithValue("@Id", id);
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Certificacion c = new Certificacion();
                    c.Id = (int)dr["IDCertificacion"];
                    c.Descripcion = dr["Descripcion"].ToString();
                    c.Precio = Convert.ToDouble(dr["Precio"]);
                    return c;
                }
            }
            return null;
        }
References FactoryDatabase.CreateDefaultDataBase(), Capa.Entities.Certificacion.Descripcion, IDataBase.ExecuteDataSet(), Capa.Entities.Certificacion.Id, and Capa.Entities.Certificacion.Precio.
Referenced by Capa.BLL.CertificacionLN.ObtenerPorID(), Capa.DAL.ExamenDB.ObtenerTodos(), Capa.DAL.ExamenDB.SeleccionarPorCertificacion(), and Capa.DAL.ExamenDB.SeleccionarPorId().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/CertificacionDB.cs