DBACreator: UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable Class Reference
UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
PA_ReporteClientesCertificadosDataTable ()
void AddPA_ReporteClientesCertificadosRow (PA_ReporteClientesCertificadosRow row)
PA_ReporteClientesCertificadosRow AddPA_ReporteClientesCertificadosRow (int IDCliente, string Nombre, string Apellido, string Email, byte[] Fotografia, System.DateTime FechaNacimiento)
PA_ReporteClientesCertificadosRow FindByIDCliente (int IDCliente)
override global::System.Data.DataTable Clone ()
PA_ReporteClientesCertificadosRow NewPA_ReporteClientesCertificadosRow ()
void RemovePA_ReporteClientesCertificadosRow (PA_ReporteClientesCertificadosRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
PA_ReporteClientesCertificadosDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
PA_ReporteClientesCertificadosDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn IDClienteColumn [get]
global::System.Data.DataColumn NombreColumn [get]
global::System.Data.DataColumn ApellidoColumn [get]
global::System.Data.DataColumn EmailColumn [get]
global::System.Data.DataColumn FotografiaColumn [get]
global::System.Data.DataColumn FechaNacimientoColumn [get]
int Count [get]
PA_ReporteClientesCertificadosRow this[int index] [get]
Events
PA_ReporteClientesCertificadosRowChangeEventHandler PA_ReporteClientesCertificadosRowChanging
PA_ReporteClientesCertificadosRowChangeEventHandler PA_ReporteClientesCertificadosRowChanged
PA_ReporteClientesCertificadosRowChangeEventHandler PA_ReporteClientesCertificadosRowDeleting
PA_ReporteClientesCertificadosRowChangeEventHandler PA_ReporteClientesCertificadosRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnIDCliente
global::System.Data.DataColumn columnNombre
global::System.Data.DataColumn columnApellido
global::System.Data.DataColumn columnEmail
global::System.Data.DataColumn columnFotografia
global::System.Data.DataColumn columnFechaNacimiento
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2794 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
PA_ReporteClientesCertificadosDataTable() [1/3]
UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable ()
Definition at line 2810 of file DataSetReportes.Designer.cs.
{
                this.TableName = "PA_ReporteClientesCertificados";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass().
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.Clone(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.CreateInstance().
PA_ReporteClientesCertificadosDataTable() [2/3]
UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable (global::System.Data.DataTable table) package
Definition at line 2819 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
PA_ReporteClientesCertificadosDataTable() [3/3]
UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 2836 of file DataSetReportes.Designer.cs.
                                                                                                                                                                                      :
                    base(info, context) {
                this.InitVars();
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
Member Function Documentation
AddPA_ReporteClientesCertificadosRow() [1/2]
PA_ReporteClientesCertificadosRow UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.AddPA_ReporteClientesCertificadosRow (int IDCliente, string Nombre, string Apellido, string Email, byte[] Fotografia, System.DateTime FechaNacimiento)
Definition at line 2926 of file DataSetReportes.Designer.cs.
{
                PA_ReporteClientesCertificadosRow rowPA_ReporteClientesCertificadosRow = ((PA_ReporteClientesCertificadosRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IDCliente,
                        Nombre,
                        Apellido,
                        Email,
                        Fotografia,
                        FechaNacimiento};
                rowPA_ReporteClientesCertificadosRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPA_ReporteClientesCertificadosRow);
                return rowPA_ReporteClientesCertificadosRow;
            }
AddPA_ReporteClientesCertificadosRow() [2/2]
void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.AddPA_ReporteClientesCertificadosRow (PA_ReporteClientesCertificadosRow row)
Definition at line 2920 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
Clone()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.Clone ()
Definition at line 2949 of file DataSetReportes.Designer.cs.
{
                PA_ReporteClientesCertificadosDataTable cln = ((PA_ReporteClientesCertificadosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable().
CreateInstance()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.CreateInstance () protected
Definition at line 2957 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteClientesCertificadosDataTable();
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable().
FindByIDCliente()
PA_ReporteClientesCertificadosRow UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.FindByIDCliente (int IDCliente)
Definition at line 2942 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteClientesCertificadosRow)(this.Rows.Find(new object[] {
                            IDCliente})));
            }
GetRowType()
override global.System.Type UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.GetRowType () protected
Definition at line 3014 of file DataSetReportes.Designer.cs.
{
                return typeof(PA_ReporteClientesCertificadosRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 3062 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PA_ReporteClientesCertificadosDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass () private
Definition at line 2974 of file DataSetReportes.Designer.cs.
{
                this.columnIDCliente = new global::System.Data.DataColumn("IDCliente", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDCliente);
                this.columnNombre = new global::System.Data.DataColumn("Nombre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNombre);
                this.columnApellido = new global::System.Data.DataColumn("Apellido", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnApellido);
                this.columnEmail = new global::System.Data.DataColumn("Email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEmail);
                this.columnFotografia = new global::System.Data.DataColumn("Fotografia", typeof(byte[]), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFotografia);
                this.columnFechaNacimiento = new global::System.Data.DataColumn("FechaNacimiento", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFechaNacimiento);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnIDCliente}, true));
                this.columnIDCliente.AllowDBNull = false;
                this.columnIDCliente.Unique = true;
                this.columnNombre.AllowDBNull = false;
                this.columnNombre.MaxLength = 50;
                this.columnApellido.AllowDBNull = false;
                this.columnApellido.MaxLength = 50;
                this.columnEmail.AllowDBNull = false;
                this.columnEmail.MaxLength = 50;
                this.columnFechaNacimiento.AllowDBNull = false;
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnEmail, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFechaNacimiento, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFotografia, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnIDCliente, and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnNombre.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable().
InitVars()
void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars () package
Definition at line 2963 of file DataSetReportes.Designer.cs.
{
                this.columnIDCliente = base.Columns["IDCliente"];
                this.columnNombre = base.Columns["Nombre"];
                this.columnApellido = base.Columns["Apellido"];
                this.columnEmail = base.Columns["Email"];
                this.columnFotografia = base.Columns["Fotografia"];
                this.columnFechaNacimiento = base.Columns["FechaNacimiento"];
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnEmail, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFechaNacimiento, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFotografia, UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnIDCliente, and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnNombre.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.Clone(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosDataTable().
NewPA_ReporteClientesCertificadosRow()
PA_ReporteClientesCertificadosRow UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.NewPA_ReporteClientesCertificadosRow ()
Definition at line 3002 of file DataSetReportes.Designer.cs.
{
                return ((PA_ReporteClientesCertificadosRow)(this.NewRow()));
            }
NewRowFromBuilder()
override global.System.Data.DataRow UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 3008 of file DataSetReportes.Designer.cs.
{
                return new PA_ReporteClientesCertificadosRow(builder);
            }
OnRowChanged()
override void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3020 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.PA_ReporteClientesCertificadosRowChanged != null)) {
                    this.PA_ReporteClientesCertificadosRowChanged(this, new PA_ReporteClientesCertificadosRowChangeEvent(((PA_ReporteClientesCertificadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowChanged.
OnRowChanging()
override void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3029 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.PA_ReporteClientesCertificadosRowChanging != null)) {
                    this.PA_ReporteClientesCertificadosRowChanging(this, new PA_ReporteClientesCertificadosRowChangeEvent(((PA_ReporteClientesCertificadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowChanging.
OnRowDeleted()
override void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3038 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.PA_ReporteClientesCertificadosRowDeleted != null)) {
                    this.PA_ReporteClientesCertificadosRowDeleted(this, new PA_ReporteClientesCertificadosRowChangeEvent(((PA_ReporteClientesCertificadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowDeleted.
OnRowDeleting()
override void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 3047 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.PA_ReporteClientesCertificadosRowDeleting != null)) {
                    this.PA_ReporteClientesCertificadosRowDeleting(this, new PA_ReporteClientesCertificadosRowChangeEvent(((PA_ReporteClientesCertificadosRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowDeleting.
RemovePA_ReporteClientesCertificadosRow()
void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.RemovePA_ReporteClientesCertificadosRow (PA_ReporteClientesCertificadosRow row)
Definition at line 3056 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnApellido
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnApellido private
Definition at line 2800 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
columnEmail
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnEmail private
Definition at line 2802 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
columnFechaNacimiento
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFechaNacimiento private
Definition at line 2806 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
columnFotografia
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnFotografia private
Definition at line 2804 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
columnIDCliente
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnIDCliente private
Definition at line 2796 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
columnNombre
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.columnNombre private
Definition at line 2798 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars().
Property Documentation
ApellidoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.ApellidoColumn get
Definition at line 2859 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnApellido;
                }
            }
Count
int UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.Count get
Definition at line 2892 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
EmailColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.EmailColumn get
Definition at line 2867 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnEmail;
                }
            }
FechaNacimientoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.FechaNacimientoColumn get
Definition at line 2883 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnFechaNacimiento;
                }
            }
FotografiaColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.FotografiaColumn get
Definition at line 2875 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnFotografia;
                }
            }
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosRow.IsFotografiaNull(), and UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosRow.SetFotografiaNull().
IDClienteColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.IDClienteColumn get
Definition at line 2843 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDCliente;
                }
            }
NombreColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.NombreColumn get
Definition at line 2851 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnNombre;
                }
            }
this[int index]
PA_ReporteClientesCertificadosRow UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.this[int index] get
Definition at line 2900 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((PA_ReporteClientesCertificadosRow)(this.Rows[index]));
                }
            }
Event Documentation
PA_ReporteClientesCertificadosRowChanged
PA_ReporteClientesCertificadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowChanged
Definition at line 2910 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowChanged().
PA_ReporteClientesCertificadosRowChanging
PA_ReporteClientesCertificadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowChanging
Definition at line 2907 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowChanging().
PA_ReporteClientesCertificadosRowDeleted
PA_ReporteClientesCertificadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowDeleted
Definition at line 2916 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowDeleted().
PA_ReporteClientesCertificadosRowDeleting
PA_ReporteClientesCertificadosRowChangeEventHandler UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.PA_ReporteClientesCertificadosRowDeleting
Definition at line 2913 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs