DBACreator: UI.Reportes.ReporteFactura Class Reference
UI.Reportes.ReporteFactura Class Reference
Public Member Functions
ReporteFactura (int numeroFactura, string correoC)
void GenerarPDF ()
Genera el pdf
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void ReporteFactura_Load (object sender, EventArgs e)
Crea un reporte con la factura y el código QR correspondiente
void toolStripBtnSalir_Click (object sender, EventArgs e)
Cierra la ventana
void toolStripBtnExportarPDF_Click (object sender, EventArgs e)
Llama al método generarPDF
void toolStripBtnMail_Click (object sender, EventArgs e)
Envía el pdf creado al correo del cliente
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int noFactura
string correo
string ruta
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnExportarPDF
System.Windows.Forms.ToolStripButton toolStripBtnSalir
Microsoft.Reporting.WinForms.ReportViewer reportViewer
System.Windows.Forms.BindingSource PA_SeleccionarDetallesPorFacturaBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_SeleccionarDetallesPorFacturaTableAdapter PA_SeleccionarDetallesPorFacturaTableAdapter
System.Windows.Forms.ToolStripButton toolStripBtnMail
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 19 of file ReporteFactura.cs.
Constructor & Destructor Documentation
ReporteFactura()
UI.Reportes.ReporteFactura.ReporteFactura (int numeroFactura, string correoC)
Definition at line 25 of file ReporteFactura.cs.
        {
            InitializeComponent();
            this.noFactura = numeroFactura;
            this.correo = correoC;
        }
References UI.Reportes.ReporteFactura.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.ReporteFactura.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file ReporteFactura.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.ReporteFactura.components.
GenerarPDF()
void UI.Reportes.ReporteFactura.GenerarPDF ()
Genera el pdf
Definition at line 91 of file ReporteFactura.cs.
        {
            ruta = $@"c:\temp\factura{noFactura}.pdf";
            if (!Directory.Exists(@"c:\temp"))
                Directory.CreateDirectory(@"c:\temp");
            byte[] Bytes = this.reportViewer.LocalReport.Render(format: "PDF", deviceInfo: @"<DeviceInfo> <EmbedFonts>None</EmbedFonts> </DeviceInfo>");
            using (FileStream stream = new FileStream(ruta, FileMode.Create))
            {
                stream.Write(Bytes, 0, Bytes.Length);
            }
            Process.Start(ruta);
            _MyLogControlEventos.Info($"PDF Generado");
        }
References UI.Reportes.ReporteFactura._MyLogControlEventos, UI.Reportes.ReporteFactura.reportViewer, and UI.Reportes.ReporteFactura.ruta.
Referenced by UI.Reportes.ReporteFactura.toolStripBtnExportarPDF_Click(), and UI.Reportes.ReporteFactura.toolStripBtnMail_Click().
InitializeComponent()
void UI.Reportes.ReporteFactura.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file ReporteFactura.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ReporteFactura));
            this.PA_SeleccionarDetallesPorFacturaBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnExportarPDF = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.reportViewer = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_SeleccionarDetallesPorFacturaTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_SeleccionarDetallesPorFacturaTableAdapter();
            this.toolStripBtnMail = new System.Windows.Forms.ToolStripButton();
            ((System.ComponentModel.ISupportInitialize)(this.PA_SeleccionarDetallesPorFacturaBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // PA_SeleccionarDetallesPorFacturaBindingSource
            //
            this.PA_SeleccionarDetallesPorFacturaBindingSource.DataMember = "PA_SeleccionarDetallesPorFactura";
            this.PA_SeleccionarDetallesPorFacturaBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnMail,
            this.toolStripBtnExportarPDF,
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(885, 55);
            this.tspBarraSuperior.TabIndex = 2;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnExportarPDF
            //
            this.toolStripBtnExportarPDF.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnExportarPDF.Image")));
            this.toolStripBtnExportarPDF.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnExportarPDF.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnExportarPDF.Name = "toolStripBtnExportarPDF";
            this.toolStripBtnExportarPDF.Size = new System.Drawing.Size(147, 52);
            this.toolStripBtnExportarPDF.Text = "Exportar PDF";
            this.toolStripBtnExportarPDF.Click += new System.EventHandler(this.toolStripBtnExportarPDF_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // reportViewer
            //
            this.reportViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetFactura";
            reportDataSource1.Value = this.PA_SeleccionarDetallesPorFacturaBindingSource;
            this.reportViewer.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteFactura.rdlc";
            this.reportViewer.Location = new System.Drawing.Point(0, 55);
            this.reportViewer.Name = "reportViewer";
            this.reportViewer.ServerReport.BearerToken = null;
            this.reportViewer.Size = new System.Drawing.Size(885, 509);
            this.reportViewer.TabIndex = 3;
            //
            // PA_SeleccionarDetallesPorFacturaTableAdapter
            //
            this.PA_SeleccionarDetallesPorFacturaTableAdapter.ClearBeforeFill = true;
            //
            // toolStripBtnMail
            //
            this.toolStripBtnMail.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnMail.Image")));
            this.toolStripBtnMail.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnMail.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnMail.Name = "toolStripBtnMail";
            this.toolStripBtnMail.Size = new System.Drawing.Size(239, 52);
            this.toolStripBtnMail.Text = "Enviar al Correo Registrado";
            this.toolStripBtnMail.Click += new System.EventHandler(this.toolStripBtnMail_Click);
            //
            // ReporteFactura
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(885, 564);
            this.Controls.Add(this.reportViewer);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "ReporteFactura";
            this.Text = "Reporte de Factura";
            this.Load += new System.EventHandler(this.ReporteFactura_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_SeleccionarDetallesPorFacturaBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Reportes.ReporteFactura.components, UI.Reportes.ReporteFactura.DataSetReportes, UI.Reportes.ReporteFactura.PA_SeleccionarDetallesPorFacturaBindingSource, UI.Reportes.ReporteFactura.PA_SeleccionarDetallesPorFacturaTableAdapter, UI.Reportes.ReporteFactura.ReporteFactura_Load(), UI.Reportes.ReporteFactura.reportViewer, UI.Reportes.DataSetReportes.SchemaSerializationMode, UI.Reportes.ReporteFactura.toolStripBtnExportarPDF, UI.Reportes.ReporteFactura.toolStripBtnExportarPDF_Click(), UI.Reportes.ReporteFactura.toolStripBtnMail, UI.Reportes.ReporteFactura.toolStripBtnMail_Click(), UI.Reportes.ReporteFactura.toolStripBtnSalir, UI.Reportes.ReporteFactura.toolStripBtnSalir_Click(), and UI.Reportes.ReporteFactura.tspBarraSuperior.
Referenced by UI.Reportes.ReporteFactura.ReporteFactura().
ReporteFactura_Load()
void UI.Reportes.ReporteFactura.ReporteFactura_Load (object sender, EventArgs e) private
Crea un reporte con la factura y el código QR correspondiente
Parameters
sender
e
Definition at line 37 of file ReporteFactura.cs.
        {
            try
            {
                string rutaQR = @"file:///" + @"C:/TEMP/qrFactura.png";
                this.PA_SeleccionarDetallesPorFacturaTableAdapter.Fill(this.DataSetReportes.PA_SeleccionarDetallesPorFactura, noFactura);
                this.reportViewer.LocalReport.EnableExternalImages = true;
                ReportParameter param = new ReportParameter("quickresponse", rutaQR);
                this.reportViewer.LocalReport.SetParameters(param);
                this.reportViewer.RefreshReport();
                _MyLogControlEventos.Info($"Reporte de Factura {noFactura} generado");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de la factura: " + er.Message);
            }
        }
References UI.Reportes.ReporteFactura._MyLogControlEventos, UI.Reportes.ReporteFactura.noFactura, UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFactura, UI.Reportes.ReporteFactura.PA_SeleccionarDetallesPorFacturaTableAdapter, and UI.Reportes.ReporteFactura.reportViewer.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
toolStripBtnExportarPDF_Click()
void UI.Reportes.ReporteFactura.toolStripBtnExportarPDF_Click (object sender, EventArgs e) private
Llama al método generarPDF
Parameters
sender
e
Definition at line 75 of file ReporteFactura.cs.
        {
            try
            {
                GenerarPDF();
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de la factura: " + er.Message);
            }
        }
References UI.Reportes.ReporteFactura._MyLogControlEventos, and UI.Reportes.ReporteFactura.GenerarPDF().
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
toolStripBtnMail_Click()
void UI.Reportes.ReporteFactura.toolStripBtnMail_Click (object sender, EventArgs e) private
Envía el pdf creado al correo del cliente
Parameters
sender
e
Definition at line 114 of file ReporteFactura.cs.
        {
            try
            {
                GenerarPDF();
                Thread.Sleep(50);
                MailMessage mensaje = new MailMessage();
                mensaje.From = new MailAddress("alfredosuarezaguilar@gmail.com", "DBACreator");
                mensaje.To.Add(this.correo);
                mensaje.Subject = "Factura";
                mensaje.Body = "¡Gracias! Se adjunta su factura.";
                mensaje.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.Credentials = new NetworkCredential("alfredosuarezaguilar@gmail.com", "Hjxc20d8910");
                smtp.EnableSsl = true;
                Attachment attachment = new Attachment($@"c:\temp\factura{noFactura}.pdf");
                mensaje.Attachments.Add(attachment);
                smtp.Send(mensaje);
                MessageBox.Show("Correo Enviado", "Evento", MessageBoxButtons.OK, MessageBoxIcon.Information);
                _MyLogControlEventos.Info($"Mail enviado a {this.correo}");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el reporte de la factura: " + er.Message);
            }
        }
References UI.Reportes.ReporteFactura._MyLogControlEventos, and UI.Reportes.ReporteFactura.GenerarPDF().
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
toolStripBtnSalir_Click()
void UI.Reportes.ReporteFactura.toolStripBtnSalir_Click (object sender, EventArgs e) private
Cierra la ventana
Parameters
sender
e
Definition at line 65 of file ReporteFactura.cs.
        {
            this.Close();
        }
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.ReporteFactura._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 24 of file ReporteFactura.cs.
Referenced by UI.Reportes.ReporteFactura.GenerarPDF(), UI.Reportes.ReporteFactura.ReporteFactura_Load(), UI.Reportes.ReporteFactura.toolStripBtnExportarPDF_Click(), and UI.Reportes.ReporteFactura.toolStripBtnMail_Click().
components
System.ComponentModel.IContainer UI.Reportes.ReporteFactura.components = null private
Required designer variable.
Definition at line 9 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.Dispose(), and UI.Reportes.ReporteFactura.InitializeComponent().
correo
string UI.Reportes.ReporteFactura.correo private
Definition at line 22 of file ReporteFactura.cs.
DataSetReportes
DataSetReportes UI.Reportes.ReporteFactura.DataSetReportes private
Definition at line 145 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
noFactura
int UI.Reportes.ReporteFactura.noFactura private
Definition at line 21 of file ReporteFactura.cs.
Referenced by UI.Reportes.ReporteFactura.ReporteFactura_Load().
PA_SeleccionarDetallesPorFacturaBindingSource
System.Windows.Forms.BindingSource UI.Reportes.ReporteFactura.PA_SeleccionarDetallesPorFacturaBindingSource private
Definition at line 144 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
PA_SeleccionarDetallesPorFacturaTableAdapter
DataSetReportesTableAdapters.PA_SeleccionarDetallesPorFacturaTableAdapter UI.Reportes.ReporteFactura.PA_SeleccionarDetallesPorFacturaTableAdapter private
Definition at line 146 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent(), and UI.Reportes.ReporteFactura.ReporteFactura_Load().
reportViewer
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.ReporteFactura.reportViewer private
Definition at line 143 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.GenerarPDF(), UI.Reportes.ReporteFactura.InitializeComponent(), and UI.Reportes.ReporteFactura.ReporteFactura_Load().
ruta
string UI.Reportes.ReporteFactura.ruta private
Definition at line 23 of file ReporteFactura.cs.
Referenced by UI.Reportes.ReporteFactura.GenerarPDF().
toolStripBtnExportarPDF
System.Windows.Forms.ToolStripButton UI.Reportes.ReporteFactura.toolStripBtnExportarPDF private
Definition at line 141 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
toolStripBtnMail
System.Windows.Forms.ToolStripButton UI.Reportes.ReporteFactura.toolStripBtnMail private
Definition at line 147 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.Reportes.ReporteFactura.toolStripBtnSalir private
Definition at line 142 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip UI.Reportes.ReporteFactura.tspBarraSuperior private
Definition at line 140 of file ReporteFactura.Designer.cs.
Referenced by UI.Reportes.ReporteFactura.InitializeComponent().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/ReporteFactura.cs
118710756/DbaCreator/UI/Reportes/ReporteFactura.Designer.cs