DBACreator: Capa.DAL.IntentoDB Class Reference
Capa.DAL.IntentoDB Class Reference
Static Public Member Functions
static void Insertar (Intento i)
Inserta un intento en la base de datos
static int ObtenerNumeroDeIntentoActual ()
Usado para saber que numero de intento va y asignar un id
static void MarcarIntentoExitoso (int idIntento)
Si el cliente gana el examen se marca como exitoso
Detailed Description
Definition at line 12 of file IntentoDB.cs.
Member Function Documentation
Insertar()
static void Capa.DAL.IntentoDB.Insertar (Intento i) static
Inserta un intento en la base de datos
Parameters
i Intento del que extraerá los datos
Definition at line 18 of file IntentoDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_InsertarIntento";
                comando.Parameters.AddWithValue("@idIntento", i.IDIntento);
                comando.Parameters.AddWithValue("@idCliente", i.IDCliente);
                comando.Parameters.AddWithValue("@idExamen", i.IDExamen);
                comando.Parameters.AddWithValue("@Exitoso", i.Exitoso);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteNonQuery(), Capa.Entities.Intento.Exitoso, Capa.Entities.Intento.IDCliente, Capa.Entities.Intento.IDExamen, and Capa.Entities.Intento.IDIntento.
Referenced by Capa.BLL.IntentoLN.Insertar().
MarcarIntentoExitoso()
static void Capa.DAL.IntentoDB.MarcarIntentoExitoso (int idIntento) static
Si el cliente gana el examen se marca como exitoso
Parameters
idIntento ID a buscar
Definition at line 62 of file IntentoDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_ActualizarIntento";
                comando.Parameters.AddWithValue("@idIntento", idIntento);
                db.ExecuteNonQuery(comando);
            }
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteNonQuery().
Referenced by Capa.BLL.IntentoLN.MarcarIntentoExitoso().
ObtenerNumeroDeIntentoActual()
static int Capa.DAL.IntentoDB.ObtenerNumeroDeIntentoActual () static
Usado para saber que numero de intento va y asignar un id
Returns
Retorna el id máximo en la tabla + 1
Definition at line 38 of file IntentoDB.cs.
        {
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                int id;
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_UltimoIDIntento";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    id = (int)dr["IDIntento"];
                    return id + 1;
                }
            }
            return 1;
        }
References FactoryDatabase.CreateDefaultDataBase(), and IDataBase.ExecuteDataSet().
Referenced by Capa.BLL.IntentoLN.ObtenerNumeroDeIntentoActual().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/IntentoDB.cs