DBACreator: UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable Class Reference
UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable Class Reference
Represents the strongly named DataTable class. /summary>
Public Member Functions
PA_DatosCertificacionDataTable ()
void AddPA_DatosCertificacionRow (PA_DatosCertificacionRow row)
PA_DatosCertificacionRow AddPA_DatosCertificacionRow (string Nombre, string Apellido, int IDCliente, string Descripcion)
PA_DatosCertificacionRow FindByIDCliente (int IDCliente)
override global::System.Data.DataTable Clone ()
PA_DatosCertificacionRow NewPA_DatosCertificacionRow ()
void RemovePA_DatosCertificacionRow (PA_DatosCertificacionRow row)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
PA_DatosCertificacionDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override global::System.Data.DataTable CreateInstance ()
override global::System.Data.DataRow NewRowFromBuilder (global::System.Data.DataRowBuilder builder)
override global::System.Type GetRowType ()
override void OnRowChanged (global::System.Data.DataRowChangeEventArgs e)
override void OnRowChanging (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleted (global::System.Data.DataRowChangeEventArgs e)
override void OnRowDeleting (global::System.Data.DataRowChangeEventArgs e)
Package Functions
PA_DatosCertificacionDataTable (global::System.Data.DataTable table)
void InitVars ()
Properties
global::System.Data.DataColumn NombreColumn [get]
global::System.Data.DataColumn ApellidoColumn [get]
global::System.Data.DataColumn IDClienteColumn [get]
global::System.Data.DataColumn DescripcionColumn [get]
int Count [get]
PA_DatosCertificacionRow this[int index] [get]
Events
PA_DatosCertificacionRowChangeEventHandler PA_DatosCertificacionRowChanging
PA_DatosCertificacionRowChangeEventHandler PA_DatosCertificacionRowChanged
PA_DatosCertificacionRowChangeEventHandler PA_DatosCertificacionRowDeleting
PA_DatosCertificacionRowChangeEventHandler PA_DatosCertificacionRowDeleted
Private Member Functions
void InitClass ()
Private Attributes
global::System.Data.DataColumn columnNombre
global::System.Data.DataColumn columnApellido
global::System.Data.DataColumn columnIDCliente
global::System.Data.DataColumn columnDescripcion
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 956 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
PA_DatosCertificacionDataTable() [1/3]
UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable ()
Definition at line 968 of file DataSetReportes.Designer.cs.
{
                this.TableName = "PA_DatosCertificacion";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass().
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.Clone(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.CreateInstance().
PA_DatosCertificacionDataTable() [2/3]
UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable (global::System.Data.DataTable table) package
Definition at line 977 of file DataSetReportes.Designer.cs.
{
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
PA_DatosCertificacionDataTable() [3/3]
UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 994 of file DataSetReportes.Designer.cs.
                                                                                                                                                                             :
                    base(info, context) {
                this.InitVars();
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars().
Member Function Documentation
AddPA_DatosCertificacionRow() [1/2]
void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.AddPA_DatosCertificacionRow (PA_DatosCertificacionRow row)
Definition at line 1062 of file DataSetReportes.Designer.cs.
{
                this.Rows.Add(row);
            }
AddPA_DatosCertificacionRow() [2/2]
PA_DatosCertificacionRow UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.AddPA_DatosCertificacionRow (string Nombre, string Apellido, int IDCliente, string Descripcion)
Definition at line 1068 of file DataSetReportes.Designer.cs.
{
                PA_DatosCertificacionRow rowPA_DatosCertificacionRow = ((PA_DatosCertificacionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Nombre,
                        Apellido,
                        IDCliente,
                        Descripcion};
                rowPA_DatosCertificacionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowPA_DatosCertificacionRow);
                return rowPA_DatosCertificacionRow;
            }
Clone()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.Clone ()
Definition at line 1089 of file DataSetReportes.Designer.cs.
{
                PA_DatosCertificacionDataTable cln = ((PA_DatosCertificacionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable().
CreateInstance()
override global.System.Data.DataTable UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.CreateInstance () protected
Definition at line 1097 of file DataSetReportes.Designer.cs.
{
                return new PA_DatosCertificacionDataTable();
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable().
FindByIDCliente()
PA_DatosCertificacionRow UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.FindByIDCliente (int IDCliente)
Definition at line 1082 of file DataSetReportes.Designer.cs.
{
                return ((PA_DatosCertificacionRow)(this.Rows.Find(new object[] {
                            IDCliente})));
            }
GetRowType()
override global.System.Type UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.GetRowType () protected
Definition at line 1147 of file DataSetReportes.Designer.cs.
{
                return typeof(PA_DatosCertificacionRow);
            }
GetTypedTableSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.GetTypedTableSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 1195 of file DataSetReportes.Designer.cs.
{
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSetReportes ds = new DataSetReportes();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "PA_DatosCertificacionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length)
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass () private
Definition at line 1112 of file DataSetReportes.Designer.cs.
{
                this.columnNombre = new global::System.Data.DataColumn("Nombre", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNombre);
                this.columnApellido = new global::System.Data.DataColumn("Apellido", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnApellido);
                this.columnIDCliente = new global::System.Data.DataColumn("IDCliente", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIDCliente);
                this.columnDescripcion = new global::System.Data.DataColumn("Descripcion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDescripcion);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnIDCliente}, true));
                this.columnNombre.AllowDBNull = false;
                this.columnNombre.MaxLength = 50;
                this.columnApellido.AllowDBNull = false;
                this.columnApellido.MaxLength = 50;
                this.columnIDCliente.AllowDBNull = false;
                this.columnIDCliente.Unique = true;
                this.columnDescripcion.AllowDBNull = false;
                this.columnDescripcion.MaxLength = 50;
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnDescripcion, UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnIDCliente, and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnNombre.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable().
InitVars()
void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars () package
Definition at line 1103 of file DataSetReportes.Designer.cs.
{
                this.columnNombre = base.Columns["Nombre"];
                this.columnApellido = base.Columns["Apellido"];
                this.columnIDCliente = base.Columns["IDCliente"];
                this.columnDescripcion = base.Columns["Descripcion"];
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnApellido, UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnDescripcion, UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnIDCliente, and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnNombre.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.Clone(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionDataTable().
NewPA_DatosCertificacionRow()
PA_DatosCertificacionRow UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.NewPA_DatosCertificacionRow ()
Definition at line 1135 of file DataSetReportes.Designer.cs.
{
                return ((PA_DatosCertificacionRow)(this.NewRow()));
            }
NewRowFromBuilder()
override global.System.Data.DataRow UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.NewRowFromBuilder (global::System.Data.DataRowBuilder builder) protected
Definition at line 1141 of file DataSetReportes.Designer.cs.
{
                return new PA_DatosCertificacionRow(builder);
            }
OnRowChanged()
override void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowChanged (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1153 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanged(e);
                if ((this.PA_DatosCertificacionRowChanged != null)) {
                    this.PA_DatosCertificacionRowChanged(this, new PA_DatosCertificacionRowChangeEvent(((PA_DatosCertificacionRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowChanged.
OnRowChanging()
override void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowChanging (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1162 of file DataSetReportes.Designer.cs.
{
                base.OnRowChanging(e);
                if ((this.PA_DatosCertificacionRowChanging != null)) {
                    this.PA_DatosCertificacionRowChanging(this, new PA_DatosCertificacionRowChangeEvent(((PA_DatosCertificacionRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowChanging.
OnRowDeleted()
override void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowDeleted (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1171 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleted(e);
                if ((this.PA_DatosCertificacionRowDeleted != null)) {
                    this.PA_DatosCertificacionRowDeleted(this, new PA_DatosCertificacionRowChangeEvent(((PA_DatosCertificacionRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowDeleted.
OnRowDeleting()
override void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowDeleting (global::System.Data.DataRowChangeEventArgs e) protected
Definition at line 1180 of file DataSetReportes.Designer.cs.
{
                base.OnRowDeleting(e);
                if ((this.PA_DatosCertificacionRowDeleting != null)) {
                    this.PA_DatosCertificacionRowDeleting(this, new PA_DatosCertificacionRowChangeEvent(((PA_DatosCertificacionRow)(e.Row)), e.Action));
                }
            }
References UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowDeleting.
RemovePA_DatosCertificacionRow()
void UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.RemovePA_DatosCertificacionRow (PA_DatosCertificacionRow row)
Definition at line 1189 of file DataSetReportes.Designer.cs.
{
                this.Rows.Remove(row);
            }
Member Data Documentation
columnApellido
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnApellido private
Definition at line 960 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars().
columnDescripcion
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnDescripcion private
Definition at line 964 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars().
columnIDCliente
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnIDCliente private
Definition at line 962 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars().
columnNombre
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.columnNombre private
Definition at line 958 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitClass(), and UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars().
Property Documentation
ApellidoColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.ApellidoColumn get
Definition at line 1009 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnApellido;
                }
            }
Count
int UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.Count get
Definition at line 1034 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.Rows.Count;
                }
            }
DescripcionColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.DescripcionColumn get
Definition at line 1025 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnDescripcion;
                }
            }
IDClienteColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.IDClienteColumn get
Definition at line 1017 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnIDCliente;
                }
            }
NombreColumn
global.System.Data.DataColumn UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.NombreColumn get
Definition at line 1001 of file DataSetReportes.Designer.cs.
{
                get {
                    return this.columnNombre;
                }
            }
this[int index]
PA_DatosCertificacionRow UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.this[int index] get
Definition at line 1042 of file DataSetReportes.Designer.cs.
{
                get {
                    return ((PA_DatosCertificacionRow)(this.Rows[index]));
                }
            }
Event Documentation
PA_DatosCertificacionRowChanged
PA_DatosCertificacionRowChangeEventHandler UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowChanged
Definition at line 1052 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowChanged().
PA_DatosCertificacionRowChanging
PA_DatosCertificacionRowChangeEventHandler UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowChanging
Definition at line 1049 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowChanging().
PA_DatosCertificacionRowDeleted
PA_DatosCertificacionRowChangeEventHandler UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowDeleted
Definition at line 1058 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowDeleted().
PA_DatosCertificacionRowDeleting
PA_DatosCertificacionRowChangeEventHandler UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.PA_DatosCertificacionRowDeleting
Definition at line 1055 of file DataSetReportes.Designer.cs.
Referenced by UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.OnRowDeleting().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs