DBACreator: Capa.BLL.CertificacionLN Class Reference
Capa.BLL.CertificacionLN Class Reference
Public Member Functions
void Guardar (Certificacion c)
Método que guarda la certificacion en la base de datos, si encuentra un dato con ese ID, lo edita
Certificacion ObtenerPorID (int id)
Retorna de la tabla Certificación el dato con el ID buscado
List< Certificacion > ObtenerTodos ()
Método para obtener todos los datos de la tabla Certificación
void Borrar (int id)
Borra el dato de la tabla con el ID enviado
void Guardar (Certificacion c)
Certificacion ObtenerPorID (int id)
List< Certificacion > ObtenerTodos ()
void Borrar (int id)
Detailed Description
Definition at line 11 of file CertificacionLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.CertificacionLN.Borrar (int id)
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Implements Capa.BLL.ICertificacionLN.
Definition at line 52 of file CertificacionLN.cs.
        {
            CertificacionDB.Borrar(id);
        }
References Capa.DAL.CertificacionDB.Borrar().
Guardar()
void Capa.BLL.CertificacionLN.Guardar (Certificacion c)
Método que guarda la certificacion en la base de datos, si encuentra un dato con ese ID, lo edita
Parameters
c Certificación del cuál extraerá los datos
Implements Capa.BLL.ICertificacionLN.
Definition at line 17 of file CertificacionLN.cs.
        {
            if (ObtenerPorID(c.Id) == null)
            {
                CertificacionDB.AgregarCertificacion(c);
            } else
            {
                CertificacionDB.Actualizar(c);
            }
        }
References Capa.DAL.CertificacionDB.Actualizar(), Capa.DAL.CertificacionDB.AgregarCertificacion(), Capa.Entities.Certificacion.Id, and Capa.BLL.CertificacionLN.ObtenerPorID().
ObtenerPorID()
Certificacion Capa.BLL.CertificacionLN.ObtenerPorID (int id)
Retorna de la tabla Certificación el dato con el ID buscado
Parameters
id ID a buscar
Returns
Implements Capa.BLL.ICertificacionLN.
Definition at line 33 of file CertificacionLN.cs.
        {
            return CertificacionDB.SeleccionarPorId(id);
        }
References Capa.DAL.CertificacionDB.SeleccionarPorId().
Referenced by Capa.BLL.CertificacionLN.Guardar().
ObtenerTodos()
List< Certificacion > Capa.BLL.CertificacionLN.ObtenerTodos ()
Método para obtener todos los datos de la tabla Certificación
Returns
Retorna una lista con todos los datos de la tabla Certificacion
Implements Capa.BLL.ICertificacionLN.
Definition at line 43 of file CertificacionLN.cs.
        {
            return CertificacionDB.ObtenerTodos();
        }
References Capa.DAL.CertificacionDB.ObtenerTodos().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/CertificacionLN.cs