DBACreator: Capa.DAL.PaisDB Class Reference
Capa.DAL.PaisDB Class Reference
Static Public Member Functions
static List< Pais > ObtenerTodos ()
Usado para ver todos los países
Detailed Description
Definition at line 12 of file PaisDB.cs.
Member Function Documentation
ObtenerTodos()
static List< Pais > Capa.DAL.PaisDB.ObtenerTodos () static
Usado para ver todos los países
Returns
retorna una lista con todos los países
Definition at line 18 of file PaisDB.cs.
        {
            List<Pais> lista = new List<Pais>();
            using (IDataBase db = FactoryDatabase.CreateDefaultDataBase())
            {
                SqlCommand comando = new SqlCommand();
                comando.CommandType = System.Data.CommandType.StoredProcedure;
                comando.CommandText = "PA_SeleccionarPaises";
                DataSet ds = db.ExecuteDataSet(comando);
                foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    Pais p = new Pais();
                    p.Nombre = dr["Nombre"].ToString();
                    lista.Add(p);
                }
            }
            return lista;
        }
References FactoryDatabase.CreateDefaultDataBase(), IDataBase.ExecuteDataSet(), and Capa.Entities.Pais.Nombre.
Referenced by Capa.BLL.PaisLN.ObtenerTodos().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.DAL/PaisDB.cs