DBACreator: UI.Reportes.DataSetReportes Class Reference
UI.Reportes.DataSetReportes Class Reference
Represents a strongly typed in-memory cache of data. /summary>
Classes
class PA_DatosCertificacionDataTable
Represents the strongly named DataTable class. /summary>
class PA_DatosCertificacionRow
Represents strongly named DataRow class. /summary>
class PA_DatosCertificacionRowChangeEvent
Row event argument class /summary>
class PA_ReporteClientesCertificadosDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteClientesCertificadosRow
Represents strongly named DataRow class. /summary>
class PA_ReporteClientesCertificadosRowChangeEvent
Row event argument class /summary>
class PA_ReporteClientesDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteClientesNombreDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteClientesNombreRow
Represents strongly named DataRow class. /summary>
class PA_ReporteClientesNombreRowChangeEvent
Row event argument class /summary>
class PA_ReporteClientesRow
Represents strongly named DataRow class. /summary>
class PA_ReporteClientesRowChangeEvent
Row event argument class /summary>
class PA_ReporteExamenesRealizadosDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteExamenesRealizadosRow
Represents strongly named DataRow class. /summary>
class PA_ReporteExamenesRealizadosRowChangeEvent
Row event argument class /summary>
class PA_ReporteGraficoDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteGraficoRow
Represents strongly named DataRow class. /summary>
class PA_ReporteGraficoRowChangeEvent
Row event argument class /summary>
class PA_ReporteVentasDataTable
Represents the strongly named DataTable class. /summary>
class PA_ReporteVentasRow
Represents strongly named DataRow class. /summary>
class PA_ReporteVentasRowChangeEvent
Row event argument class /summary>
class PA_SeleccionarDetallesPorFacturaDataTable
Represents the strongly named DataTable class. /summary>
class PA_SeleccionarDetallesPorFacturaRow
Represents strongly named DataRow class. /summary>
class PA_SeleccionarDetallesPorFacturaRowChangeEvent
Row event argument class /summary>
Public Member Functions
DataSetReportes ()
override global::System.Data.DataSet Clone ()
delegate void PA_SeleccionarDetallesPorFacturaRowChangeEventHandler (object sender, PA_SeleccionarDetallesPorFacturaRowChangeEvent e)
delegate void PA_DatosCertificacionRowChangeEventHandler (object sender, PA_DatosCertificacionRowChangeEvent e)
delegate void PA_ReporteClientesNombreRowChangeEventHandler (object sender, PA_ReporteClientesNombreRowChangeEvent e)
delegate void PA_ReporteVentasRowChangeEventHandler (object sender, PA_ReporteVentasRowChangeEvent e)
delegate void PA_ReporteExamenesRealizadosRowChangeEventHandler (object sender, PA_ReporteExamenesRealizadosRowChangeEvent e)
delegate void PA_ReporteClientesRowChangeEventHandler (object sender, PA_ReporteClientesRowChangeEvent e)
delegate void PA_ReporteClientesCertificadosRowChangeEventHandler (object sender, PA_ReporteClientesCertificadosRowChangeEvent e)
delegate void PA_ReporteGraficoRowChangeEventHandler (object sender, PA_ReporteGraficoRowChangeEvent e)
Static Public Member Functions
static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema (global::System.Xml.Schema.XmlSchemaSet xs)
Protected Member Functions
DataSetReportes (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context)
override void InitializeDerivedDataSet ()
override bool ShouldSerializeTables ()
override bool ShouldSerializeRelations ()
override void ReadXmlSerializable (global::System.Xml.XmlReader reader)
override global::System.Xml.Schema.XmlSchema GetSchemaSerializable ()
Package Functions
void InitVars ()
void InitVars (bool initTable)
Properties
PA_SeleccionarDetallesPorFacturaDataTable PA_SeleccionarDetallesPorFactura [get]
PA_DatosCertificacionDataTable PA_DatosCertificacion [get]
PA_ReporteClientesNombreDataTable PA_ReporteClientesNombre [get]
PA_ReporteVentasDataTable PA_ReporteVentas [get]
PA_ReporteExamenesRealizadosDataTable PA_ReporteExamenesRealizados [get]
PA_ReporteClientesDataTable PA_ReporteClientes [get]
PA_ReporteClientesCertificadosDataTable PA_ReporteClientesCertificados [get]
PA_ReporteGraficoDataTable PA_ReporteGrafico [get]
override global::System.Data.SchemaSerializationMode SchemaSerializationMode [get, set]
new global::System.Data.DataTableCollection Tables [get]
new global::System.Data.DataRelationCollection Relations [get]
Private Member Functions
void InitClass ()
bool ShouldSerializePA_SeleccionarDetallesPorFactura ()
bool ShouldSerializePA_DatosCertificacion ()
bool ShouldSerializePA_ReporteClientesNombre ()
bool ShouldSerializePA_ReporteVentas ()
bool ShouldSerializePA_ReporteExamenesRealizados ()
bool ShouldSerializePA_ReporteClientes ()
bool ShouldSerializePA_ReporteClientesCertificados ()
bool ShouldSerializePA_ReporteGrafico ()
void SchemaChanged (object sender, global::System.ComponentModel.CollectionChangeEventArgs e)
Private Attributes
PA_SeleccionarDetallesPorFacturaDataTable tablePA_SeleccionarDetallesPorFactura
PA_DatosCertificacionDataTable tablePA_DatosCertificacion
PA_ReporteClientesNombreDataTable tablePA_ReporteClientesNombre
PA_ReporteVentasDataTable tablePA_ReporteVentas
PA_ReporteExamenesRealizadosDataTable tablePA_ReporteExamenesRealizados
PA_ReporteClientesDataTable tablePA_ReporteClientes
PA_ReporteClientesCertificadosDataTable tablePA_ReporteClientesCertificados
PA_ReporteGraficoDataTable tablePA_ReporteGrafico
global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema
Detailed Description
Represents a strongly typed in-memory cache of data. /summary>
Definition at line 25 of file DataSetReportes.Designer.cs.
Constructor & Destructor Documentation
DataSetReportes() [1/2]
UI.Reportes.DataSetReportes.DataSetReportes ()
Definition at line 47 of file DataSetReportes.Designer.cs.
{
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
References UI.Reportes.DataSetReportes.InitClass(), and UI.Reportes.DataSetReportes.SchemaChanged().
Referenced by UI.Reportes.DataSetReportes.Clone(), UI.Reportes.DataSetReportes.GetTypedDataSetSchema(), UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFacturaDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesNombreDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.GetTypedTableSchema(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.GetTypedTableSchema().
DataSetReportes() [2/2]
UI.Reportes.DataSetReportes.DataSetReportes (global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) protected
Definition at line 58 of file DataSetReportes.Designer.cs.
                                                                                                                                                          :
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["PA_SeleccionarDetallesPorFactura"] != null)) {
                    base.Tables.Add(new PA_SeleccionarDetallesPorFacturaDataTable(ds.Tables["PA_SeleccionarDetallesPorFactura"]));
                }
                if ((ds.Tables["PA_DatosCertificacion"] != null)) {
                    base.Tables.Add(new PA_DatosCertificacionDataTable(ds.Tables["PA_DatosCertificacion"]));
                }
                if ((ds.Tables["PA_ReporteClientesNombre"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesNombreDataTable(ds.Tables["PA_ReporteClientesNombre"]));
                }
                if ((ds.Tables["PA_ReporteVentas"] != null)) {
                    base.Tables.Add(new PA_ReporteVentasDataTable(ds.Tables["PA_ReporteVentas"]));
                }
                if ((ds.Tables["PA_ReporteExamenesRealizados"] != null)) {
                    base.Tables.Add(new PA_ReporteExamenesRealizadosDataTable(ds.Tables["PA_ReporteExamenesRealizados"]));
                }
                if ((ds.Tables["PA_ReporteClientes"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesDataTable(ds.Tables["PA_ReporteClientes"]));
                }
                if ((ds.Tables["PA_ReporteClientesCertificados"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesCertificadosDataTable(ds.Tables["PA_ReporteClientesCertificados"]));
                }
                if ((ds.Tables["PA_ReporteGrafico"] != null)) {
                    base.Tables.Add(new PA_ReporteGraficoDataTable(ds.Tables["PA_ReporteGrafico"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
References UI.Reportes.DataSetReportes.InitVars(), UI.Reportes.DataSetReportes.Relations, UI.Reportes.DataSetReportes.SchemaChanged(), and UI.Reportes.DataSetReportes.Tables.
Member Function Documentation
Clone()
override global.System.Data.DataSet UI.Reportes.DataSetReportes.Clone ()
Definition at line 234 of file DataSetReportes.Designer.cs.
{
            DataSetReportes cln = ((DataSetReportes)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
References UI.Reportes.DataSetReportes.DataSetReportes(), UI.Reportes.DataSetReportes.InitVars(), and UI.Reportes.DataSetReportes.SchemaSerializationMode.
GetSchemaSerializable()
override global.System.Xml.Schema.XmlSchema UI.Reportes.DataSetReportes.GetSchemaSerializable () protected
Definition at line 301 of file DataSetReportes.Designer.cs.
{
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
Referenced by UI.Reportes.DataSetReportes.GetTypedDataSetSchema(), UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFacturaDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesNombreDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesDataTable.GetTypedTableSchema(), UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.GetTypedTableSchema(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.GetTypedTableSchema().
GetTypedDataSetSchema()
static global.System.Xml.Schema.XmlSchemaComplexType UI.Reportes.DataSetReportes.GetTypedDataSetSchema (global::System.Xml.Schema.XmlSchemaSet xs) static
Definition at line 451 of file DataSetReportes.Designer.cs.
{
            DataSetReportes ds = new DataSetReportes();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length)
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
References UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.GetSchemaSerializable().
InitClass()
void UI.Reportes.DataSetReportes.InitClass () private
Definition at line 369 of file DataSetReportes.Designer.cs.
{
            this.DataSetName = "DataSetReportes";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetReportes.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablePA_SeleccionarDetallesPorFactura = new PA_SeleccionarDetallesPorFacturaDataTable();
            base.Tables.Add(this.tablePA_SeleccionarDetallesPorFactura);
            this.tablePA_DatosCertificacion = new PA_DatosCertificacionDataTable();
            base.Tables.Add(this.tablePA_DatosCertificacion);
            this.tablePA_ReporteClientesNombre = new PA_ReporteClientesNombreDataTable();
            base.Tables.Add(this.tablePA_ReporteClientesNombre);
            this.tablePA_ReporteVentas = new PA_ReporteVentasDataTable();
            base.Tables.Add(this.tablePA_ReporteVentas);
            this.tablePA_ReporteExamenesRealizados = new PA_ReporteExamenesRealizadosDataTable();
            base.Tables.Add(this.tablePA_ReporteExamenesRealizados);
            this.tablePA_ReporteClientes = new PA_ReporteClientesDataTable();
            base.Tables.Add(this.tablePA_ReporteClientes);
            this.tablePA_ReporteClientesCertificados = new PA_ReporteClientesCertificadosDataTable();
            base.Tables.Add(this.tablePA_ReporteClientesCertificados);
            this.tablePA_ReporteGrafico = new PA_ReporteGraficoDataTable();
            base.Tables.Add(this.tablePA_ReporteGrafico);
        }
References UI.Reportes.DataSetReportes.SchemaSerializationMode.
Referenced by UI.Reportes.DataSetReportes.DataSetReportes(), and UI.Reportes.DataSetReportes.InitializeDerivedDataSet().
InitializeDerivedDataSet()
override void UI.Reportes.DataSetReportes.InitializeDerivedDataSet () protected
Definition at line 226 of file DataSetReportes.Designer.cs.
{
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
References UI.Reportes.DataSetReportes.InitClass().
InitVars() [1/2]
void UI.Reportes.DataSetReportes.InitVars () package
Definition at line 310 of file DataSetReportes.Designer.cs.
{
            this.InitVars(true);
        }
References UI.Reportes.DataSetReportes.InitVars().
Referenced by UI.Reportes.DataSetReportes.Clone(), UI.Reportes.DataSetReportes.DataSetReportes(), UI.Reportes.DataSetReportes.InitVars(), UI.Reportes.DataSetReportes.ReadXmlSerializable(), and UI.Reportes.DataSetReportes.SchemaChanged().
InitVars() [2/2]
void UI.Reportes.DataSetReportes.InitVars (bool initTable) package
Definition at line 316 of file DataSetReportes.Designer.cs.
{
            this.tablePA_SeleccionarDetallesPorFactura = ((PA_SeleccionarDetallesPorFacturaDataTable)(base.Tables["PA_SeleccionarDetallesPorFactura"]));
            if ((initTable == true)) {
                if ((this.tablePA_SeleccionarDetallesPorFactura != null)) {
                    this.tablePA_SeleccionarDetallesPorFactura.InitVars();
                }
            }
            this.tablePA_DatosCertificacion = ((PA_DatosCertificacionDataTable)(base.Tables["PA_DatosCertificacion"]));
            if ((initTable == true)) {
                if ((this.tablePA_DatosCertificacion != null)) {
                    this.tablePA_DatosCertificacion.InitVars();
                }
            }
            this.tablePA_ReporteClientesNombre = ((PA_ReporteClientesNombreDataTable)(base.Tables["PA_ReporteClientesNombre"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteClientesNombre != null)) {
                    this.tablePA_ReporteClientesNombre.InitVars();
                }
            }
            this.tablePA_ReporteVentas = ((PA_ReporteVentasDataTable)(base.Tables["PA_ReporteVentas"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteVentas != null)) {
                    this.tablePA_ReporteVentas.InitVars();
                }
            }
            this.tablePA_ReporteExamenesRealizados = ((PA_ReporteExamenesRealizadosDataTable)(base.Tables["PA_ReporteExamenesRealizados"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteExamenesRealizados != null)) {
                    this.tablePA_ReporteExamenesRealizados.InitVars();
                }
            }
            this.tablePA_ReporteClientes = ((PA_ReporteClientesDataTable)(base.Tables["PA_ReporteClientes"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteClientes != null)) {
                    this.tablePA_ReporteClientes.InitVars();
                }
            }
            this.tablePA_ReporteClientesCertificados = ((PA_ReporteClientesCertificadosDataTable)(base.Tables["PA_ReporteClientesCertificados"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteClientesCertificados != null)) {
                    this.tablePA_ReporteClientesCertificados.InitVars();
                }
            }
            this.tablePA_ReporteGrafico = ((PA_ReporteGraficoDataTable)(base.Tables["PA_ReporteGrafico"]));
            if ((initTable == true)) {
                if ((this.tablePA_ReporteGrafico != null)) {
                    this.tablePA_ReporteGrafico.InitVars();
                }
            }
        }
References UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFacturaDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_DatosCertificacionDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_ReporteClientesNombreDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_ReporteVentasDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_ReporteClientesDataTable.InitVars(), UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosDataTable.InitVars(), and UI.Reportes.DataSetReportes.PA_ReporteGraficoDataTable.InitVars().
PA_DatosCertificacionRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_DatosCertificacionRowChangeEventHandler (object sender, PA_DatosCertificacionRowChangeEvent e)
PA_ReporteClientesCertificadosRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteClientesCertificadosRowChangeEventHandler (object sender, PA_ReporteClientesCertificadosRowChangeEvent e)
PA_ReporteClientesNombreRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteClientesNombreRowChangeEventHandler (object sender, PA_ReporteClientesNombreRowChangeEvent e)
PA_ReporteClientesRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteClientesRowChangeEventHandler (object sender, PA_ReporteClientesRowChangeEvent e)
PA_ReporteExamenesRealizadosRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizadosRowChangeEventHandler (object sender, PA_ReporteExamenesRealizadosRowChangeEvent e)
PA_ReporteGraficoRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteGraficoRowChangeEventHandler (object sender, PA_ReporteGraficoRowChangeEvent e)
PA_ReporteVentasRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_ReporteVentasRowChangeEventHandler (object sender, PA_ReporteVentasRowChangeEvent e)
PA_SeleccionarDetallesPorFacturaRowChangeEventHandler()
delegate void UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFacturaRowChangeEventHandler (object sender, PA_SeleccionarDetallesPorFacturaRowChangeEvent e)
ReadXmlSerializable()
override void UI.Reportes.DataSetReportes.ReadXmlSerializable (global::System.Xml.XmlReader reader) protected
Definition at line 255 of file DataSetReportes.Designer.cs.
{
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["PA_SeleccionarDetallesPorFactura"] != null)) {
                    base.Tables.Add(new PA_SeleccionarDetallesPorFacturaDataTable(ds.Tables["PA_SeleccionarDetallesPorFactura"]));
                }
                if ((ds.Tables["PA_DatosCertificacion"] != null)) {
                    base.Tables.Add(new PA_DatosCertificacionDataTable(ds.Tables["PA_DatosCertificacion"]));
                }
                if ((ds.Tables["PA_ReporteClientesNombre"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesNombreDataTable(ds.Tables["PA_ReporteClientesNombre"]));
                }
                if ((ds.Tables["PA_ReporteVentas"] != null)) {
                    base.Tables.Add(new PA_ReporteVentasDataTable(ds.Tables["PA_ReporteVentas"]));
                }
                if ((ds.Tables["PA_ReporteExamenesRealizados"] != null)) {
                    base.Tables.Add(new PA_ReporteExamenesRealizadosDataTable(ds.Tables["PA_ReporteExamenesRealizados"]));
                }
                if ((ds.Tables["PA_ReporteClientes"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesDataTable(ds.Tables["PA_ReporteClientes"]));
                }
                if ((ds.Tables["PA_ReporteClientesCertificados"] != null)) {
                    base.Tables.Add(new PA_ReporteClientesCertificadosDataTable(ds.Tables["PA_ReporteClientesCertificados"]));
                }
                if ((ds.Tables["PA_ReporteGrafico"] != null)) {
                    base.Tables.Add(new PA_ReporteGraficoDataTable(ds.Tables["PA_ReporteGrafico"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
References UI.Reportes.DataSetReportes.InitVars().
SchemaChanged()
void UI.Reportes.DataSetReportes.SchemaChanged (object sender, global::System.ComponentModel.CollectionChangeEventArgs e) private
Definition at line 443 of file DataSetReportes.Designer.cs.
{
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
References UI.Reportes.DataSetReportes.InitVars().
Referenced by UI.Reportes.DataSetReportes.DataSetReportes().
ShouldSerializePA_DatosCertificacion()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_DatosCertificacion () private
Definition at line 401 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteClientes()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteClientes () private
Definition at line 425 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteClientesCertificados()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteClientesCertificados () private
Definition at line 431 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteClientesNombre()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteClientesNombre () private
Definition at line 407 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteExamenesRealizados()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteExamenesRealizados () private
Definition at line 419 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteGrafico()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteGrafico () private
Definition at line 437 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_ReporteVentas()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_ReporteVentas () private
Definition at line 413 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializePA_SeleccionarDetallesPorFactura()
bool UI.Reportes.DataSetReportes.ShouldSerializePA_SeleccionarDetallesPorFactura () private
Definition at line 395 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeRelations()
override bool UI.Reportes.DataSetReportes.ShouldSerializeRelations () protected
Definition at line 249 of file DataSetReportes.Designer.cs.
{
            return false;
        }
ShouldSerializeTables()
override bool UI.Reportes.DataSetReportes.ShouldSerializeTables () protected
Definition at line 243 of file DataSetReportes.Designer.cs.
{
            return false;
        }
Member Data Documentation
_schemaSerializationMode
global.System.Data.SchemaSerializationMode UI.Reportes.DataSetReportes._schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema private
Definition at line 43 of file DataSetReportes.Designer.cs.
tablePA_DatosCertificacion
PA_DatosCertificacionDataTable UI.Reportes.DataSetReportes.tablePA_DatosCertificacion private
Definition at line 29 of file DataSetReportes.Designer.cs.
tablePA_ReporteClientes
PA_ReporteClientesDataTable UI.Reportes.DataSetReportes.tablePA_ReporteClientes private
Definition at line 37 of file DataSetReportes.Designer.cs.
tablePA_ReporteClientesCertificados
PA_ReporteClientesCertificadosDataTable UI.Reportes.DataSetReportes.tablePA_ReporteClientesCertificados private
Definition at line 39 of file DataSetReportes.Designer.cs.
tablePA_ReporteClientesNombre
PA_ReporteClientesNombreDataTable UI.Reportes.DataSetReportes.tablePA_ReporteClientesNombre private
Definition at line 31 of file DataSetReportes.Designer.cs.
tablePA_ReporteExamenesRealizados
PA_ReporteExamenesRealizadosDataTable UI.Reportes.DataSetReportes.tablePA_ReporteExamenesRealizados private
Definition at line 35 of file DataSetReportes.Designer.cs.
tablePA_ReporteGrafico
PA_ReporteGraficoDataTable UI.Reportes.DataSetReportes.tablePA_ReporteGrafico private
Definition at line 41 of file DataSetReportes.Designer.cs.
tablePA_ReporteVentas
PA_ReporteVentasDataTable UI.Reportes.DataSetReportes.tablePA_ReporteVentas private
Definition at line 33 of file DataSetReportes.Designer.cs.
tablePA_SeleccionarDetallesPorFactura
PA_SeleccionarDetallesPorFacturaDataTable UI.Reportes.DataSetReportes.tablePA_SeleccionarDetallesPorFactura private
Definition at line 27 of file DataSetReportes.Designer.cs.
Property Documentation
PA_DatosCertificacion
PA_DatosCertificacionDataTable UI.Reportes.DataSetReportes.PA_DatosCertificacion get
Definition at line 127 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_DatosCertificacion;
            }
        }
Referenced by UI.Reportes.FrmCertificado.FrmCertificado_Load().
PA_ReporteClientes
PA_ReporteClientesDataTable UI.Reportes.DataSetReportes.PA_ReporteClientes get
Definition at line 167 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteClientes;
            }
        }
Referenced by UI.Reportes.FrmReporteClientes.toolStripBtnBuscar_Click().
PA_ReporteClientesCertificados
PA_ReporteClientesCertificadosDataTable UI.Reportes.DataSetReportes.PA_ReporteClientesCertificados get
Definition at line 177 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteClientesCertificados;
            }
        }
Referenced by UI.Reportes.FrmClientesCertificados.toolStripBtnBuscar_Click().
PA_ReporteClientesNombre
PA_ReporteClientesNombreDataTable UI.Reportes.DataSetReportes.PA_ReporteClientesNombre get
Definition at line 137 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteClientesNombre;
            }
        }
PA_ReporteExamenesRealizados
PA_ReporteExamenesRealizadosDataTable UI.Reportes.DataSetReportes.PA_ReporteExamenesRealizados get
Definition at line 157 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteExamenesRealizados;
            }
        }
Referenced by UI.Reportes.FrmReporteExamenes.toolStripBtnBuscar_Click().
PA_ReporteGrafico
PA_ReporteGraficoDataTable UI.Reportes.DataSetReportes.PA_ReporteGrafico get
Definition at line 187 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteGrafico;
            }
        }
Referenced by UI.Reportes.FrmReporteGrafico.FrmReporteGrafico_Load().
PA_ReporteVentas
PA_ReporteVentasDataTable UI.Reportes.DataSetReportes.PA_ReporteVentas get
Definition at line 147 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_ReporteVentas;
            }
        }
Referenced by UI.Reportes.FrmReporteVentas.btnBuscar_Click().
PA_SeleccionarDetallesPorFactura
PA_SeleccionarDetallesPorFacturaDataTable UI.Reportes.DataSetReportes.PA_SeleccionarDetallesPorFactura get
Definition at line 117 of file DataSetReportes.Designer.cs.
{
            get {
                return this.tablePA_SeleccionarDetallesPorFactura;
            }
        }
Referenced by UI.Reportes.ReporteFactura.ReporteFactura_Load().
Relations
new global.System.Data.DataRelationCollection UI.Reportes.DataSetReportes.Relations get
Definition at line 218 of file DataSetReportes.Designer.cs.
{
            get {
                return base.Relations;
            }
        }
Referenced by UI.Reportes.DataSetReportes.DataSetReportes().
SchemaSerializationMode
override global.System.Data.SchemaSerializationMode UI.Reportes.DataSetReportes.SchemaSerializationMode get set
Definition at line 197 of file DataSetReportes.Designer.cs.
{
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
Referenced by UI.Reportes.DataSetReportes.Clone(), UI.Reportes.DataSetReportes.InitClass(), UI.Reportes.FrmCertificado.InitializeComponent(), UI.Reportes.FrmClientesCertificados.InitializeComponent(), UI.Reportes.FrmReporteClientes.InitializeComponent(), UI.Reportes.FrmReporteExamenes.InitializeComponent(), UI.Reportes.FrmReporteGrafico.InitializeComponent(), UI.Reportes.FrmReporteVentas.InitializeComponent(), and UI.Reportes.ReporteFactura.InitializeComponent().
Tables
new global.System.Data.DataTableCollection UI.Reportes.DataSetReportes.Tables get
Definition at line 209 of file DataSetReportes.Designer.cs.
{
            get {
                return base.Tables;
            }
        }
Referenced by UI.Reportes.DataSetReportes.DataSetReportes().
The documentation for this class was generated from the following file:
118710756/DbaCreator/UI/Reportes/DataSetReportes.Designer.cs