DBACreator: UI.Reportes.FrmCertificado Class Reference
UI.Reportes.FrmCertificado Class Reference
Public Member Functions
FrmCertificado (int idIntento, string correoC)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void FrmCertificado_Load (object sender, EventArgs e)
Intenta cargar el reporte para que sea visible
void toolStripBtnSalir_Click (object sender, EventArgs e)
Cierra la ventana
void toolStripBtnExportarPDF_Click (object sender, EventArgs e)
Exporta el pdf
void toolStripBtnMail_Click (object sender, EventArgs e)
Envía el mail al correo del usuario
void GenerarPDF ()
Método que genera el pdf de la certificación
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int idIntento
string correo
string ruta
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnExportarPDF
System.Windows.Forms.ToolStripButton toolStripBtnSalir
Microsoft.Reporting.WinForms.ReportViewer reportViewer1
System.Windows.Forms.BindingSource PA_DatosCertificacionBindingSource
DataSetReportes DataSetReportes
DataSetReportesTableAdapters.PA_DatosCertificacionTableAdapter PA_DatosCertificacionTableAdapter
System.Windows.Forms.ToolStripButton toolStripBtnMail
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 19 of file FrmCertificado.cs.
Constructor & Destructor Documentation
FrmCertificado()
UI.Reportes.FrmCertificado.FrmCertificado (int idIntento, string correoC)
Definition at line 25 of file FrmCertificado.cs.
        {
            InitializeComponent();
            this.idIntento = idIntento;
            this.correo = correoC;
        }
References UI.Reportes.FrmCertificado.idIntento, and UI.Reportes.FrmCertificado.InitializeComponent().
Member Function Documentation
Dispose()
override void UI.Reportes.FrmCertificado.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file FrmCertificado.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Reportes.FrmCertificado.components.
FrmCertificado_Load()
void UI.Reportes.FrmCertificado.FrmCertificado_Load (object sender, EventArgs e) private
Intenta cargar el reporte para que sea visible
Parameters
sender
e
Definition at line 37 of file FrmCertificado.cs.
        {
            try
            {
                // TODO: This line of code loads data into the 'DataSetReportes.PA_DatosCertificacion' table. You can move, or remove it, as needed.
                this.PA_DatosCertificacionTableAdapter.Fill(this.DataSetReportes.PA_DatosCertificacion, idIntento);
                this.reportViewer1.RefreshReport();
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el certificado: " + er.Message);
            }
        }
References UI.Reportes.FrmCertificado._MyLogControlEventos, UI.Reportes.FrmCertificado.idIntento, UI.Reportes.DataSetReportes.PA_DatosCertificacion, UI.Reportes.FrmCertificado.PA_DatosCertificacionTableAdapter, and UI.Reportes.FrmCertificado.reportViewer1.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
GenerarPDF()
void UI.Reportes.FrmCertificado.GenerarPDF () private
Método que genera el pdf de la certificación
Definition at line 124 of file FrmCertificado.cs.
        {
            ruta = $@"c:\temp\Certificado {idIntento}.pdf";
            if (!Directory.Exists(@"c:\temp"))
                Directory.CreateDirectory(@"c:\temp");
            byte[] Bytes = this.reportViewer1.LocalReport.Render(format: "PDF", deviceInfo: @"<DeviceInfo> <EmbedFonts>None</EmbedFonts> </DeviceInfo>");
            using (FileStream stream = new FileStream(ruta, FileMode.Create))
            {
                stream.Write(Bytes, 0, Bytes.Length);
            }
            Process.Start(ruta);
            _MyLogControlEventos.Info($"PDF Generado");
        }
References UI.Reportes.FrmCertificado._MyLogControlEventos, UI.Reportes.FrmCertificado.reportViewer1, and UI.Reportes.FrmCertificado.ruta.
Referenced by UI.Reportes.FrmCertificado.toolStripBtnExportarPDF_Click(), and UI.Reportes.FrmCertificado.toolStripBtnMail_Click().
InitializeComponent()
void UI.Reportes.FrmCertificado.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file FrmCertificado.Designer.cs.
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmCertificado));
            Microsoft.Reporting.WinForms.ReportDataSource reportDataSource1 = new Microsoft.Reporting.WinForms.ReportDataSource();
            this.PA_DatosCertificacionBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.DataSetReportes = new UI.Reportes.DataSetReportes();
            this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
            this.toolStripBtnMail = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnExportarPDF = new System.Windows.Forms.ToolStripButton();
            this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
            this.reportViewer1 = new Microsoft.Reporting.WinForms.ReportViewer();
            this.PA_DatosCertificacionTableAdapter = new UI.Reportes.DataSetReportesTableAdapters.PA_DatosCertificacionTableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.PA_DatosCertificacionBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).BeginInit();
            this.tspBarraSuperior.SuspendLayout();
            this.SuspendLayout();
            //
            // PA_DatosCertificacionBindingSource
            //
            this.PA_DatosCertificacionBindingSource.DataMember = "PA_DatosCertificacion";
            this.PA_DatosCertificacionBindingSource.DataSource = this.DataSetReportes;
            //
            // DataSetReportes
            //
            this.DataSetReportes.DataSetName = "DataSetReportes";
            this.DataSetReportes.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            //
            // tspBarraSuperior
            //
            this.tspBarraSuperior.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripBtnMail,
            this.toolStripBtnExportarPDF,
            this.toolStripBtnSalir});
            this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
            this.tspBarraSuperior.Name = "tspBarraSuperior";
            this.tspBarraSuperior.Size = new System.Drawing.Size(942, 55);
            this.tspBarraSuperior.TabIndex = 3;
            this.tspBarraSuperior.Text = "toolStrip1";
            //
            // toolStripBtnMail
            //
            this.toolStripBtnMail.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnMail.Image")));
            this.toolStripBtnMail.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnMail.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnMail.Name = "toolStripBtnMail";
            this.toolStripBtnMail.Size = new System.Drawing.Size(239, 52);
            this.toolStripBtnMail.Text = "Enviar al Correo Registrado";
            this.toolStripBtnMail.Click += new System.EventHandler(this.toolStripBtnMail_Click);
            //
            // toolStripBtnExportarPDF
            //
            this.toolStripBtnExportarPDF.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnExportarPDF.Image")));
            this.toolStripBtnExportarPDF.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnExportarPDF.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnExportarPDF.Name = "toolStripBtnExportarPDF";
            this.toolStripBtnExportarPDF.Size = new System.Drawing.Size(147, 52);
            this.toolStripBtnExportarPDF.Text = "Exportar PDF";
            this.toolStripBtnExportarPDF.Click += new System.EventHandler(this.toolStripBtnExportarPDF_Click);
            //
            // toolStripBtnSalir
            //
            this.toolStripBtnSalir.Image = ((System.Drawing.Image)(resources.GetObject("toolStripBtnSalir.Image")));
            this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripBtnSalir.Name = "toolStripBtnSalir";
            this.toolStripBtnSalir.Size = new System.Drawing.Size(90, 52);
            this.toolStripBtnSalir.Text = "Salir";
            this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
            //
            // reportViewer1
            //
            this.reportViewer1.Dock = System.Windows.Forms.DockStyle.Fill;
            reportDataSource1.Name = "DataSetCertificado";
            reportDataSource1.Value = this.PA_DatosCertificacionBindingSource;
            this.reportViewer1.LocalReport.DataSources.Add(reportDataSource1);
            this.reportViewer1.LocalReport.ReportEmbeddedResource = "UI.Reportes.ReporteCertificacion.rdlc";
            this.reportViewer1.Location = new System.Drawing.Point(0, 55);
            this.reportViewer1.Name = "reportViewer1";
            this.reportViewer1.ServerReport.BearerToken = null;
            this.reportViewer1.Size = new System.Drawing.Size(942, 497);
            this.reportViewer1.TabIndex = 4;
            //
            // PA_DatosCertificacionTableAdapter
            //
            this.PA_DatosCertificacionTableAdapter.ClearBeforeFill = true;
            //
            // FrmCertificado
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(942, 552);
            this.Controls.Add(this.reportViewer1);
            this.Controls.Add(this.tspBarraSuperior);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Name = "FrmCertificado";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Certificado";
            this.Load += new System.EventHandler(this.FrmCertificado_Load);
            ((System.ComponentModel.ISupportInitialize)(this.PA_DatosCertificacionBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.DataSetReportes)).EndInit();
            this.tspBarraSuperior.ResumeLayout(false);
            this.tspBarraSuperior.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Reportes.FrmCertificado.components, UI.Reportes.FrmCertificado.DataSetReportes, UI.Reportes.FrmCertificado.FrmCertificado_Load(), UI.Reportes.FrmCertificado.PA_DatosCertificacionBindingSource, UI.Reportes.FrmCertificado.PA_DatosCertificacionTableAdapter, UI.Reportes.FrmCertificado.reportViewer1, UI.Reportes.DataSetReportes.SchemaSerializationMode, UI.Reportes.FrmCertificado.toolStripBtnExportarPDF, UI.Reportes.FrmCertificado.toolStripBtnExportarPDF_Click(), UI.Reportes.FrmCertificado.toolStripBtnMail, UI.Reportes.FrmCertificado.toolStripBtnMail_Click(), UI.Reportes.FrmCertificado.toolStripBtnSalir, UI.Reportes.FrmCertificado.toolStripBtnSalir_Click(), and UI.Reportes.FrmCertificado.tspBarraSuperior.
Referenced by UI.Reportes.FrmCertificado.FrmCertificado().
toolStripBtnExportarPDF_Click()
void UI.Reportes.FrmCertificado.toolStripBtnExportarPDF_Click (object sender, EventArgs e) private
Exporta el pdf
Parameters
sender
e
Definition at line 68 of file FrmCertificado.cs.
        {
            try
{
                GenerarPDF();
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el certificado: " + er.Message);
            }
        }
References UI.Reportes.FrmCertificado._MyLogControlEventos, and UI.Reportes.FrmCertificado.GenerarPDF().
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
toolStripBtnMail_Click()
void UI.Reportes.FrmCertificado.toolStripBtnMail_Click (object sender, EventArgs e) private
Envía el mail al correo del usuario
Parameters
sender
e
Definition at line 86 of file FrmCertificado.cs.
        {
            try
            {
                GenerarPDF();
                Thread.Sleep(50);
                MailMessage mensaje = new MailMessage();
                mensaje.From = new MailAddress("alfredosuarezaguilar@gmail.com", "DBACreator");
                mensaje.To.Add(this.correo);
                mensaje.Subject = "Certificado";
                mensaje.Body = "¡Felicidades! Se adjunta su certificación.";
                mensaje.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.Credentials = new NetworkCredential("alfredosuarezaguilar@gmail.com", "Hjxc20d8910");
                smtp.EnableSsl = true;
                Attachment attachment = new Attachment($@"c:\temp\Certificado {idIntento}.pdf");
                mensaje.Attachments.Add(attachment);
                smtp.Send(mensaje);
                MessageBox.Show("Correo Enviado", "Evento", MessageBoxButtons.OK, MessageBoxIcon.Information);
                _MyLogControlEventos.Info($"Mail enviado a {this.correo}");
            }
            catch (Exception er)
            {
                MessageBox.Show(er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                _MyLogControlEventos.Error("Ocurrió el siguiente error en el certificado: " + er.Message);
            }
        }
References UI.Reportes.FrmCertificado._MyLogControlEventos, and UI.Reportes.FrmCertificado.GenerarPDF().
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
toolStripBtnSalir_Click()
void UI.Reportes.FrmCertificado.toolStripBtnSalir_Click (object sender, EventArgs e) private
Cierra la ventana
Parameters
sender
e
Definition at line 58 of file FrmCertificado.cs.
        {
            this.Close();
        }
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Reportes.FrmCertificado._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 24 of file FrmCertificado.cs.
Referenced by UI.Reportes.FrmCertificado.FrmCertificado_Load(), UI.Reportes.FrmCertificado.GenerarPDF(), UI.Reportes.FrmCertificado.toolStripBtnExportarPDF_Click(), and UI.Reportes.FrmCertificado.toolStripBtnMail_Click().
components
System.ComponentModel.IContainer UI.Reportes.FrmCertificado.components = null private
Required designer variable.
Definition at line 9 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.Dispose(), and UI.Reportes.FrmCertificado.InitializeComponent().
correo
string UI.Reportes.FrmCertificado.correo private
Definition at line 22 of file FrmCertificado.cs.
DataSetReportes
DataSetReportes UI.Reportes.FrmCertificado.DataSetReportes private
Definition at line 146 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
idIntento
int UI.Reportes.FrmCertificado.idIntento private
Definition at line 21 of file FrmCertificado.cs.
Referenced by UI.Reportes.FrmCertificado.FrmCertificado(), and UI.Reportes.FrmCertificado.FrmCertificado_Load().
PA_DatosCertificacionBindingSource
System.Windows.Forms.BindingSource UI.Reportes.FrmCertificado.PA_DatosCertificacionBindingSource private
Definition at line 145 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
PA_DatosCertificacionTableAdapter
DataSetReportesTableAdapters.PA_DatosCertificacionTableAdapter UI.Reportes.FrmCertificado.PA_DatosCertificacionTableAdapter private
Definition at line 147 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.FrmCertificado_Load(), and UI.Reportes.FrmCertificado.InitializeComponent().
reportViewer1
Microsoft.Reporting.WinForms.ReportViewer UI.Reportes.FrmCertificado.reportViewer1 private
Definition at line 144 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.FrmCertificado_Load(), UI.Reportes.FrmCertificado.GenerarPDF(), and UI.Reportes.FrmCertificado.InitializeComponent().
ruta
string UI.Reportes.FrmCertificado.ruta private
Definition at line 23 of file FrmCertificado.cs.
Referenced by UI.Reportes.FrmCertificado.GenerarPDF().
toolStripBtnExportarPDF
System.Windows.Forms.ToolStripButton UI.Reportes.FrmCertificado.toolStripBtnExportarPDF private
Definition at line 142 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
toolStripBtnMail
System.Windows.Forms.ToolStripButton UI.Reportes.FrmCertificado.toolStripBtnMail private
Definition at line 148 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UI.Reportes.FrmCertificado.toolStripBtnSalir private
Definition at line 143 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
tspBarraSuperior
System.Windows.Forms.ToolStrip UI.Reportes.FrmCertificado.tspBarraSuperior private
Definition at line 141 of file FrmCertificado.Designer.cs.
Referenced by UI.Reportes.FrmCertificado.InitializeComponent().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Reportes/FrmCertificado.cs
118710756/DbaCreator/UI/Reportes/FrmCertificado.Designer.cs