DBACreator: UI.Menu Class Reference
UI.Menu Class Reference
Public Member Functions
Menu ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Cliente cliente [get, set]
Private Member Functions
void Menu_Load (object sender, EventArgs e)
Revisa el tipo de usuario que entró y muestra las opciones disponibles según lo encontrado
void btnSalir_Click (object sender, EventArgs e)
Pide confirmación para cerrar sesión y abre de nuevo el Login
void mantenimientoExamenesToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del mantenimiento de Examenes
void mantenimientoClienteToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del mantenimiento de Clientes
void mantenimientoDeCertificacionToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del mantenimiento de certificaciones
void facturarExamenToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI de facturación
void realizarExamenToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI de realización de examen
void reporteDeClientesToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del reporte de clientes
void reporteDeVentasToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del reporte de ventas
void reporteDeCertificacionesToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del reporte de examenes
void reporteDeFacturasToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del reporte de clientes certificados
void reporteDeToolStripMenuItem_Click (object sender, EventArgs e)
Crea una nueva ventana MDI del reporte gráfico
void Menu_FormClosed (object sender, FormClosedEventArgs e)
Crea un log que informa del cierre de la app
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip menuStrip
System.Windows.Forms.ToolStripMenuItem itemExamen
System.Windows.Forms.ToolStripMenuItem itemMantenimientos
System.Windows.Forms.ToolStripMenuItem itemReportes
System.Windows.Forms.ToolStripMenuItem reporteDeClientesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem reporteDeVentasToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem btnSalir
System.Windows.Forms.ToolStripMenuItem realizarExamenToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem facturarExamenToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem mantenimientoExamenesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem mantenimientoClientesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem mantenimientoDeCertificacionToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem reporteDeCertificacionesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem reporteDeFacturasToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem reporteDeToolStripMenuItem
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 14 of file Menu.cs.
Constructor & Destructor Documentation
Menu()
UI.Menu.Menu ()
Definition at line 18 of file Menu.cs.
        {
            InitializeComponent();
        }
References UI.Menu.InitializeComponent().
Member Function Documentation
btnSalir_Click()
void UI.Menu.btnSalir_Click (object sender, EventArgs e) private
Pide confirmación para cerrar sesión y abre de nuevo el Login
Parameters
sender
e
Definition at line 49 of file Menu.cs.
        {
            DialogResult respuesta = MessageBox.Show($"Desea Cerrar Sesión?", "Atención", MessageBoxButtons.OKCancel, MessageBoxIcon.Question);
            if (respuesta == DialogResult.OK)
            {
                _MyLogControlEventos.Info("Sesión cerrada");
                this.Hide();
                var frm = new InicioSesion();
                frm.Closed += (s, args) => this.Close();
                frm.Show();
            } else
            {
                return;
            }
        }
References UI.Menu._MyLogControlEventos.
Dispose()
override void UI.Menu.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file Menu.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
References UI.Menu.components.
facturarExamenToolStripMenuItem_Click()
void UI.Menu.facturarExamenToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI de facturación
Parameters
sender
e
Definition at line 110 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Facturación abierto");
            var frm = new FacturacionExamenes();
            frm.AsignarCliente(cliente);
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos, and UI.Menu.cliente.
Referenced by UI.Menu.InitializeComponent().
InitializeComponent()
void UI.Menu.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 30 of file Menu.Designer.cs.
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Menu));
            this.menuStrip = new System.Windows.Forms.MenuStrip();
            this.itemExamen = new System.Windows.Forms.ToolStripMenuItem();
            this.realizarExamenToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.facturarExamenToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.itemMantenimientos = new System.Windows.Forms.ToolStripMenuItem();
            this.mantenimientoClientesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mantenimientoDeCertificacionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mantenimientoExamenesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.itemReportes = new System.Windows.Forms.ToolStripMenuItem();
            this.reporteDeClientesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.reporteDeVentasToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.reporteDeCertificacionesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.reporteDeFacturasToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.reporteDeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.btnSalir = new System.Windows.Forms.ToolStripMenuItem();
            this.menuStrip.SuspendLayout();
            this.SuspendLayout();
            //
            // menuStrip
            //
            this.menuStrip.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.menuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.itemExamen,
            this.itemMantenimientos,
            this.itemReportes,
            this.btnSalir});
            this.menuStrip.Location = new System.Drawing.Point(0, 0);
            this.menuStrip.Name = "menuStrip";
            this.menuStrip.Size = new System.Drawing.Size(1222, 56);
            this.menuStrip.TabIndex = 2;
            this.menuStrip.Text = "menuStrip1";
            //
            // itemExamen
            //
            this.itemExamen.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.realizarExamenToolStripMenuItem,
            this.facturarExamenToolStripMenuItem});
            this.itemExamen.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.itemExamen.Image = ((System.Drawing.Image)(resources.GetObject("itemExamen.Image")));
            this.itemExamen.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.itemExamen.Name = "itemExamen";
            this.itemExamen.Size = new System.Drawing.Size(132, 52);
            this.itemExamen.Text = "Examen";
            //
            // realizarExamenToolStripMenuItem
            //
            this.realizarExamenToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("realizarExamenToolStripMenuItem.Image")));
            this.realizarExamenToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.realizarExamenToolStripMenuItem.Name = "realizarExamenToolStripMenuItem";
            this.realizarExamenToolStripMenuItem.Size = new System.Drawing.Size(265, 72);
            this.realizarExamenToolStripMenuItem.Text = "Realizar Examen";
            this.realizarExamenToolStripMenuItem.Click += new System.EventHandler(this.realizarExamenToolStripMenuItem_Click);
            //
            // facturarExamenToolStripMenuItem
            //
            this.facturarExamenToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("facturarExamenToolStripMenuItem.Image")));
            this.facturarExamenToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.facturarExamenToolStripMenuItem.Name = "facturarExamenToolStripMenuItem";
            this.facturarExamenToolStripMenuItem.Size = new System.Drawing.Size(265, 72);
            this.facturarExamenToolStripMenuItem.Text = "Facturar Examen";
            this.facturarExamenToolStripMenuItem.Click += new System.EventHandler(this.facturarExamenToolStripMenuItem_Click);
            //
            // itemMantenimientos
            //
            this.itemMantenimientos.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mantenimientoClientesToolStripMenuItem,
            this.mantenimientoDeCertificacionToolStripMenuItem,
            this.mantenimientoExamenesToolStripMenuItem});
            this.itemMantenimientos.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.itemMantenimientos.Image = ((System.Drawing.Image)(resources.GetObject("itemMantenimientos.Image")));
            this.itemMantenimientos.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.itemMantenimientos.Name = "itemMantenimientos";
            this.itemMantenimientos.Size = new System.Drawing.Size(196, 52);
            this.itemMantenimientos.Text = "Mantenimientos";
            //
            // mantenimientoClientesToolStripMenuItem
            //
            this.mantenimientoClientesToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("mantenimientoClientesToolStripMenuItem.Image")));
            this.mantenimientoClientesToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.mantenimientoClientesToolStripMenuItem.Name = "mantenimientoClientesToolStripMenuItem";
            this.mantenimientoClientesToolStripMenuItem.Size = new System.Drawing.Size(378, 54);
            this.mantenimientoClientesToolStripMenuItem.Text = "Mantenimiento Clientes";
            this.mantenimientoClientesToolStripMenuItem.Click += new System.EventHandler(this.mantenimientoClienteToolStripMenuItem_Click);
            //
            // mantenimientoDeCertificacionToolStripMenuItem
            //
            this.mantenimientoDeCertificacionToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("mantenimientoDeCertificacionToolStripMenuItem.Image")));
            this.mantenimientoDeCertificacionToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.mantenimientoDeCertificacionToolStripMenuItem.Name = "mantenimientoDeCertificacionToolStripMenuItem";
            this.mantenimientoDeCertificacionToolStripMenuItem.Size = new System.Drawing.Size(378, 54);
            this.mantenimientoDeCertificacionToolStripMenuItem.Text = "Mantenimiento de Certificaciones";
            this.mantenimientoDeCertificacionToolStripMenuItem.Click += new System.EventHandler(this.mantenimientoDeCertificacionToolStripMenuItem_Click);
            //
            // mantenimientoExamenesToolStripMenuItem
            //
            this.mantenimientoExamenesToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("mantenimientoExamenesToolStripMenuItem.Image")));
            this.mantenimientoExamenesToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.mantenimientoExamenesToolStripMenuItem.Name = "mantenimientoExamenesToolStripMenuItem";
            this.mantenimientoExamenesToolStripMenuItem.Size = new System.Drawing.Size(378, 54);
            this.mantenimientoExamenesToolStripMenuItem.Text = "Mantenimiento Examenes";
            this.mantenimientoExamenesToolStripMenuItem.Click += new System.EventHandler(this.mantenimientoExamenesToolStripMenuItem_Click);
            //
            // itemReportes
            //
            this.itemReportes.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.reporteDeClientesToolStripMenuItem,
            this.reporteDeVentasToolStripMenuItem,
            this.reporteDeCertificacionesToolStripMenuItem,
            this.reporteDeFacturasToolStripMenuItem,
            this.reporteDeToolStripMenuItem});
            this.itemReportes.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.itemReportes.Image = ((System.Drawing.Image)(resources.GetObject("itemReportes.Image")));
            this.itemReportes.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.itemReportes.Name = "itemReportes";
            this.itemReportes.Size = new System.Drawing.Size(139, 52);
            this.itemReportes.Text = "Reportes";
            //
            // reporteDeClientesToolStripMenuItem
            //
            this.reporteDeClientesToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("reporteDeClientesToolStripMenuItem.Image")));
            this.reporteDeClientesToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.reporteDeClientesToolStripMenuItem.Name = "reporteDeClientesToolStripMenuItem";
            this.reporteDeClientesToolStripMenuItem.Size = new System.Drawing.Size(372, 54);
            this.reporteDeClientesToolStripMenuItem.Text = "Reporte de Clientes";
            this.reporteDeClientesToolStripMenuItem.Click += new System.EventHandler(this.reporteDeClientesToolStripMenuItem_Click);
            //
            // reporteDeVentasToolStripMenuItem
            //
            this.reporteDeVentasToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("reporteDeVentasToolStripMenuItem.Image")));
            this.reporteDeVentasToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.reporteDeVentasToolStripMenuItem.Name = "reporteDeVentasToolStripMenuItem";
            this.reporteDeVentasToolStripMenuItem.Size = new System.Drawing.Size(372, 54);
            this.reporteDeVentasToolStripMenuItem.Text = "Reporte de Ventas";
            this.reporteDeVentasToolStripMenuItem.Click += new System.EventHandler(this.reporteDeVentasToolStripMenuItem_Click);
            //
            // reporteDeCertificacionesToolStripMenuItem
            //
            this.reporteDeCertificacionesToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("reporteDeCertificacionesToolStripMenuItem.Image")));
            this.reporteDeCertificacionesToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.reporteDeCertificacionesToolStripMenuItem.Name = "reporteDeCertificacionesToolStripMenuItem";
            this.reporteDeCertificacionesToolStripMenuItem.Size = new System.Drawing.Size(372, 54);
            this.reporteDeCertificacionesToolStripMenuItem.Text = "Examenes Realizados por Cliente";
            this.reporteDeCertificacionesToolStripMenuItem.Click += new System.EventHandler(this.reporteDeCertificacionesToolStripMenuItem_Click);
            //
            // reporteDeFacturasToolStripMenuItem
            //
            this.reporteDeFacturasToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("reporteDeFacturasToolStripMenuItem.Image")));
            this.reporteDeFacturasToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.reporteDeFacturasToolStripMenuItem.Name = "reporteDeFacturasToolStripMenuItem";
            this.reporteDeFacturasToolStripMenuItem.Size = new System.Drawing.Size(372, 54);
            this.reporteDeFacturasToolStripMenuItem.Text = "Clientes Certificados";
            this.reporteDeFacturasToolStripMenuItem.Click += new System.EventHandler(this.reporteDeFacturasToolStripMenuItem_Click);
            //
            // reporteDeToolStripMenuItem
            //
            this.reporteDeToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("reporteDeToolStripMenuItem.Image")));
            this.reporteDeToolStripMenuItem.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.reporteDeToolStripMenuItem.Name = "reporteDeToolStripMenuItem";
            this.reporteDeToolStripMenuItem.Size = new System.Drawing.Size(372, 54);
            this.reporteDeToolStripMenuItem.Text = "Gráfico";
            this.reporteDeToolStripMenuItem.Click += new System.EventHandler(this.reporteDeToolStripMenuItem_Click);
            //
            // btnSalir
            //
            this.btnSalir.Font = new System.Drawing.Font("Segoe UI", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSalir.Image = ((System.Drawing.Image)(resources.GetObject("btnSalir.Image")));
            this.btnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.Size = new System.Drawing.Size(173, 52);
            this.btnSalir.Text = "Cerrar Sesión";
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            //
            // Menu
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.MenuHighlight;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.ClientSize = new System.Drawing.Size(1222, 748);
            this.Controls.Add(this.menuStrip);
            this.DoubleBuffered = true;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.MainMenuStrip = this.menuStrip;
            this.Name = "Menu";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Menú Principal";
            this.TransparencyKey = System.Drawing.SystemColors.ActiveCaption;
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Menu_FormClosed);
            this.Load += new System.EventHandler(this.Menu_Load);
            this.menuStrip.ResumeLayout(false);
            this.menuStrip.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
References UI.Menu.btnSalir, UI.Menu.facturarExamenToolStripMenuItem, UI.Menu.facturarExamenToolStripMenuItem_Click(), UI.Menu.itemExamen, UI.Menu.itemMantenimientos, UI.Menu.itemReportes, UI.Menu.mantenimientoClientesToolStripMenuItem, UI.Menu.mantenimientoDeCertificacionToolStripMenuItem, UI.Menu.mantenimientoExamenesToolStripMenuItem, UI.Menu.menuStrip, UI.Menu.realizarExamenToolStripMenuItem, UI.Menu.realizarExamenToolStripMenuItem_Click(), UI.Menu.reporteDeCertificacionesToolStripMenuItem, UI.Menu.reporteDeClientesToolStripMenuItem, UI.Menu.reporteDeFacturasToolStripMenuItem, UI.Menu.reporteDeToolStripMenuItem, and UI.Menu.reporteDeVentasToolStripMenuItem.
Referenced by UI.Menu.Menu().
mantenimientoClienteToolStripMenuItem_Click()
void UI.Menu.mantenimientoClienteToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del mantenimiento de Clientes
Parameters
sender
e
Definition at line 84 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Mantenimiento de clientes abierto");
            var frm = new MantenimientoClientes();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
mantenimientoDeCertificacionToolStripMenuItem_Click()
void UI.Menu.mantenimientoDeCertificacionToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del mantenimiento de certificaciones
Parameters
sender
e
Definition at line 97 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Mantenimiento de certificaciones abierto");
            var frm = new MantenimientoCertificaciones();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
mantenimientoExamenesToolStripMenuItem_Click()
void UI.Menu.mantenimientoExamenesToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del mantenimiento de Examenes
Parameters
sender
e
Definition at line 71 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Mantenimiento de examenes abierto");
            var frm = new MantenimientoExamenes();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
Menu_FormClosed()
void UI.Menu.Menu_FormClosed (object sender, FormClosedEventArgs e) private
Crea un log que informa del cierre de la app
Parameters
sender
e
Definition at line 202 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Aplicación cerrada");
        }
References UI.Menu._MyLogControlEventos.
Menu_Load()
void UI.Menu.Menu_Load (object sender, EventArgs e) private
Revisa el tipo de usuario que entró y muestra las opciones disponibles según lo encontrado
Parameters
sender
e
Definition at line 28 of file Menu.cs.
        {
            if (cliente.IdTipo == 2)
            {
                itemMantenimientos.Visible = false;
                itemReportes.Visible = false;
            }
            else if (cliente.IdTipo == 3)
            {
                itemMantenimientos.Visible = false;
                itemExamen.Visible = false;
            }
            _MyLogControlEventos.Info($"Usuario: {cliente.Id} {cliente.Nombre} {cliente.Apellido}");
        }
References UI.Menu._MyLogControlEventos, UI.Menu.cliente, Capa.Entities.Cliente.IdTipo, UI.Menu.itemExamen, UI.Menu.itemMantenimientos, and UI.Menu.itemReportes.
realizarExamenToolStripMenuItem_Click()
void UI.Menu.realizarExamenToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI de realización de examen
Parameters
sender
e
Definition at line 124 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Realización de Examen abierto");
            var frm = new RealizarExamen(cliente);
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos, and UI.Menu.cliente.
Referenced by UI.Menu.InitializeComponent().
reporteDeCertificacionesToolStripMenuItem_Click()
void UI.Menu.reporteDeCertificacionesToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del reporte de examenes
Parameters
sender
e
Definition at line 163 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Reporte de Examenes realizados por cliente consultado");
            var frm = new Reportes.FrmReporteExamenes();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
reporteDeClientesToolStripMenuItem_Click()
void UI.Menu.reporteDeClientesToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del reporte de clientes
Parameters
sender
e
Definition at line 137 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Reporte de Clientes consultado");
            var frm = new Reportes.FrmReporteClientes();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
reporteDeFacturasToolStripMenuItem_Click()
void UI.Menu.reporteDeFacturasToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del reporte de clientes certificados
Parameters
sender
e
Definition at line 176 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Reporte de clientes certificados consultado");
            var frm = new Reportes.FrmClientesCertificados();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
reporteDeToolStripMenuItem_Click()
void UI.Menu.reporteDeToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del reporte gráfico
Parameters
sender
e
Definition at line 189 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Gráfico de clientes certificados consultado");
            var frm = new Reportes.FrmReporteGrafico();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
reporteDeVentasToolStripMenuItem_Click()
void UI.Menu.reporteDeVentasToolStripMenuItem_Click (object sender, EventArgs e) private
Crea una nueva ventana MDI del reporte de ventas
Parameters
sender
e
Definition at line 150 of file Menu.cs.
        {
            _MyLogControlEventos.Info("Reporte de Ventas consultado");
            var frm = new Reportes.FrmReporteVentas();
            frm.MdiParent = this;
            frm.Show();
        }
References UI.Menu._MyLogControlEventos.
Member Data Documentation
_MyLogControlEventos
readonly log4net.ILog UI.Menu._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 17 of file Menu.cs.
Referenced by UI.Menu.btnSalir_Click(), UI.Menu.facturarExamenToolStripMenuItem_Click(), UI.Menu.mantenimientoClienteToolStripMenuItem_Click(), UI.Menu.mantenimientoDeCertificacionToolStripMenuItem_Click(), UI.Menu.mantenimientoExamenesToolStripMenuItem_Click(), UI.Menu.Menu_FormClosed(), UI.Menu.Menu_Load(), UI.Menu.realizarExamenToolStripMenuItem_Click(), UI.Menu.reporteDeCertificacionesToolStripMenuItem_Click(), UI.Menu.reporteDeClientesToolStripMenuItem_Click(), UI.Menu.reporteDeFacturasToolStripMenuItem_Click(), UI.Menu.reporteDeToolStripMenuItem_Click(), and UI.Menu.reporteDeVentasToolStripMenuItem_Click().
btnSalir
System.Windows.Forms.ToolStripMenuItem UI.Menu.btnSalir private
Definition at line 240 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
components
System.ComponentModel.IContainer UI.Menu.components = null private
Required designer variable.
Definition at line 9 of file Menu.Designer.cs.
Referenced by UI.Menu.Dispose().
facturarExamenToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.facturarExamenToolStripMenuItem private
Definition at line 242 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
itemExamen
System.Windows.Forms.ToolStripMenuItem UI.Menu.itemExamen private
Definition at line 235 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent(), and UI.Menu.Menu_Load().
itemMantenimientos
System.Windows.Forms.ToolStripMenuItem UI.Menu.itemMantenimientos private
Definition at line 236 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent(), and UI.Menu.Menu_Load().
itemReportes
System.Windows.Forms.ToolStripMenuItem UI.Menu.itemReportes private
Definition at line 237 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent(), and UI.Menu.Menu_Load().
mantenimientoClientesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.mantenimientoClientesToolStripMenuItem private
Definition at line 244 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
mantenimientoDeCertificacionToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.mantenimientoDeCertificacionToolStripMenuItem private
Definition at line 245 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
mantenimientoExamenesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.mantenimientoExamenesToolStripMenuItem private
Definition at line 243 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
menuStrip
System.Windows.Forms.MenuStrip UI.Menu.menuStrip private
Definition at line 234 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
realizarExamenToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.realizarExamenToolStripMenuItem private
Definition at line 241 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
reporteDeCertificacionesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.reporteDeCertificacionesToolStripMenuItem private
Definition at line 246 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
reporteDeClientesToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.reporteDeClientesToolStripMenuItem private
Definition at line 238 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
reporteDeFacturasToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.reporteDeFacturasToolStripMenuItem private
Definition at line 247 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
reporteDeToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.reporteDeToolStripMenuItem private
Definition at line 248 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
reporteDeVentasToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem UI.Menu.reporteDeVentasToolStripMenuItem private
Definition at line 239 of file Menu.Designer.cs.
Referenced by UI.Menu.InitializeComponent().
Property Documentation
cliente
Cliente UI.Menu.cliente get set
Definition at line 16 of file Menu.cs.
{ get; set; }
Referenced by UI.Menu.facturarExamenToolStripMenuItem_Click(), UI.Menu.Menu_Load(), and UI.Menu.realizarExamenToolStripMenuItem_Click().
The documentation for this class was generated from the following files:
118710756/DbaCreator/UI/Menu.cs
118710756/DbaCreator/UI/Menu.Designer.cs