DBACreator: Capa.BLL.ExamenLN Class Reference
Capa.BLL.ExamenLN Class Reference
Public Member Functions
void Guardar (Examen e)
Método que guarda el examen en la base de datos, si encuentra un dato con ese ID, lo edita
List< Examen > ObtenerPorCertificacion (int idCertificacion)
Método que busca los examenes por certificación
Examen ObtenerPorID (int id)
Retorna de la tabla Examen el dato con el ID buscado
List< Examen > ObtenerTodos ()
Método para obtener todos los datos de la tabla Examen
void Borrar (int id)
Borra el dato de la tabla con el ID enviado
void Guardar (Examen e)
List< Examen > ObtenerPorCertificacion (int idCertificacion)
Examen ObtenerPorID (int id)
List< Examen > ObtenerTodos ()
void Borrar (int id)
Detailed Description
Definition at line 11 of file ExamenLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.ExamenLN.Borrar (int id)
Borra el dato de la tabla con el ID enviado
Parameters
id ID a buscar
Implements Capa.BLL.IExamenLN.
Definition at line 62 of file ExamenLN.cs.
        {
            ExamenDB.Borrar(id);
        }
References Capa.DAL.ExamenDB.Borrar().
Guardar()
void Capa.BLL.ExamenLN.Guardar (Examen e)
Método que guarda el examen en la base de datos, si encuentra un dato con ese ID, lo edita
Parameters
c Examen del cuál extraerá los datos
Implements Capa.BLL.IExamenLN.
Definition at line 17 of file ExamenLN.cs.
        {
            if (ObtenerPorID(e.ID) == null)
            {
                ExamenDB.Agregar(e);
            }
            else
            {
                ExamenDB.Actualizar(e);
            }
        }
References Capa.DAL.ExamenDB.Actualizar(), Capa.DAL.ExamenDB.Agregar(), Capa.Entities.Examen.ID, and Capa.BLL.ExamenLN.ObtenerPorID().
ObtenerPorCertificacion()
List< Examen > Capa.BLL.ExamenLN.ObtenerPorCertificacion (int idCertificacion)
Método que busca los examenes por certificación
Parameters
idCertificacion ID de certificación a buscar
Returns
retorna una lista de examenes que pertenecen a una certificación
Implements Capa.BLL.IExamenLN.
Definition at line 34 of file ExamenLN.cs.
        {
            return ExamenDB.SeleccionarPorCertificacion(idCertificacion);
        }
References Capa.DAL.ExamenDB.SeleccionarPorCertificacion().
ObtenerPorID()
Examen Capa.BLL.ExamenLN.ObtenerPorID (int id)
Retorna de la tabla Examen el dato con el ID buscado
Parameters
id ID a buscar
Returns
Retorna de la tabla Examen el dato con el ID buscado
Implements Capa.BLL.IExamenLN.
Definition at line 44 of file ExamenLN.cs.
        {
            return ExamenDB.SeleccionarPorId(id);
        }
References Capa.DAL.ExamenDB.SeleccionarPorId().
Referenced by Capa.BLL.ExamenLN.Guardar().
ObtenerTodos()
List< Examen > Capa.BLL.ExamenLN.ObtenerTodos ()
Método para obtener todos los datos de la tabla Examen
Returns
Retorna una lista con todos los datos de la tabla Examen
Implements Capa.BLL.IExamenLN.
Definition at line 53 of file ExamenLN.cs.
        {
            return ExamenDB.ObtenerTodos();
        }
References Capa.DAL.ExamenDB.ObtenerTodos().
The documentation for this class was generated from the following file:
118710756/DbaCreator/Capa.BLL/ExamenLN.cs