DBACreator: Capa.BLL.IPreguntaLN Interface Reference
Capa.BLL.IPreguntaLN Interface Reference
Interfaz pregunta, la documentación de los métodos está en la clase hijo
Public Member Functions
List< Pregunta > SeleccionarPorExamen (int idExamen)
void Guardar (Pregunta p)
Pregunta ObtenerPorID (int id)
void Borrar (int id)
Detailed Description
Interfaz pregunta, la documentación de los métodos está en la clase hijo
Definition at line 13 of file IPreguntaLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.IPreguntaLN.Borrar (int id)
Implemented in Capa.BLL.PreguntaLN.
Referenced by UI.MantenimientoPreguntas.toolStripBtnBorrar_Click().
Guardar()
void Capa.BLL.IPreguntaLN.Guardar (Pregunta p)
Implemented in Capa.BLL.PreguntaLN.
Referenced by UI.MantenimientoPreguntas.btnAceptar_Click().
ObtenerPorID()
Pregunta Capa.BLL.IPreguntaLN.ObtenerPorID (int id)
Implemented in Capa.BLL.PreguntaLN.
SeleccionarPorExamen()
List< Pregunta > Capa.BLL.IPreguntaLN.SeleccionarPorExamen (int idExamen)
Implemented in Capa.BLL.PreguntaLN.
Referenced by UI.MantenimientoPreguntas.CargarDatos(), and UI.RealizarExamen.comenzarExamen().
The documentation for this interface was generated from the following file:
118710756/DbaCreator/Capa.BLL/Interfaces/IPreguntaLN.cs