DBACreator: Capa.BLL.IFacturaLN Interface Reference
Capa.BLL.IFacturaLN Interface Reference
Interfaz factura, la documentación de los métodos está en la clase hijo
Public Member Functions
void Guardar (EncFactura factura)
int ObtenerNumeroDeFacturaActual ()
Detailed Description
Interfaz factura, la documentación de los métodos está en la clase hijo
Definition at line 13 of file IFacturaLN.cs.
Member Function Documentation
Guardar()
void Capa.BLL.IFacturaLN.Guardar (EncFactura factura)
Implemented in Capa.BLL.FacturaLN.
Referenced by UI.FacturacionExamenes.toolStripBtnFacturar_Click().
ObtenerNumeroDeFacturaActual()
int Capa.BLL.IFacturaLN.ObtenerNumeroDeFacturaActual ()
Implemented in Capa.BLL.FacturaLN.
Referenced by UI.FacturacionExamenes.FacturacionExamenes_Load(), and UI.FacturacionExamenes.toolStripBtnNuevo_Click().
The documentation for this interface was generated from the following file:
118710756/DbaCreator/Capa.BLL/Interfaces/IFacturaLN.cs