DBACreator: Capa.BLL.IExamenLN Interface Reference
Capa.BLL.IExamenLN Interface Reference
Interfaz examen, la documentación de los métodos está en la clase hijo
Public Member Functions
void Guardar (Examen e)
List< Examen > ObtenerPorCertificacion (int idCertificacion)
Examen ObtenerPorID (int id)
List< Examen > ObtenerTodos ()
void Borrar (int id)
Detailed Description
Interfaz examen, la documentación de los métodos está en la clase hijo
Definition at line 13 of file IExamenLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.IExamenLN.Borrar (int id)
Implemented in Capa.BLL.ExamenLN.
Referenced by UI.MantenimientoExamenes.toolStripBtnBorrar_Click().
Guardar()
void Capa.BLL.IExamenLN.Guardar (Examen e)
Implemented in Capa.BLL.ExamenLN.
Referenced by UI.MantenimientoExamenes.btnAceptar_Click().
ObtenerPorCertificacion()
List< Examen > Capa.BLL.IExamenLN.ObtenerPorCertificacion (int idCertificacion)
Implemented in Capa.BLL.ExamenLN.
Referenced by UI.FacturacionExamenes.cmbCertis_SelectedIndexChanged(), and UI.FacturacionExamenes.FacturacionExamenes_Load().
ObtenerPorID()
Examen Capa.BLL.IExamenLN.ObtenerPorID (int id)
Implemented in Capa.BLL.ExamenLN.
Referenced by UI.RealizarExamen.comenzarExamen().
ObtenerTodos()
List< Examen > Capa.BLL.IExamenLN.ObtenerTodos ()
Implemented in Capa.BLL.ExamenLN.
Referenced by UI.MantenimientoExamenes.CargarDatos().
The documentation for this interface was generated from the following file:
118710756/DbaCreator/Capa.BLL/Interfaces/IExamenLN.cs