DBACreator: Capa.BLL.IClienteLN Interface Reference
Capa.BLL.IClienteLN Interface Reference
Interfaz cliente, la documentación de los métodos está en la clase hijo
Public Member Functions
void Guardar (Cliente c)
Cliente ObtenerPorID (int id)
Cliente ObtenerPorTelefono (string telefono)
Cliente ObtenerPorCorreo (string email)
List< Cliente > ObtenerTodos ()
void Borrar (string id)
void Actualizar (Cliente c, int idViejo)
Detailed Description
Interfaz cliente, la documentación de los métodos está en la clase hijo
Definition at line 13 of file IClienteLN.cs.
Member Function Documentation
Actualizar()
void Capa.BLL.IClienteLN.Actualizar (Cliente c, int idViejo)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.MantenimientoClientes.btnAceptar_Click().
Borrar()
void Capa.BLL.IClienteLN.Borrar (string id)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.MantenimientoClientes.toolStripBtnBorrar_Click().
Guardar()
void Capa.BLL.IClienteLN.Guardar (Cliente c)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.Registro.btnRegistrar_Click().
ObtenerPorCorreo()
Cliente Capa.BLL.IClienteLN.ObtenerPorCorreo (string email)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.Registro.btnRegistrar_Click().
ObtenerPorID()
Cliente Capa.BLL.IClienteLN.ObtenerPorID (int id)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.InicioSesion.btnLogIn_Click(), and UI.Registro.btnRegistrar_Click().
ObtenerPorTelefono()
Cliente Capa.BLL.IClienteLN.ObtenerPorTelefono (string telefono)
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.Registro.btnRegistrar_Click().
ObtenerTodos()
List< Cliente > Capa.BLL.IClienteLN.ObtenerTodos ()
Implemented in Capa.BLL.ClienteLN.
Referenced by UI.MantenimientoClientes.CargarDatos().
The documentation for this interface was generated from the following file:
118710756/DbaCreator/Capa.BLL/Interfaces/IClienteLN.cs