DBACreator: Capa.BLL.ICertificacionLN Interface Reference
Capa.BLL.ICertificacionLN Interface Reference
Interfaz de certificacionLN, la documentación de los métodos está en la clase hijo
Public Member Functions
void Guardar (Certificacion c)
Certificacion ObtenerPorID (int id)
List< Certificacion > ObtenerTodos ()
void Borrar (int id)
Detailed Description
Interfaz de certificacionLN, la documentación de los métodos está en la clase hijo
Definition at line 13 of file ICertificacionLN.cs.
Member Function Documentation
Borrar()
void Capa.BLL.ICertificacionLN.Borrar (int id)
Implemented in Capa.BLL.CertificacionLN.
Referenced by UI.MantenimientoCertificaciones.toolStripBtnBorrar_Click().
Guardar()
void Capa.BLL.ICertificacionLN.Guardar (Certificacion c)
Implemented in Capa.BLL.CertificacionLN.
Referenced by UI.MantenimientoCertificaciones.btnAceptar_Click().
ObtenerPorID()
Certificacion Capa.BLL.ICertificacionLN.ObtenerPorID (int id)
Implemented in Capa.BLL.CertificacionLN.
ObtenerTodos()
List< Certificacion > Capa.BLL.ICertificacionLN.ObtenerTodos ()
Implemented in Capa.BLL.CertificacionLN.
Referenced by UI.MantenimientoCertificaciones.CargarDatos(), UI.FacturacionExamenes.FacturacionExamenes_Load(), and UI.MantenimientoExamenes.MantenimientoExamenes_Load().
The documentation for this interface was generated from the following file:
118710756/DbaCreator/Capa.BLL/Interfaces/ICertificacionLN.cs